formal_android_mirror_testaRumblingVolcanoMapInfoConfig = {
[1] = { id=1, base_reel_weight_config="RumblingVolcanoBaseReelWeightConfig", feature_reel_weight_config="RumblingVolcanoFeatureReelWeightConfig", fire_reel_weight_config="RumblingVolcanoFireReelWeightConfig", other_config="RumblingVolcanoOthersConfig", multiplier_config="RumblingVolcanoMultiplierConfig"},
[2] = { id=2, base_reel_weight_config="RumblingVolcanoBaseReelWeightConfig", feature_reel_weight_config="RumblingVolcanoFeatureReelWeightConfig", fire_reel_weight_config="RumblingVolcanoFireReelWeightConfig", other_config="RumblingVolcanoOthersConfig", multiplier_config="RumblingVolcanoMultiplierConfig"},
[3] = { id=3, base_reel_weight_config="RumblingVolcanoBaseReelWeight1Config", feature_reel_weight_config="RumblingVolcanoFeatureReelWeightConfig", fire_reel_weight_config="RumblingVolcanoFireReelWeightConfig", other_config="RumblingVolcanoOthers1Config", multiplier_config="RumblingVolcanoMultiplierConfig"},
[4] = { id=4, base_reel_weight_config="RumblingVolcanoBaseReelWeight2Config", feature_reel_weight_config="RumblingVolcanoFeatureReelWeightConfig", fire_reel_weight_config="RumblingVolcanoFireReelWeightConfig", other_config="RumblingVolcanoOthers2Config", multiplier_config="RumblingVolcanoMultiplierConfig"},
[5] = { id=5, base_reel_weight_config="RumblingVolcanoBaseReelWeight3Config", feature_reel_weight_config="RumblingVolcanoFeatureReelWeightConfig", fire_reel_weight_config="RumblingVolcanoFireReelWeightConfig", other_config="RumblingVolcanoOthers3Config", multiplier_config="RumblingVolcanoMultiplier3Config"},
[6] = { id=6, base_reel_weight_config="RumblingVolcanoBaseReelWeight4Config", feature_reel_weight_config="RumblingVolcanoFeatureReelWeightConfig", fire_reel_weight_config="RumblingVolcanoFireReelWeightConfig", other_config="RumblingVolcanoOthers4Config", multiplier_config="RumblingVolcanoMultiplierConfig"},
[7] = { id=7, base_reel_weight_config="RumblingVolcanoBaseReelWeight5Config", feature_reel_weight_config="RumblingVolcanoFeatureReelWeightConfig", fire_reel_weight_config="RumblingVolcanoFireReelWeight5Config", other_config="RumblingVolcanoOthers5Config", multiplier_config="RumblingVolcanoMultiplierConfig"},
[8] = { id=8, base_reel_weight_config="RumblingVolcanoBaseReelWeight6Config", feature_reel_weight_config="RumblingVolcanoFeatureReelWeightConfig", fire_reel_weight_config="RumblingVolcanoFireReelWeight6Config", other_config="RumblingVolcanoOthers6Config", multiplier_config="RumblingVolcanoMultiplierConfig"},
[9] = { id=9, base_reel_weight_config="RumblingVolcanoBaseReelWeightConfig", feature_reel_weight_config="RumblingVolcanoFeatureReelWeightConfig", fire_reel_weight_config="RumblingVolcanoFireReelWeight6Config", other_config="RumblingVolcanoOthers7Config", multiplier_config="RumblingVolcanoMultiplierConfig"},
[10] = { id=10, base_reel_weight_config="RumblingVolcanoBaseReelWeight7Config", feature_reel_weight_config="RumblingVolcanoFeatureReelWeightConfig", fire_reel_weight_config="RumblingVolcanoFireReelWeightConfig", other_config="RumblingVolcanoOthers8Config", multiplier_config="RumblingVolcanoMultiplierConfig"},
}