module("ActionType", package.seeall)

ActionTypes = {
    TakePhoto = 1,
    TakePhotoFaker = 2,
    ReplaceItem = 3,
    LockItem = 4,
    EnterBonus = 5,
    DragonFlyWithFire = 6,
    DragonFly = 7,
    NightKing = 8,
    Respin = 9,
    CombineItem = 10,
    Ice777Dobule7 = 11,
    Ice777Respin = 12,
    DaanLockItem = 13,
    TheSlotFather = 14,
    SetColLock = 15,
    HorizontalShift = 16,
    FrozenTrigger = 17,
    ScatterTrigger = 18,
    MoveWildTrigger = 19,
    FeatureSpin = 20,
    SelectNeed = 21,
    WholeColWild = 22, --整列为wild
    NewLegendLock = 23,
    SwitchSpinType = 24, --切换spin类型
    CoinInfoArr = 25, --金币信息数组
    NewLegendFreeSpin = 26, --弹出free spin界面
    CollectItem = 30, --spin时的道具收集
    MultiplierFeature = 31,
    ExpandingWild = 32,
    CollectThrowCoin = 33,
    GameJackpotPool = 34, --游戏内的Jackpot奖池信息
    TriggerFreeSpin = 35, --弹出free spin界面
    HoldSpinSettle = 36, --HoldSpin结算信息
    TotalFreeSpinWin = 37, --Freespin结束时弹出总奖励
    WildEffect = 38, --Wild效果
    DacingDrumsPotStatus = 39, --0空，1半满，2满
    WinGameJackpot = 41, --赢取了游戏的jackpot
    SpinWildPosSettle = 42, --Spin的wild的结算
    SpinSpecialItemSettle = 43, --Spin的特殊图标的结算
    FreeSpinWinMultiple = 44, --free_spin的赢取加倍
    FreeSpinSettle = 45, --free_spin结算
    SuperStackReplaceItemId = 46, --替换图标id
    ExtraPayout = 47, --记录额外赔付数据
    ClassicGameInfo = 48, --触发Classic Game的信息
    BaseLineWinChip = 49, --基础连线的赢钱
    SuperFreeSpinProgress = 50, --super free_spin进度
    ClassicJackpotPool = 51, --Classic内的Jackpot奖池信息
    FreeSpinTimesAdd = 52, --free_spin次数增加
    RevealInfo = 53,
    CurrentWinChip = 54,
    ShowFreeSpinBoutsBySub = 847860152, --显示扣除制定数量后的free_spin次数（方便客户端同步free_spin次数时，先扣除，然后用动画加上特性触发增加的free_spin次数）
    SpinPiggyValue = 55,
    PiggyEnterMap = 56,
    PiggyFormationId = 8,
    ChangeBetAmount = 57, --改变bet amount
    VolcanoSproutInfo = 58, --火山喷发消息
    RoundInfo = 59, --本轮次数
    WildFly = 60, --Wild飞行效果
    WildRoundEffect = 61, --一轮后wild的替换位置
    SuperFreeSpinInfo = 62,
    ScatterInfo = 63,
    HoneyUpdateLevel = 65, -- 更新蜜蜂蜜罐等级
    HoneyInitWildValue = 67,
    HoneyUpdateWildValue = 68,
    LuckyChristmasAddSpin = 69,
    NudgeReel = 70
}
