module("GameType")

AllTypes = {
    OpenSesame = 4,
    DragonTale = 5,
    ForbiddenCity = 6,
    Vampire = 7,
    FruitSlice = 8,
    PharaohTreasure = 9,
    ElvesEpic = 10,
    HalloweenNight = 11,
    AliceinWonderland = 12,
    Pirate = 13,
    SantaSuprise = 14,
    BacktoJurassic = 15,
    ChefsChoice = 16,
    WildCircus = 17,
    AgentBond = 18,
    LegendsofOlympus = 19,
    ChineseNewYear = 20,
    BruceLee = 21, --李小龙
    IceAndFire = 22,
    LuxuryLife = 23,
    CashSpin = 24,
    PurrfectPets = 25,
    SummerBeach = 26,
    WorldCup = 27,
    LeprechaunTreasure = 28,
    Ice777 = 29,
    Mega5xWins = 30,
    PresidentTrump = 31, --@Daan
    WestWorld = 32,
    TheSlotFather = 33,
    FrozenEra = 35,
    LittleRed = 34,
    NewPurrfectPets = 36,
    PiggyJackpot = 37,
    NewLeprechaunTreasure = 38, --新小绿人
    NewLegendsOfOlympus = 39,
    DancingDrums = 40, --打鼓
    GoldMine = 41, --金矿
    NewWildCircus = 42, --新马戏团
    VampireRose = 43, --吸血鬼
    NewBacktoJurassic = 44, --新侏罗纪
    ThunderZeus = 45, --雷神宙斯
    RapidHit = 46,
    CashRain = 47,
    NewAliceinWonderland = 48,
    TikiIsland = 49,
    RumblingVolcano = 50,
    MagicScarab = 51,
    HoneyFortune = 52,
    LuckyChristmas = 53,
    NewPirate = 54,
    TestGame = 999
}

NewGameTypes = {
    [AllTypes.IceAndFire] = 1,
    [AllTypes.TheSlotFather] = 1,
    [AllTypes.NewBacktoJurassic] = 1,
    [AllTypes.PiggyJackpot] = 1,
    [AllTypes.NewLeprechaunTreasure] = 1,
    [AllTypes.DancingDrums] = 1,
    [AllTypes.NewWildCircus] = 1,
    [AllTypes.RapidHit] = 1,
    [AllTypes.NewAliceinWonderland] = 1,
    [AllTypes.ThunderZeus] = 1,
    [AllTypes.TikiIsland] = 1,
    [AllTypes.RumblingVolcano] = 1,
    [AllTypes.MagicScarab] = 1,
    [AllTypes.HoneyFortune] = 1,
    [AllTypes.LuckyChristmas] = 1,
    [AllTypes.NewLegendsOfOlympus] = 1,
    [AllTypes.FrozenEra] = 1,
    [AllTypes.CashRain] = 1,
    [AllTypes.VampireRose] = 1,
    [AllTypes.NewPurrfectPets] = 1,
    [AllTypes.GoldMine] = 1,
    [AllTypes.NewPirate] = 1,
    [AllTypes.TestGame] = 1
}
