-- Generated By protoc-gen-lua Do not Edit
require "protobuf"
module('Account_pb', package.seeall)


ACCOUNT = protobuf.Descriptor();
local ACCOUNT_ACCOUNT_TYPE_FIELD = protobuf.FieldDescriptor();
local ACCOUNT_FACEBOOK_ID_FIELD = protobuf.FieldDescriptor();
local ACCOUNT_GOOGLE_ID_FIELD = protobuf.FieldDescriptor();

ACCOUNT_ACCOUNT_TYPE_FIELD.name = "account_type"
ACCOUNT_ACCOUNT_TYPE_FIELD.full_name = ".Account.account_type"
ACCOUNT_ACCOUNT_TYPE_FIELD.number = 1
ACCOUNT_ACCOUNT_TYPE_FIELD.index = 0
ACCOUNT_ACCOUNT_TYPE_FIELD.label = 1
ACCOUNT_ACCOUNT_TYPE_FIELD.has_default_value = false
ACCOUNT_ACCOUNT_TYPE_FIELD.default_value = ""
ACCOUNT_ACCOUNT_TYPE_FIELD.type = 9
ACCOUNT_ACCOUNT_TYPE_FIELD.cpp_type = 9

ACCOUNT_FACEBOOK_ID_FIELD.name = "facebook_id"
ACCOUNT_FACEBOOK_ID_FIELD.full_name = ".Account.facebook_id"
ACCOUNT_FACEBOOK_ID_FIELD.number = 2
ACCOUNT_FACEBOOK_ID_FIELD.index = 1
ACCOUNT_FACEBOOK_ID_FIELD.label = 1
ACCOUNT_FACEBOOK_ID_FIELD.has_default_value = false
ACCOUNT_FACEBOOK_ID_FIELD.default_value = ""
ACCOUNT_FACEBOOK_ID_FIELD.type = 9
ACCOUNT_FACEBOOK_ID_FIELD.cpp_type = 9

ACCOUNT_GOOGLE_ID_FIELD.name = "google_id"
ACCOUNT_GOOGLE_ID_FIELD.full_name = ".Account.google_id"
ACCOUNT_GOOGLE_ID_FIELD.number = 3
ACCOUNT_GOOGLE_ID_FIELD.index = 2
ACCOUNT_GOOGLE_ID_FIELD.label = 1
ACCOUNT_GOOGLE_ID_FIELD.has_default_value = false
ACCOUNT_GOOGLE_ID_FIELD.default_value = ""
ACCOUNT_GOOGLE_ID_FIELD.type = 9
ACCOUNT_GOOGLE_ID_FIELD.cpp_type = 9

ACCOUNT.name = "Account"
ACCOUNT.full_name = ".Account"
ACCOUNT.nested_types = {}
ACCOUNT.enum_types = {}
ACCOUNT.fields = {ACCOUNT_ACCOUNT_TYPE_FIELD, ACCOUNT_FACEBOOK_ID_FIELD, ACCOUNT_GOOGLE_ID_FIELD}
ACCOUNT.is_extendable = false
ACCOUNT.extensions = {}

Account = protobuf.Message(ACCOUNT)

