-- Generated By protoc-gen-lua Do not Edit
require "protobuf"
module('Client_pb', package.seeall)


CLIENT = protobuf.Descriptor();
local CLIENT_APP_NAME_FIELD = protobuf.FieldDescriptor();
local CLIENT_PACKAGE_FIELD = protobuf.FieldDescriptor();
local CLIENT_VERSION_FIELD = protobuf.FieldDescriptor();
local CLIENT_CHANNEL_FIELD = protobuf.FieldDescriptor();
local CLIENT_ETH_IP_FIELD = protobuf.FieldDescriptor();
local CLIENT_IP_FIELD = protobuf.FieldDescriptor();
local CLIENT_MAC_FIELD = protobuf.FieldDescriptor();
local CLIENT_DEVICE_FIELD = protobuf.FieldDescriptor();
local CLIENT_OS_FIELD = protobuf.FieldDescriptor();
local CLIENT_OS_VERSION_FIELD = protobuf.FieldDescriptor();
local CLIENT_IMEI_IDFA_FIELD = protobuf.FieldDescriptor();
local CLIENT_DEVICE_ID_FIELD = protobuf.FieldDescriptor();
local CLIENT_DEVICE_TOKEN_FIELD = protobuf.FieldDescriptor();

CLIENT_APP_NAME_FIELD.name = "app_name"
CLIENT_APP_NAME_FIELD.full_name = ".Client.app_name"
CLIENT_APP_NAME_FIELD.number = 1
CLIENT_APP_NAME_FIELD.index = 0
CLIENT_APP_NAME_FIELD.label = 1
CLIENT_APP_NAME_FIELD.has_default_value = false
CLIENT_APP_NAME_FIELD.default_value = ""
CLIENT_APP_NAME_FIELD.type = 9
CLIENT_APP_NAME_FIELD.cpp_type = 9

CLIENT_PACKAGE_FIELD.name = "package"
CLIENT_PACKAGE_FIELD.full_name = ".Client.package"
CLIENT_PACKAGE_FIELD.number = 2
CLIENT_PACKAGE_FIELD.index = 1
CLIENT_PACKAGE_FIELD.label = 1
CLIENT_PACKAGE_FIELD.has_default_value = false
CLIENT_PACKAGE_FIELD.default_value = ""
CLIENT_PACKAGE_FIELD.type = 9
CLIENT_PACKAGE_FIELD.cpp_type = 9

CLIENT_VERSION_FIELD.name = "version"
CLIENT_VERSION_FIELD.full_name = ".Client.version"
CLIENT_VERSION_FIELD.number = 3
CLIENT_VERSION_FIELD.index = 2
CLIENT_VERSION_FIELD.label = 1
CLIENT_VERSION_FIELD.has_default_value = false
CLIENT_VERSION_FIELD.default_value = ""
CLIENT_VERSION_FIELD.type = 9
CLIENT_VERSION_FIELD.cpp_type = 9

CLIENT_CHANNEL_FIELD.name = "channel"
CLIENT_CHANNEL_FIELD.full_name = ".Client.channel"
CLIENT_CHANNEL_FIELD.number = 4
CLIENT_CHANNEL_FIELD.index = 3
CLIENT_CHANNEL_FIELD.label = 1
CLIENT_CHANNEL_FIELD.has_default_value = false
CLIENT_CHANNEL_FIELD.default_value = ""
CLIENT_CHANNEL_FIELD.type = 9
CLIENT_CHANNEL_FIELD.cpp_type = 9

CLIENT_ETH_IP_FIELD.name = "eth_ip"
CLIENT_ETH_IP_FIELD.full_name = ".Client.eth_ip"
CLIENT_ETH_IP_FIELD.number = 5
CLIENT_ETH_IP_FIELD.index = 4
CLIENT_ETH_IP_FIELD.label = 1
CLIENT_ETH_IP_FIELD.has_default_value = false
CLIENT_ETH_IP_FIELD.default_value = ""
CLIENT_ETH_IP_FIELD.type = 9
CLIENT_ETH_IP_FIELD.cpp_type = 9

CLIENT_IP_FIELD.name = "ip"
CLIENT_IP_FIELD.full_name = ".Client.ip"
CLIENT_IP_FIELD.number = 6
CLIENT_IP_FIELD.index = 5
CLIENT_IP_FIELD.label = 1
CLIENT_IP_FIELD.has_default_value = false
CLIENT_IP_FIELD.default_value = ""
CLIENT_IP_FIELD.type = 9
CLIENT_IP_FIELD.cpp_type = 9

CLIENT_MAC_FIELD.name = "mac"
CLIENT_MAC_FIELD.full_name = ".Client.mac"
CLIENT_MAC_FIELD.number = 7
CLIENT_MAC_FIELD.index = 6
CLIENT_MAC_FIELD.label = 1
CLIENT_MAC_FIELD.has_default_value = false
CLIENT_MAC_FIELD.default_value = ""
CLIENT_MAC_FIELD.type = 9
CLIENT_MAC_FIELD.cpp_type = 9

CLIENT_DEVICE_FIELD.name = "device"
CLIENT_DEVICE_FIELD.full_name = ".Client.device"
CLIENT_DEVICE_FIELD.number = 8
CLIENT_DEVICE_FIELD.index = 7
CLIENT_DEVICE_FIELD.label = 1
CLIENT_DEVICE_FIELD.has_default_value = false
CLIENT_DEVICE_FIELD.default_value = ""
CLIENT_DEVICE_FIELD.type = 9
CLIENT_DEVICE_FIELD.cpp_type = 9

CLIENT_OS_FIELD.name = "os"
CLIENT_OS_FIELD.full_name = ".Client.os"
CLIENT_OS_FIELD.number = 9
CLIENT_OS_FIELD.index = 8
CLIENT_OS_FIELD.label = 1
CLIENT_OS_FIELD.has_default_value = false
CLIENT_OS_FIELD.default_value = ""
CLIENT_OS_FIELD.type = 9
CLIENT_OS_FIELD.cpp_type = 9

CLIENT_OS_VERSION_FIELD.name = "os_version"
CLIENT_OS_VERSION_FIELD.full_name = ".Client.os_version"
CLIENT_OS_VERSION_FIELD.number = 10
CLIENT_OS_VERSION_FIELD.index = 9
CLIENT_OS_VERSION_FIELD.label = 1
CLIENT_OS_VERSION_FIELD.has_default_value = false
CLIENT_OS_VERSION_FIELD.default_value = ""
CLIENT_OS_VERSION_FIELD.type = 9
CLIENT_OS_VERSION_FIELD.cpp_type = 9

CLIENT_IMEI_IDFA_FIELD.name = "imei_idfa"
CLIENT_IMEI_IDFA_FIELD.full_name = ".Client.imei_idfa"
CLIENT_IMEI_IDFA_FIELD.number = 11
CLIENT_IMEI_IDFA_FIELD.index = 10
CLIENT_IMEI_IDFA_FIELD.label = 1
CLIENT_IMEI_IDFA_FIELD.has_default_value = false
CLIENT_IMEI_IDFA_FIELD.default_value = ""
CLIENT_IMEI_IDFA_FIELD.type = 9
CLIENT_IMEI_IDFA_FIELD.cpp_type = 9

CLIENT_DEVICE_ID_FIELD.name = "device_id"
CLIENT_DEVICE_ID_FIELD.full_name = ".Client.device_id"
CLIENT_DEVICE_ID_FIELD.number = 12
CLIENT_DEVICE_ID_FIELD.index = 11
CLIENT_DEVICE_ID_FIELD.label = 1
CLIENT_DEVICE_ID_FIELD.has_default_value = false
CLIENT_DEVICE_ID_FIELD.default_value = ""
CLIENT_DEVICE_ID_FIELD.type = 9
CLIENT_DEVICE_ID_FIELD.cpp_type = 9

CLIENT_DEVICE_TOKEN_FIELD.name = "device_token"
CLIENT_DEVICE_TOKEN_FIELD.full_name = ".Client.device_token"
CLIENT_DEVICE_TOKEN_FIELD.number = 13
CLIENT_DEVICE_TOKEN_FIELD.index = 12
CLIENT_DEVICE_TOKEN_FIELD.label = 1
CLIENT_DEVICE_TOKEN_FIELD.has_default_value = false
CLIENT_DEVICE_TOKEN_FIELD.default_value = ""
CLIENT_DEVICE_TOKEN_FIELD.type = 9
CLIENT_DEVICE_TOKEN_FIELD.cpp_type = 9

CLIENT.name = "Client"
CLIENT.full_name = ".Client"
CLIENT.nested_types = {}
CLIENT.enum_types = {}
CLIENT.fields = {CLIENT_APP_NAME_FIELD, CLIENT_PACKAGE_FIELD, CLIENT_VERSION_FIELD, CLIENT_CHANNEL_FIELD, CLIENT_ETH_IP_FIELD, CLIENT_IP_FIELD, CLIENT_MAC_FIELD, CLIENT_DEVICE_FIELD, CLIENT_OS_FIELD, CLIENT_OS_VERSION_FIELD, CLIENT_IMEI_IDFA_FIELD, CLIENT_DEVICE_ID_FIELD, CLIENT_DEVICE_TOKEN_FIELD}
CLIENT.is_extendable = false
CLIENT.extensions = {}

Client = protobuf.Message(CLIENT)

