-- Generated By protoc-gen-lua Do not Edit
require "protobuf"
module('ClubInfo_pb', package.seeall)


CLUBINFO = protobuf.Descriptor();
local CLUBINFO_CLUB_ID_FIELD = protobuf.FieldDescriptor();
local CLUBINFO_CUPS_WINNING_FIELD = protobuf.FieldDescriptor();
local CLUBINFO_LAST_FUND_TIMESTAMP_FIELD = protobuf.FieldDescriptor();
local CLUBINFO_JOINED_CLUB_FIELD = protobuf.FieldDescriptor();

CLUBINFO_CLUB_ID_FIELD.name = "club_id"
CLUBINFO_CLUB_ID_FIELD.full_name = ".ClubInfo.club_id"
CLUBINFO_CLUB_ID_FIELD.number = 1
CLUBINFO_CLUB_ID_FIELD.index = 0
CLUBINFO_CLUB_ID_FIELD.label = 1
CLUBINFO_CLUB_ID_FIELD.has_default_value = false
CLUBINFO_CLUB_ID_FIELD.default_value = 0
CLUBINFO_CLUB_ID_FIELD.type = 3
CLUBINFO_CLUB_ID_FIELD.cpp_type = 2

CLUBINFO_CUPS_WINNING_FIELD.name = "cups_winning"
CLUBINFO_CUPS_WINNING_FIELD.full_name = ".ClubInfo.cups_winning"
CLUBINFO_CUPS_WINNING_FIELD.number = 2
CLUBINFO_CUPS_WINNING_FIELD.index = 1
CLUBINFO_CUPS_WINNING_FIELD.label = 1
CLUBINFO_CUPS_WINNING_FIELD.has_default_value = false
CLUBINFO_CUPS_WINNING_FIELD.default_value = 0
CLUBINFO_CUPS_WINNING_FIELD.type = 3
CLUBINFO_CUPS_WINNING_FIELD.cpp_type = 2

CLUBINFO_LAST_FUND_TIMESTAMP_FIELD.name = "last_fund_timestamp"
CLUBINFO_LAST_FUND_TIMESTAMP_FIELD.full_name = ".ClubInfo.last_fund_timestamp"
CLUBINFO_LAST_FUND_TIMESTAMP_FIELD.number = 3
CLUBINFO_LAST_FUND_TIMESTAMP_FIELD.index = 2
CLUBINFO_LAST_FUND_TIMESTAMP_FIELD.label = 1
CLUBINFO_LAST_FUND_TIMESTAMP_FIELD.has_default_value = false
CLUBINFO_LAST_FUND_TIMESTAMP_FIELD.default_value = 0
CLUBINFO_LAST_FUND_TIMESTAMP_FIELD.type = 3
CLUBINFO_LAST_FUND_TIMESTAMP_FIELD.cpp_type = 2

CLUBINFO_JOINED_CLUB_FIELD.name = "joined_club"
CLUBINFO_JOINED_CLUB_FIELD.full_name = ".ClubInfo.joined_club"
CLUBINFO_JOINED_CLUB_FIELD.number = 4
CLUBINFO_JOINED_CLUB_FIELD.index = 3
CLUBINFO_JOINED_CLUB_FIELD.label = 1
CLUBINFO_JOINED_CLUB_FIELD.has_default_value = false
CLUBINFO_JOINED_CLUB_FIELD.default_value = 0
CLUBINFO_JOINED_CLUB_FIELD.type = 3
CLUBINFO_JOINED_CLUB_FIELD.cpp_type = 2

CLUBINFO.name = "ClubInfo"
CLUBINFO.full_name = ".ClubInfo"
CLUBINFO.nested_types = {}
CLUBINFO.enum_types = {}
CLUBINFO.fields = {CLUBINFO_CLUB_ID_FIELD, CLUBINFO_CUPS_WINNING_FIELD, CLUBINFO_LAST_FUND_TIMESTAMP_FIELD, CLUBINFO_JOINED_CLUB_FIELD}
CLUBINFO.is_extendable = false
CLUBINFO.extensions = {}

ClubInfo = protobuf.Message(CLUBINFO)

