-- Generated By protoc-gen-lua Do not Edit
require "protobuf"
module('Common_pb', package.seeall)


RETURN = protobuf.Descriptor();
local RETURN_CODE_FIELD = protobuf.FieldDescriptor();
local RETURN_MSG_FIELD = protobuf.FieldDescriptor();
HEADER = protobuf.Descriptor();
local HEADER_ROUTER_FIELD = protobuf.FieldDescriptor();
local HEADER_SESSION_ID_FIELD = protobuf.FieldDescriptor();
local HEADER_PLAYER_ID_FIELD = protobuf.FieldDescriptor();
local HEADER_CLIENT_ID_FIELD = protobuf.FieldDescriptor();
local HEADER_SERVICE_NAME_FIELD = protobuf.FieldDescriptor();
local HEADER_TASK_ID_FIELD = protobuf.FieldDescriptor();
local HEADER_CHANNEL_ID_FIELD = protobuf.FieldDescriptor();
local HEADER_MODULE_ID_FIELD = protobuf.FieldDescriptor();
local HEADER_MESSAGE_ID_FIELD = protobuf.FieldDescriptor();
local HEADER_TIME_FIELD = protobuf.FieldDescriptor();
local HEADER_SEQUENCE_ID_FIELD = protobuf.FieldDescriptor();

RETURN_CODE_FIELD.name = "code"
RETURN_CODE_FIELD.full_name = ".Return.code"
RETURN_CODE_FIELD.number = 1
RETURN_CODE_FIELD.index = 0
RETURN_CODE_FIELD.label = 2
RETURN_CODE_FIELD.has_default_value = false
RETURN_CODE_FIELD.default_value = 0
RETURN_CODE_FIELD.type = 3
RETURN_CODE_FIELD.cpp_type = 2

RETURN_MSG_FIELD.name = "msg"
RETURN_MSG_FIELD.full_name = ".Return.msg"
RETURN_MSG_FIELD.number = 2
RETURN_MSG_FIELD.index = 1
RETURN_MSG_FIELD.label = 2
RETURN_MSG_FIELD.has_default_value = false
RETURN_MSG_FIELD.default_value = ""
RETURN_MSG_FIELD.type = 9
RETURN_MSG_FIELD.cpp_type = 9

RETURN.name = "Return"
RETURN.full_name = ".Return"
RETURN.nested_types = {}
RETURN.enum_types = {}
RETURN.fields = {RETURN_CODE_FIELD, RETURN_MSG_FIELD}
RETURN.is_extendable = false
RETURN.extensions = {}
HEADER_ROUTER_FIELD.name = "router"
HEADER_ROUTER_FIELD.full_name = ".Header.router"
HEADER_ROUTER_FIELD.number = 1
HEADER_ROUTER_FIELD.index = 0
HEADER_ROUTER_FIELD.label = 1
HEADER_ROUTER_FIELD.has_default_value = false
HEADER_ROUTER_FIELD.default_value = ""
HEADER_ROUTER_FIELD.type = 9
HEADER_ROUTER_FIELD.cpp_type = 9

HEADER_SESSION_ID_FIELD.name = "session_id"
HEADER_SESSION_ID_FIELD.full_name = ".Header.session_id"
HEADER_SESSION_ID_FIELD.number = 2
HEADER_SESSION_ID_FIELD.index = 1
HEADER_SESSION_ID_FIELD.label = 1
HEADER_SESSION_ID_FIELD.has_default_value = false
HEADER_SESSION_ID_FIELD.default_value = 0
HEADER_SESSION_ID_FIELD.type = 3
HEADER_SESSION_ID_FIELD.cpp_type = 2

HEADER_PLAYER_ID_FIELD.name = "player_id"
HEADER_PLAYER_ID_FIELD.full_name = ".Header.player_id"
HEADER_PLAYER_ID_FIELD.number = 3
HEADER_PLAYER_ID_FIELD.index = 2
HEADER_PLAYER_ID_FIELD.label = 1
HEADER_PLAYER_ID_FIELD.has_default_value = false
HEADER_PLAYER_ID_FIELD.default_value = 0
HEADER_PLAYER_ID_FIELD.type = 3
HEADER_PLAYER_ID_FIELD.cpp_type = 2

HEADER_CLIENT_ID_FIELD.name = "client_id"
HEADER_CLIENT_ID_FIELD.full_name = ".Header.client_id"
HEADER_CLIENT_ID_FIELD.number = 4
HEADER_CLIENT_ID_FIELD.index = 3
HEADER_CLIENT_ID_FIELD.label = 1
HEADER_CLIENT_ID_FIELD.has_default_value = false
HEADER_CLIENT_ID_FIELD.default_value = 0
HEADER_CLIENT_ID_FIELD.type = 3
HEADER_CLIENT_ID_FIELD.cpp_type = 2

HEADER_SERVICE_NAME_FIELD.name = "service_name"
HEADER_SERVICE_NAME_FIELD.full_name = ".Header.service_name"
HEADER_SERVICE_NAME_FIELD.number = 5
HEADER_SERVICE_NAME_FIELD.index = 4
HEADER_SERVICE_NAME_FIELD.label = 1
HEADER_SERVICE_NAME_FIELD.has_default_value = false
HEADER_SERVICE_NAME_FIELD.default_value = ""
HEADER_SERVICE_NAME_FIELD.type = 9
HEADER_SERVICE_NAME_FIELD.cpp_type = 9

HEADER_TASK_ID_FIELD.name = "task_id"
HEADER_TASK_ID_FIELD.full_name = ".Header.task_id"
HEADER_TASK_ID_FIELD.number = 6
HEADER_TASK_ID_FIELD.index = 5
HEADER_TASK_ID_FIELD.label = 1
HEADER_TASK_ID_FIELD.has_default_value = false
HEADER_TASK_ID_FIELD.default_value = ""
HEADER_TASK_ID_FIELD.type = 9
HEADER_TASK_ID_FIELD.cpp_type = 9

HEADER_CHANNEL_ID_FIELD.name = "channel_id"
HEADER_CHANNEL_ID_FIELD.full_name = ".Header.channel_id"
HEADER_CHANNEL_ID_FIELD.number = 7
HEADER_CHANNEL_ID_FIELD.index = 6
HEADER_CHANNEL_ID_FIELD.label = 1
HEADER_CHANNEL_ID_FIELD.has_default_value = false
HEADER_CHANNEL_ID_FIELD.default_value = ""
HEADER_CHANNEL_ID_FIELD.type = 9
HEADER_CHANNEL_ID_FIELD.cpp_type = 9

HEADER_MODULE_ID_FIELD.name = "module_id"
HEADER_MODULE_ID_FIELD.full_name = ".Header.module_id"
HEADER_MODULE_ID_FIELD.number = 8
HEADER_MODULE_ID_FIELD.index = 7
HEADER_MODULE_ID_FIELD.label = 1
HEADER_MODULE_ID_FIELD.has_default_value = false
HEADER_MODULE_ID_FIELD.default_value = ""
HEADER_MODULE_ID_FIELD.type = 9
HEADER_MODULE_ID_FIELD.cpp_type = 9

HEADER_MESSAGE_ID_FIELD.name = "message_id"
HEADER_MESSAGE_ID_FIELD.full_name = ".Header.message_id"
HEADER_MESSAGE_ID_FIELD.number = 9
HEADER_MESSAGE_ID_FIELD.index = 8
HEADER_MESSAGE_ID_FIELD.label = 1
HEADER_MESSAGE_ID_FIELD.has_default_value = false
HEADER_MESSAGE_ID_FIELD.default_value = ""
HEADER_MESSAGE_ID_FIELD.type = 9
HEADER_MESSAGE_ID_FIELD.cpp_type = 9

HEADER_TIME_FIELD.name = "time"
HEADER_TIME_FIELD.full_name = ".Header.time"
HEADER_TIME_FIELD.number = 10
HEADER_TIME_FIELD.index = 9
HEADER_TIME_FIELD.label = 1
HEADER_TIME_FIELD.has_default_value = false
HEADER_TIME_FIELD.default_value = 0
HEADER_TIME_FIELD.type = 3
HEADER_TIME_FIELD.cpp_type = 2

HEADER_SEQUENCE_ID_FIELD.name = "sequence_id"
HEADER_SEQUENCE_ID_FIELD.full_name = ".Header.sequence_id"
HEADER_SEQUENCE_ID_FIELD.number = 11
HEADER_SEQUENCE_ID_FIELD.index = 10
HEADER_SEQUENCE_ID_FIELD.label = 1
HEADER_SEQUENCE_ID_FIELD.has_default_value = false
HEADER_SEQUENCE_ID_FIELD.default_value = 0
HEADER_SEQUENCE_ID_FIELD.type = 3
HEADER_SEQUENCE_ID_FIELD.cpp_type = 2

HEADER.name = "Header"
HEADER.full_name = ".Header"
HEADER.nested_types = {}
HEADER.enum_types = {}
HEADER.fields = {HEADER_ROUTER_FIELD, HEADER_SESSION_ID_FIELD, HEADER_PLAYER_ID_FIELD, HEADER_CLIENT_ID_FIELD, HEADER_SERVICE_NAME_FIELD, HEADER_TASK_ID_FIELD, HEADER_CHANNEL_ID_FIELD, HEADER_MODULE_ID_FIELD, HEADER_MESSAGE_ID_FIELD, HEADER_TIME_FIELD, HEADER_SEQUENCE_ID_FIELD}
HEADER.is_extendable = false
HEADER.extensions = {}

Header = protobuf.Message(HEADER)
Return = protobuf.Message(RETURN)

