-- Generated By protoc-gen-lua Do not Edit
require "protobuf"
require "Protocol/Player_pb"
module('Contest_pb', package.seeall)


SEAT = protobuf.Descriptor();
local SEAT_ID_FIELD = protobuf.FieldDescriptor();
local SEAT_PLAYER_FIELD = protobuf.FieldDescriptor();
local SEAT_ONLINE_FIELD = protobuf.FieldDescriptor();
TABLE = protobuf.Descriptor();
local TABLE_SEAT_FIELD = protobuf.FieldDescriptor();
DEVICE = protobuf.Descriptor();
local DEVICE_DEVICE_ID_FIELD = protobuf.FieldDescriptor();
local DEVICE_PLAYER_ID_FIELD = protobuf.FieldDescriptor();
local DEVICE_LUCKY_FIELD = protobuf.FieldDescriptor();
local DEVICE_WIN_FIELD = protobuf.FieldDescriptor();
local DEVICE_ROOM_NAME_FIELD = protobuf.FieldDescriptor();
local DEVICE_NICKNAME_FIELD = protobuf.FieldDescriptor();
local DEVICE_SEX_FIELD = protobuf.FieldDescriptor();

SEAT_ID_FIELD.name = "id"
SEAT_ID_FIELD.full_name = ".Seat.id"
SEAT_ID_FIELD.number = 1
SEAT_ID_FIELD.index = 0
SEAT_ID_FIELD.label = 1
SEAT_ID_FIELD.has_default_value = false
SEAT_ID_FIELD.default_value = 0
SEAT_ID_FIELD.type = 3
SEAT_ID_FIELD.cpp_type = 2

SEAT_PLAYER_FIELD.name = "player"
SEAT_PLAYER_FIELD.full_name = ".Seat.player"
SEAT_PLAYER_FIELD.number = 2
SEAT_PLAYER_FIELD.index = 1
SEAT_PLAYER_FIELD.label = 1
SEAT_PLAYER_FIELD.has_default_value = false
SEAT_PLAYER_FIELD.default_value = nil
SEAT_PLAYER_FIELD.message_type = Player_pb.PLAYER
SEAT_PLAYER_FIELD.type = 11
SEAT_PLAYER_FIELD.cpp_type = 10

SEAT_ONLINE_FIELD.name = "online"
SEAT_ONLINE_FIELD.full_name = ".Seat.online"
SEAT_ONLINE_FIELD.number = 3
SEAT_ONLINE_FIELD.index = 2
SEAT_ONLINE_FIELD.label = 1
SEAT_ONLINE_FIELD.has_default_value = false
SEAT_ONLINE_FIELD.default_value = 0
SEAT_ONLINE_FIELD.type = 3
SEAT_ONLINE_FIELD.cpp_type = 2

SEAT.name = "Seat"
SEAT.full_name = ".Seat"
SEAT.nested_types = {}
SEAT.enum_types = {}
SEAT.fields = {SEAT_ID_FIELD, SEAT_PLAYER_FIELD, SEAT_ONLINE_FIELD}
SEAT.is_extendable = false
SEAT.extensions = {}
TABLE_SEAT_FIELD.name = "seat"
TABLE_SEAT_FIELD.full_name = ".Table.seat"
TABLE_SEAT_FIELD.number = 1
TABLE_SEAT_FIELD.index = 0
TABLE_SEAT_FIELD.label = 3
TABLE_SEAT_FIELD.has_default_value = false
TABLE_SEAT_FIELD.default_value = {}
TABLE_SEAT_FIELD.message_type = SEAT
TABLE_SEAT_FIELD.type = 11
TABLE_SEAT_FIELD.cpp_type = 10

TABLE.name = "Table"
TABLE.full_name = ".Table"
TABLE.nested_types = {}
TABLE.enum_types = {}
TABLE.fields = {TABLE_SEAT_FIELD}
TABLE.is_extendable = false
TABLE.extensions = {}
DEVICE_DEVICE_ID_FIELD.name = "device_id"
DEVICE_DEVICE_ID_FIELD.full_name = ".Device.device_id"
DEVICE_DEVICE_ID_FIELD.number = 1
DEVICE_DEVICE_ID_FIELD.index = 0
DEVICE_DEVICE_ID_FIELD.label = 1
DEVICE_DEVICE_ID_FIELD.has_default_value = false
DEVICE_DEVICE_ID_FIELD.default_value = 0
DEVICE_DEVICE_ID_FIELD.type = 3
DEVICE_DEVICE_ID_FIELD.cpp_type = 2

DEVICE_PLAYER_ID_FIELD.name = "player_id"
DEVICE_PLAYER_ID_FIELD.full_name = ".Device.player_id"
DEVICE_PLAYER_ID_FIELD.number = 2
DEVICE_PLAYER_ID_FIELD.index = 1
DEVICE_PLAYER_ID_FIELD.label = 1
DEVICE_PLAYER_ID_FIELD.has_default_value = false
DEVICE_PLAYER_ID_FIELD.default_value = 0
DEVICE_PLAYER_ID_FIELD.type = 3
DEVICE_PLAYER_ID_FIELD.cpp_type = 2

DEVICE_LUCKY_FIELD.name = "lucky"
DEVICE_LUCKY_FIELD.full_name = ".Device.lucky"
DEVICE_LUCKY_FIELD.number = 3
DEVICE_LUCKY_FIELD.index = 2
DEVICE_LUCKY_FIELD.label = 1
DEVICE_LUCKY_FIELD.has_default_value = false
DEVICE_LUCKY_FIELD.default_value = 0
DEVICE_LUCKY_FIELD.type = 3
DEVICE_LUCKY_FIELD.cpp_type = 2

DEVICE_WIN_FIELD.name = "win"
DEVICE_WIN_FIELD.full_name = ".Device.win"
DEVICE_WIN_FIELD.number = 4
DEVICE_WIN_FIELD.index = 3
DEVICE_WIN_FIELD.label = 1
DEVICE_WIN_FIELD.has_default_value = false
DEVICE_WIN_FIELD.default_value = 0
DEVICE_WIN_FIELD.type = 3
DEVICE_WIN_FIELD.cpp_type = 2

DEVICE_ROOM_NAME_FIELD.name = "room_name"
DEVICE_ROOM_NAME_FIELD.full_name = ".Device.room_name"
DEVICE_ROOM_NAME_FIELD.number = 5
DEVICE_ROOM_NAME_FIELD.index = 4
DEVICE_ROOM_NAME_FIELD.label = 1
DEVICE_ROOM_NAME_FIELD.has_default_value = false
DEVICE_ROOM_NAME_FIELD.default_value = ""
DEVICE_ROOM_NAME_FIELD.type = 9
DEVICE_ROOM_NAME_FIELD.cpp_type = 9

DEVICE_NICKNAME_FIELD.name = "nickname"
DEVICE_NICKNAME_FIELD.full_name = ".Device.nickname"
DEVICE_NICKNAME_FIELD.number = 6
DEVICE_NICKNAME_FIELD.index = 5
DEVICE_NICKNAME_FIELD.label = 1
DEVICE_NICKNAME_FIELD.has_default_value = false
DEVICE_NICKNAME_FIELD.default_value = ""
DEVICE_NICKNAME_FIELD.type = 9
DEVICE_NICKNAME_FIELD.cpp_type = 9

DEVICE_SEX_FIELD.name = "sex"
DEVICE_SEX_FIELD.full_name = ".Device.sex"
DEVICE_SEX_FIELD.number = 7
DEVICE_SEX_FIELD.index = 6
DEVICE_SEX_FIELD.label = 1
DEVICE_SEX_FIELD.has_default_value = false
DEVICE_SEX_FIELD.default_value = 0
DEVICE_SEX_FIELD.type = 3
DEVICE_SEX_FIELD.cpp_type = 2

DEVICE.name = "Device"
DEVICE.full_name = ".Device"
DEVICE.nested_types = {}
DEVICE.enum_types = {}
DEVICE.fields = {DEVICE_DEVICE_ID_FIELD, DEVICE_PLAYER_ID_FIELD, DEVICE_LUCKY_FIELD, DEVICE_WIN_FIELD, DEVICE_ROOM_NAME_FIELD, DEVICE_NICKNAME_FIELD, DEVICE_SEX_FIELD}
DEVICE.is_extendable = false
DEVICE.extensions = {}

Device = protobuf.Message(DEVICE)
Seat = protobuf.Message(SEAT)
Table = protobuf.Message(TABLE)

