-- Generated By protoc-gen-lua Do not Edit
require "protobuf"
module('DailyTask_pb', package.seeall)


ITEM = protobuf.Descriptor();
local ITEM_ID_FIELD = protobuf.FieldDescriptor();
local ITEM_NUMERATOR_FIELD = protobuf.FieldDescriptor();
local ITEM_HAS_FETCHED_FIELD = protobuf.FieldDescriptor();

ITEM_ID_FIELD.name = "id"
ITEM_ID_FIELD.full_name = ".Item.id"
ITEM_ID_FIELD.number = 1
ITEM_ID_FIELD.index = 0
ITEM_ID_FIELD.label = 1
ITEM_ID_FIELD.has_default_value = false
ITEM_ID_FIELD.default_value = 0
ITEM_ID_FIELD.type = 3
ITEM_ID_FIELD.cpp_type = 2

ITEM_NUMERATOR_FIELD.name = "numerator"
ITEM_NUMERATOR_FIELD.full_name = ".Item.numerator"
ITEM_NUMERATOR_FIELD.number = 2
ITEM_NUMERATOR_FIELD.index = 1
ITEM_NUMERATOR_FIELD.label = 1
ITEM_NUMERATOR_FIELD.has_default_value = false
ITEM_NUMERATOR_FIELD.default_value = 0
ITEM_NUMERATOR_FIELD.type = 3
ITEM_NUMERATOR_FIELD.cpp_type = 2

ITEM_HAS_FETCHED_FIELD.name = "has_fetched"
ITEM_HAS_FETCHED_FIELD.full_name = ".Item.has_fetched"
ITEM_HAS_FETCHED_FIELD.number = 3
ITEM_HAS_FETCHED_FIELD.index = 2
ITEM_HAS_FETCHED_FIELD.label = 1
ITEM_HAS_FETCHED_FIELD.has_default_value = false
ITEM_HAS_FETCHED_FIELD.default_value = false
ITEM_HAS_FETCHED_FIELD.type = 8
ITEM_HAS_FETCHED_FIELD.cpp_type = 7

ITEM.name = "Item"
ITEM.full_name = ".Item"
ITEM.nested_types = {}
ITEM.enum_types = {}
ITEM.fields = {ITEM_ID_FIELD, ITEM_NUMERATOR_FIELD, ITEM_HAS_FETCHED_FIELD}
ITEM.is_extendable = false
ITEM.extensions = {}

Item = protobuf.Message(ITEM)

