-- Generated By protoc-gen-lua Do not Edit
require "protobuf"
require "Protocol/SantaSuprise_pb"
require "Protocol/Character_pb"
require "Protocol/BacktoJurassic_pb"
require "Protocol/FruitSlice_pb"
require "Protocol/ChefsChoice_pb"
require "Protocol/WildCircus_pb"
require "Protocol/AgentBond_pb"
require "Protocol/LegendsofOlympus_pb"
require "Protocol/ChineseNewYear_pb"
require "Protocol/BruceLee_pb"
require "Protocol/Notice_pb"
require "Protocol/LuxuryLife_pb"
require "Protocol/CashSpin_pb"
require "Protocol/IceAndFire_pb"
require "Protocol/PurrfectPets_pb"
require "Protocol/NewHandAward_pb"
require "Protocol/SummerBeach_pb"
require "Protocol/WorldCup_pb"
require "Protocol/Statistics_pb"
require "Protocol/GameDataBase_pb"
require "Protocol/User_pb"
require "Protocol/Account_pb"
require "Protocol/Client_pb"
require "Protocol/DailyWheel_pb"
require "Protocol/Simple_pb"
require "Protocol/OpenSesame_pb"
require "Protocol/ElvesEpic_pb"
require "Protocol/Pirate_pb"
require "Protocol/AliceinWonderland_pb"
require "Protocol/Record_pb"
require "Protocol/DragonTale_pb"
require "Protocol/WestWorld_pb"
require "Protocol/ForbiddenCity_pb"
require "Protocol/Vampire_pb"
require "Protocol/ClubInfo_pb"
require "Protocol/HalloweenNight_pb"
require "Protocol/PharaohTreasure_pb"
module('DbPlayer_pb', package.seeall)


DBPLAYER = protobuf.Descriptor();
local DBPLAYER_ID_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_EXPIRE_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_VERSION_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_USER_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_ACCOUNT_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_CLIENT_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_CHARACTER_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_PROP_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_TASK_INFO_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_RECORD_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_DAILY_WHEEL_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_FIRST_CHARGE_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_CLUB_INFO_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_GAME_TYPE_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_MEGA_WIN_CHIPS_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_UNLOCK_GAMES_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_CASH_CASINO_CHIPS_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_CASH_CASINO_TIME_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_CASH_CASINO_NUMBER_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_TOTAL_PURE_WIN_CHIP_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_MEGA_WIN_TIME_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_MEGA_WIN_NUMBER_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_UNLOCK_DIAMOND_GAMES_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_UNLOCK_FREE_GAMES_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_NOTICE_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_NEW_HAND_AWARD_FIELD = protobuf.FieldDescriptor();
local DBPLAYER_STATISTICS_FIELD = protobuf.FieldDescriptor();

DBPLAYER_ID_FIELD.name = "id"
DBPLAYER_ID_FIELD.full_name = ".DbPlayer.id"
DBPLAYER_ID_FIELD.number = 1
DBPLAYER_ID_FIELD.index = 0
DBPLAYER_ID_FIELD.label = 1
DBPLAYER_ID_FIELD.has_default_value = false
DBPLAYER_ID_FIELD.default_value = 0
DBPLAYER_ID_FIELD.type = 3
DBPLAYER_ID_FIELD.cpp_type = 2

DBPLAYER_EXPIRE_FIELD.name = "expire"
DBPLAYER_EXPIRE_FIELD.full_name = ".DbPlayer.expire"
DBPLAYER_EXPIRE_FIELD.number = 2
DBPLAYER_EXPIRE_FIELD.index = 1
DBPLAYER_EXPIRE_FIELD.label = 1
DBPLAYER_EXPIRE_FIELD.has_default_value = false
DBPLAYER_EXPIRE_FIELD.default_value = 0
DBPLAYER_EXPIRE_FIELD.type = 3
DBPLAYER_EXPIRE_FIELD.cpp_type = 2

DBPLAYER_VERSION_FIELD.name = "version"
DBPLAYER_VERSION_FIELD.full_name = ".DbPlayer.version"
DBPLAYER_VERSION_FIELD.number = 3
DBPLAYER_VERSION_FIELD.index = 2
DBPLAYER_VERSION_FIELD.label = 1
DBPLAYER_VERSION_FIELD.has_default_value = false
DBPLAYER_VERSION_FIELD.default_value = 0
DBPLAYER_VERSION_FIELD.type = 3
DBPLAYER_VERSION_FIELD.cpp_type = 2

DBPLAYER_USER_FIELD.name = "user"
DBPLAYER_USER_FIELD.full_name = ".DbPlayer.user"
DBPLAYER_USER_FIELD.number = 4
DBPLAYER_USER_FIELD.index = 3
DBPLAYER_USER_FIELD.label = 1
DBPLAYER_USER_FIELD.has_default_value = false
DBPLAYER_USER_FIELD.default_value = nil
DBPLAYER_USER_FIELD.message_type = User_pb.USER
DBPLAYER_USER_FIELD.type = 11
DBPLAYER_USER_FIELD.cpp_type = 10

DBPLAYER_ACCOUNT_FIELD.name = "account"
DBPLAYER_ACCOUNT_FIELD.full_name = ".DbPlayer.account"
DBPLAYER_ACCOUNT_FIELD.number = 5
DBPLAYER_ACCOUNT_FIELD.index = 4
DBPLAYER_ACCOUNT_FIELD.label = 1
DBPLAYER_ACCOUNT_FIELD.has_default_value = false
DBPLAYER_ACCOUNT_FIELD.default_value = nil
DBPLAYER_ACCOUNT_FIELD.message_type = Account_pb.ACCOUNT
DBPLAYER_ACCOUNT_FIELD.type = 11
DBPLAYER_ACCOUNT_FIELD.cpp_type = 10

DBPLAYER_CLIENT_FIELD.name = "client"
DBPLAYER_CLIENT_FIELD.full_name = ".DbPlayer.client"
DBPLAYER_CLIENT_FIELD.number = 6
DBPLAYER_CLIENT_FIELD.index = 5
DBPLAYER_CLIENT_FIELD.label = 1
DBPLAYER_CLIENT_FIELD.has_default_value = false
DBPLAYER_CLIENT_FIELD.default_value = nil
DBPLAYER_CLIENT_FIELD.message_type = Client_pb.CLIENT
DBPLAYER_CLIENT_FIELD.type = 11
DBPLAYER_CLIENT_FIELD.cpp_type = 10

DBPLAYER_CHARACTER_FIELD.name = "character"
DBPLAYER_CHARACTER_FIELD.full_name = ".DbPlayer.character"
DBPLAYER_CHARACTER_FIELD.number = 7
DBPLAYER_CHARACTER_FIELD.index = 6
DBPLAYER_CHARACTER_FIELD.label = 1
DBPLAYER_CHARACTER_FIELD.has_default_value = false
DBPLAYER_CHARACTER_FIELD.default_value = nil
DBPLAYER_CHARACTER_FIELD.message_type = Character_pb.CHARACTER
DBPLAYER_CHARACTER_FIELD.type = 11
DBPLAYER_CHARACTER_FIELD.cpp_type = 10

DBPLAYER_PROP_FIELD.name = "prop"
DBPLAYER_PROP_FIELD.full_name = ".DbPlayer.prop"
DBPLAYER_PROP_FIELD.number = 8
DBPLAYER_PROP_FIELD.index = 7
DBPLAYER_PROP_FIELD.label = 1
DBPLAYER_PROP_FIELD.has_default_value = false
DBPLAYER_PROP_FIELD.default_value = nil
DBPLAYER_PROP_FIELD.message_type = Simple_pb.PROP
DBPLAYER_PROP_FIELD.type = 11
DBPLAYER_PROP_FIELD.cpp_type = 10

DBPLAYER_TASK_INFO_FIELD.name = "task_info"
DBPLAYER_TASK_INFO_FIELD.full_name = ".DbPlayer.task_info"
DBPLAYER_TASK_INFO_FIELD.number = 9
DBPLAYER_TASK_INFO_FIELD.index = 8
DBPLAYER_TASK_INFO_FIELD.label = 1
DBPLAYER_TASK_INFO_FIELD.has_default_value = false
DBPLAYER_TASK_INFO_FIELD.default_value = nil
DBPLAYER_TASK_INFO_FIELD.message_type = Simple_pb.TASKINFO
DBPLAYER_TASK_INFO_FIELD.type = 11
DBPLAYER_TASK_INFO_FIELD.cpp_type = 10

DBPLAYER_RECORD_FIELD.name = "record"
DBPLAYER_RECORD_FIELD.full_name = ".DbPlayer.record"
DBPLAYER_RECORD_FIELD.number = 10
DBPLAYER_RECORD_FIELD.index = 9
DBPLAYER_RECORD_FIELD.label = 1
DBPLAYER_RECORD_FIELD.has_default_value = false
DBPLAYER_RECORD_FIELD.default_value = nil
DBPLAYER_RECORD_FIELD.message_type = Record_pb.RECORD
DBPLAYER_RECORD_FIELD.type = 11
DBPLAYER_RECORD_FIELD.cpp_type = 10

DBPLAYER_DAILY_WHEEL_FIELD.name = "daily_wheel"
DBPLAYER_DAILY_WHEEL_FIELD.full_name = ".DbPlayer.daily_wheel"
DBPLAYER_DAILY_WHEEL_FIELD.number = 11
DBPLAYER_DAILY_WHEEL_FIELD.index = 10
DBPLAYER_DAILY_WHEEL_FIELD.label = 1
DBPLAYER_DAILY_WHEEL_FIELD.has_default_value = false
DBPLAYER_DAILY_WHEEL_FIELD.default_value = nil
DBPLAYER_DAILY_WHEEL_FIELD.message_type = DailyWheel_pb.DAILYWHEEL
DBPLAYER_DAILY_WHEEL_FIELD.type = 11
DBPLAYER_DAILY_WHEEL_FIELD.cpp_type = 10

DBPLAYER_FIRST_CHARGE_FIELD.name = "first_charge"
DBPLAYER_FIRST_CHARGE_FIELD.full_name = ".DbPlayer.first_charge"
DBPLAYER_FIRST_CHARGE_FIELD.number = 12
DBPLAYER_FIRST_CHARGE_FIELD.index = 11
DBPLAYER_FIRST_CHARGE_FIELD.label = 1
DBPLAYER_FIRST_CHARGE_FIELD.has_default_value = false
DBPLAYER_FIRST_CHARGE_FIELD.default_value = nil
DBPLAYER_FIRST_CHARGE_FIELD.message_type = Simple_pb.FIRSTCHARGEINFO
DBPLAYER_FIRST_CHARGE_FIELD.type = 11
DBPLAYER_FIRST_CHARGE_FIELD.cpp_type = 10

DBPLAYER_CLUB_INFO_FIELD.name = "club_info"
DBPLAYER_CLUB_INFO_FIELD.full_name = ".DbPlayer.club_info"
DBPLAYER_CLUB_INFO_FIELD.number = 13
DBPLAYER_CLUB_INFO_FIELD.index = 12
DBPLAYER_CLUB_INFO_FIELD.label = 1
DBPLAYER_CLUB_INFO_FIELD.has_default_value = false
DBPLAYER_CLUB_INFO_FIELD.default_value = nil
DBPLAYER_CLUB_INFO_FIELD.message_type = ClubInfo_pb.CLUBINFO
DBPLAYER_CLUB_INFO_FIELD.type = 11
DBPLAYER_CLUB_INFO_FIELD.cpp_type = 10

DBPLAYER_GAME_TYPE_FIELD.name = "game_type"
DBPLAYER_GAME_TYPE_FIELD.full_name = ".DbPlayer.game_type"
DBPLAYER_GAME_TYPE_FIELD.number = 14
DBPLAYER_GAME_TYPE_FIELD.index = 13
DBPLAYER_GAME_TYPE_FIELD.label = 1
DBPLAYER_GAME_TYPE_FIELD.has_default_value = false
DBPLAYER_GAME_TYPE_FIELD.default_value = 0
DBPLAYER_GAME_TYPE_FIELD.type = 3
DBPLAYER_GAME_TYPE_FIELD.cpp_type = 2

DBPLAYER_MEGA_WIN_CHIPS_FIELD.name = "mega_win_chips"
DBPLAYER_MEGA_WIN_CHIPS_FIELD.full_name = ".DbPlayer.mega_win_chips"
DBPLAYER_MEGA_WIN_CHIPS_FIELD.number = 15
DBPLAYER_MEGA_WIN_CHIPS_FIELD.index = 14
DBPLAYER_MEGA_WIN_CHIPS_FIELD.label = 1
DBPLAYER_MEGA_WIN_CHIPS_FIELD.has_default_value = false
DBPLAYER_MEGA_WIN_CHIPS_FIELD.default_value = ""
DBPLAYER_MEGA_WIN_CHIPS_FIELD.type = 9
DBPLAYER_MEGA_WIN_CHIPS_FIELD.cpp_type = 9

DBPLAYER_UNLOCK_GAMES_FIELD.name = "unlock_games"
DBPLAYER_UNLOCK_GAMES_FIELD.full_name = ".DbPlayer.unlock_games"
DBPLAYER_UNLOCK_GAMES_FIELD.number = 16
DBPLAYER_UNLOCK_GAMES_FIELD.index = 15
DBPLAYER_UNLOCK_GAMES_FIELD.label = 1
DBPLAYER_UNLOCK_GAMES_FIELD.has_default_value = false
DBPLAYER_UNLOCK_GAMES_FIELD.default_value = ""
DBPLAYER_UNLOCK_GAMES_FIELD.type = 9
DBPLAYER_UNLOCK_GAMES_FIELD.cpp_type = 9

DBPLAYER_CASH_CASINO_CHIPS_FIELD.name = "cash_casino_chips"
DBPLAYER_CASH_CASINO_CHIPS_FIELD.full_name = ".DbPlayer.cash_casino_chips"
DBPLAYER_CASH_CASINO_CHIPS_FIELD.number = 17
DBPLAYER_CASH_CASINO_CHIPS_FIELD.index = 16
DBPLAYER_CASH_CASINO_CHIPS_FIELD.label = 1
DBPLAYER_CASH_CASINO_CHIPS_FIELD.has_default_value = false
DBPLAYER_CASH_CASINO_CHIPS_FIELD.default_value = 0
DBPLAYER_CASH_CASINO_CHIPS_FIELD.type = 3
DBPLAYER_CASH_CASINO_CHIPS_FIELD.cpp_type = 2

DBPLAYER_CASH_CASINO_TIME_FIELD.name = "cash_casino_time"
DBPLAYER_CASH_CASINO_TIME_FIELD.full_name = ".DbPlayer.cash_casino_time"
DBPLAYER_CASH_CASINO_TIME_FIELD.number = 18
DBPLAYER_CASH_CASINO_TIME_FIELD.index = 17
DBPLAYER_CASH_CASINO_TIME_FIELD.label = 1
DBPLAYER_CASH_CASINO_TIME_FIELD.has_default_value = false
DBPLAYER_CASH_CASINO_TIME_FIELD.default_value = 0
DBPLAYER_CASH_CASINO_TIME_FIELD.type = 3
DBPLAYER_CASH_CASINO_TIME_FIELD.cpp_type = 2

DBPLAYER_CASH_CASINO_NUMBER_FIELD.name = "cash_casino_number"
DBPLAYER_CASH_CASINO_NUMBER_FIELD.full_name = ".DbPlayer.cash_casino_number"
DBPLAYER_CASH_CASINO_NUMBER_FIELD.number = 19
DBPLAYER_CASH_CASINO_NUMBER_FIELD.index = 18
DBPLAYER_CASH_CASINO_NUMBER_FIELD.label = 1
DBPLAYER_CASH_CASINO_NUMBER_FIELD.has_default_value = false
DBPLAYER_CASH_CASINO_NUMBER_FIELD.default_value = 0
DBPLAYER_CASH_CASINO_NUMBER_FIELD.type = 5
DBPLAYER_CASH_CASINO_NUMBER_FIELD.cpp_type = 1

DBPLAYER_TOTAL_PURE_WIN_CHIP_FIELD.name = "total_pure_win_chip"
DBPLAYER_TOTAL_PURE_WIN_CHIP_FIELD.full_name = ".DbPlayer.total_pure_win_chip"
DBPLAYER_TOTAL_PURE_WIN_CHIP_FIELD.number = 20
DBPLAYER_TOTAL_PURE_WIN_CHIP_FIELD.index = 19
DBPLAYER_TOTAL_PURE_WIN_CHIP_FIELD.label = 1
DBPLAYER_TOTAL_PURE_WIN_CHIP_FIELD.has_default_value = false
DBPLAYER_TOTAL_PURE_WIN_CHIP_FIELD.default_value = 0
DBPLAYER_TOTAL_PURE_WIN_CHIP_FIELD.type = 3
DBPLAYER_TOTAL_PURE_WIN_CHIP_FIELD.cpp_type = 2

DBPLAYER_MEGA_WIN_TIME_FIELD.name = "mega_win_time"
DBPLAYER_MEGA_WIN_TIME_FIELD.full_name = ".DbPlayer.mega_win_time"
DBPLAYER_MEGA_WIN_TIME_FIELD.number = 21
DBPLAYER_MEGA_WIN_TIME_FIELD.index = 20
DBPLAYER_MEGA_WIN_TIME_FIELD.label = 1
DBPLAYER_MEGA_WIN_TIME_FIELD.has_default_value = false
DBPLAYER_MEGA_WIN_TIME_FIELD.default_value = 0
DBPLAYER_MEGA_WIN_TIME_FIELD.type = 3
DBPLAYER_MEGA_WIN_TIME_FIELD.cpp_type = 2

DBPLAYER_MEGA_WIN_NUMBER_FIELD.name = "mega_win_number"
DBPLAYER_MEGA_WIN_NUMBER_FIELD.full_name = ".DbPlayer.mega_win_number"
DBPLAYER_MEGA_WIN_NUMBER_FIELD.number = 22
DBPLAYER_MEGA_WIN_NUMBER_FIELD.index = 21
DBPLAYER_MEGA_WIN_NUMBER_FIELD.label = 1
DBPLAYER_MEGA_WIN_NUMBER_FIELD.has_default_value = false
DBPLAYER_MEGA_WIN_NUMBER_FIELD.default_value = 0
DBPLAYER_MEGA_WIN_NUMBER_FIELD.type = 3
DBPLAYER_MEGA_WIN_NUMBER_FIELD.cpp_type = 2

DBPLAYER_UNLOCK_DIAMOND_GAMES_FIELD.name = "unlock_diamond_games"
DBPLAYER_UNLOCK_DIAMOND_GAMES_FIELD.full_name = ".DbPlayer.unlock_diamond_games"
DBPLAYER_UNLOCK_DIAMOND_GAMES_FIELD.number = 23
DBPLAYER_UNLOCK_DIAMOND_GAMES_FIELD.index = 22
DBPLAYER_UNLOCK_DIAMOND_GAMES_FIELD.label = 1
DBPLAYER_UNLOCK_DIAMOND_GAMES_FIELD.has_default_value = false
DBPLAYER_UNLOCK_DIAMOND_GAMES_FIELD.default_value = ""
DBPLAYER_UNLOCK_DIAMOND_GAMES_FIELD.type = 9
DBPLAYER_UNLOCK_DIAMOND_GAMES_FIELD.cpp_type = 9

DBPLAYER_UNLOCK_FREE_GAMES_FIELD.name = "unlock_free_games"
DBPLAYER_UNLOCK_FREE_GAMES_FIELD.full_name = ".DbPlayer.unlock_free_games"
DBPLAYER_UNLOCK_FREE_GAMES_FIELD.number = 24
DBPLAYER_UNLOCK_FREE_GAMES_FIELD.index = 23
DBPLAYER_UNLOCK_FREE_GAMES_FIELD.label = 1
DBPLAYER_UNLOCK_FREE_GAMES_FIELD.has_default_value = false
DBPLAYER_UNLOCK_FREE_GAMES_FIELD.default_value = ""
DBPLAYER_UNLOCK_FREE_GAMES_FIELD.type = 9
DBPLAYER_UNLOCK_FREE_GAMES_FIELD.cpp_type = 9

DBPLAYER_NOTICE_FIELD.name = "notice"
DBPLAYER_NOTICE_FIELD.full_name = ".DbPlayer.notice"
DBPLAYER_NOTICE_FIELD.number = 25
DBPLAYER_NOTICE_FIELD.index = 24
DBPLAYER_NOTICE_FIELD.label = 1
DBPLAYER_NOTICE_FIELD.has_default_value = false
DBPLAYER_NOTICE_FIELD.default_value = nil
DBPLAYER_NOTICE_FIELD.message_type = Notice_pb.NOTICE
DBPLAYER_NOTICE_FIELD.type = 11
DBPLAYER_NOTICE_FIELD.cpp_type = 10

DBPLAYER_NEW_HAND_AWARD_FIELD.name = "new_hand_award"
DBPLAYER_NEW_HAND_AWARD_FIELD.full_name = ".DbPlayer.new_hand_award"
DBPLAYER_NEW_HAND_AWARD_FIELD.number = 26
DBPLAYER_NEW_HAND_AWARD_FIELD.index = 25
DBPLAYER_NEW_HAND_AWARD_FIELD.label = 1
DBPLAYER_NEW_HAND_AWARD_FIELD.has_default_value = false
DBPLAYER_NEW_HAND_AWARD_FIELD.default_value = nil
DBPLAYER_NEW_HAND_AWARD_FIELD.message_type = NewHandAward_pb.NEWHANDAWARD
DBPLAYER_NEW_HAND_AWARD_FIELD.type = 11
DBPLAYER_NEW_HAND_AWARD_FIELD.cpp_type = 10

DBPLAYER_STATISTICS_FIELD.name = "statistics"
DBPLAYER_STATISTICS_FIELD.full_name = ".DbPlayer.statistics"
DBPLAYER_STATISTICS_FIELD.number = 27
DBPLAYER_STATISTICS_FIELD.index = 26
DBPLAYER_STATISTICS_FIELD.label = 1
DBPLAYER_STATISTICS_FIELD.has_default_value = false
DBPLAYER_STATISTICS_FIELD.default_value = nil
DBPLAYER_STATISTICS_FIELD.message_type = Statistics_pb.STATISTICS
DBPLAYER_STATISTICS_FIELD.type = 11
DBPLAYER_STATISTICS_FIELD.cpp_type = 10

DBPLAYER.name = "DbPlayer"
DBPLAYER.full_name = ".DbPlayer"
DBPLAYER.nested_types = {}
DBPLAYER.enum_types = {}
DBPLAYER.fields = {DBPLAYER_ID_FIELD, DBPLAYER_EXPIRE_FIELD, DBPLAYER_VERSION_FIELD, DBPLAYER_USER_FIELD, DBPLAYER_ACCOUNT_FIELD, DBPLAYER_CLIENT_FIELD, DBPLAYER_CHARACTER_FIELD, DBPLAYER_PROP_FIELD, DBPLAYER_TASK_INFO_FIELD, DBPLAYER_RECORD_FIELD, DBPLAYER_DAILY_WHEEL_FIELD, DBPLAYER_FIRST_CHARGE_FIELD, DBPLAYER_CLUB_INFO_FIELD, DBPLAYER_GAME_TYPE_FIELD, DBPLAYER_MEGA_WIN_CHIPS_FIELD, DBPLAYER_UNLOCK_GAMES_FIELD, DBPLAYER_CASH_CASINO_CHIPS_FIELD, DBPLAYER_CASH_CASINO_TIME_FIELD, DBPLAYER_CASH_CASINO_NUMBER_FIELD, DBPLAYER_TOTAL_PURE_WIN_CHIP_FIELD, DBPLAYER_MEGA_WIN_TIME_FIELD, DBPLAYER_MEGA_WIN_NUMBER_FIELD, DBPLAYER_UNLOCK_DIAMOND_GAMES_FIELD, DBPLAYER_UNLOCK_FREE_GAMES_FIELD, DBPLAYER_NOTICE_FIELD, DBPLAYER_NEW_HAND_AWARD_FIELD, DBPLAYER_STATISTICS_FIELD}
DBPLAYER.is_extendable = false
DBPLAYER.extensions = {}

DbPlayer = protobuf.Message(DBPLAYER)

