-- Generated By protoc-gen-lua Do not Edit
require "protobuf"
module('LoginReward_pb', package.seeall)


MONTHRULE = protobuf.Descriptor();
local MONTHRULE_DAYS_FIELD = protobuf.FieldDescriptor();
local MONTHRULE_GOLD_FIELD = protobuf.FieldDescriptor();
CONTINUOUSRULE = protobuf.Descriptor();
local CONTINUOUSRULE_DAYS_FIELD = protobuf.FieldDescriptor();
local CONTINUOUSRULE_GOLD_FIELD = protobuf.FieldDescriptor();

MONTHRULE_DAYS_FIELD.name = "days"
MONTHRULE_DAYS_FIELD.full_name = ".MonthRule.days"
MONTHRULE_DAYS_FIELD.number = 1
MONTHRULE_DAYS_FIELD.index = 0
MONTHRULE_DAYS_FIELD.label = 1
MONTHRULE_DAYS_FIELD.has_default_value = false
MONTHRULE_DAYS_FIELD.default_value = 0
MONTHRULE_DAYS_FIELD.type = 3
MONTHRULE_DAYS_FIELD.cpp_type = 2

MONTHRULE_GOLD_FIELD.name = "gold"
MONTHRULE_GOLD_FIELD.full_name = ".MonthRule.gold"
MONTHRULE_GOLD_FIELD.number = 2
MONTHRULE_GOLD_FIELD.index = 1
MONTHRULE_GOLD_FIELD.label = 1
MONTHRULE_GOLD_FIELD.has_default_value = false
MONTHRULE_GOLD_FIELD.default_value = 0
MONTHRULE_GOLD_FIELD.type = 3
MONTHRULE_GOLD_FIELD.cpp_type = 2

MONTHRULE.name = "MonthRule"
MONTHRULE.full_name = ".MonthRule"
MONTHRULE.nested_types = {}
MONTHRULE.enum_types = {}
MONTHRULE.fields = {MONTHRULE_DAYS_FIELD, MONTHRULE_GOLD_FIELD}
MONTHRULE.is_extendable = false
MONTHRULE.extensions = {}
CONTINUOUSRULE_DAYS_FIELD.name = "days"
CONTINUOUSRULE_DAYS_FIELD.full_name = ".ContinuousRule.days"
CONTINUOUSRULE_DAYS_FIELD.number = 1
CONTINUOUSRULE_DAYS_FIELD.index = 0
CONTINUOUSRULE_DAYS_FIELD.label = 1
CONTINUOUSRULE_DAYS_FIELD.has_default_value = false
CONTINUOUSRULE_DAYS_FIELD.default_value = 0
CONTINUOUSRULE_DAYS_FIELD.type = 3
CONTINUOUSRULE_DAYS_FIELD.cpp_type = 2

CONTINUOUSRULE_GOLD_FIELD.name = "gold"
CONTINUOUSRULE_GOLD_FIELD.full_name = ".ContinuousRule.gold"
CONTINUOUSRULE_GOLD_FIELD.number = 2
CONTINUOUSRULE_GOLD_FIELD.index = 1
CONTINUOUSRULE_GOLD_FIELD.label = 1
CONTINUOUSRULE_GOLD_FIELD.has_default_value = false
CONTINUOUSRULE_GOLD_FIELD.default_value = 0
CONTINUOUSRULE_GOLD_FIELD.type = 3
CONTINUOUSRULE_GOLD_FIELD.cpp_type = 2

CONTINUOUSRULE.name = "ContinuousRule"
CONTINUOUSRULE.full_name = ".ContinuousRule"
CONTINUOUSRULE.nested_types = {}
CONTINUOUSRULE.enum_types = {}
CONTINUOUSRULE.fields = {CONTINUOUSRULE_DAYS_FIELD, CONTINUOUSRULE_GOLD_FIELD}
CONTINUOUSRULE.is_extendable = false
CONTINUOUSRULE.extensions = {}

ContinuousRule = protobuf.Message(CONTINUOUSRULE)
MonthRule = protobuf.Message(MONTHRULE)

