-- Generated By protoc-gen-lua Do not Edit
require "protobuf"
module('Notice_pb', package.seeall)


NOTICE = protobuf.Descriptor();
local NOTICE_CHECK_LOBBY_BONUS_FIELD = protobuf.FieldDescriptor();

NOTICE_CHECK_LOBBY_BONUS_FIELD.name = "check_lobby_bonus"
NOTICE_CHECK_LOBBY_BONUS_FIELD.full_name = ".Notice.check_lobby_bonus"
NOTICE_CHECK_LOBBY_BONUS_FIELD.number = 1
NOTICE_CHECK_LOBBY_BONUS_FIELD.index = 0
NOTICE_CHECK_LOBBY_BONUS_FIELD.label = 1
NOTICE_CHECK_LOBBY_BONUS_FIELD.has_default_value = false
NOTICE_CHECK_LOBBY_BONUS_FIELD.default_value = 0
NOTICE_CHECK_LOBBY_BONUS_FIELD.type = 3
NOTICE_CHECK_LOBBY_BONUS_FIELD.cpp_type = 2

NOTICE.name = "Notice"
NOTICE.full_name = ".Notice"
NOTICE.nested_types = {}
NOTICE.enum_types = {}
NOTICE.fields = {NOTICE_CHECK_LOBBY_BONUS_FIELD}
NOTICE.is_extendable = false
NOTICE.extensions = {}

Notice = protobuf.Message(NOTICE)

