-- Generated By protoc-gen-lua Do not Edit
require "protobuf"
module('Pirate_pb', package.seeall)


PIRATE = protobuf.Descriptor();
local PIRATE_BET_AMOUNT_FIELD = protobuf.FieldDescriptor();
local PIRATE_FREE_SPIN_BOUTS_FIELD = protobuf.FieldDescriptor();
local PIRATE_FREE_SPIN_NUM_FIELD = protobuf.FieldDescriptor();
local PIRATE_BOUTS_ID_FIELD = protobuf.FieldDescriptor();
local PIRATE_CHANNEL_ID_FIELD = protobuf.FieldDescriptor();
local PIRATE_TOTAL_LOSS_FIELD = protobuf.FieldDescriptor();
local PIRATE_ENTER_CHIP_FIELD = protobuf.FieldDescriptor();
local PIRATE_SPINED_TIMES_FIELD = protobuf.FieldDescriptor();
local PIRATE_FREE_TOTAL_WIN_FIELD = protobuf.FieldDescriptor();
local PIRATE_IS_SLOTS_FIELD = protobuf.FieldDescriptor();
local PIRATE_STEP_NUM_FIELD = protobuf.FieldDescriptor();
local PIRATE_JSON_STR_FIELD = protobuf.FieldDescriptor();

PIRATE_BET_AMOUNT_FIELD.name = "bet_amount"
PIRATE_BET_AMOUNT_FIELD.full_name = ".Pirate.bet_amount"
PIRATE_BET_AMOUNT_FIELD.number = 1
PIRATE_BET_AMOUNT_FIELD.index = 0
PIRATE_BET_AMOUNT_FIELD.label = 1
PIRATE_BET_AMOUNT_FIELD.has_default_value = false
PIRATE_BET_AMOUNT_FIELD.default_value = 0
PIRATE_BET_AMOUNT_FIELD.type = 3
PIRATE_BET_AMOUNT_FIELD.cpp_type = 2

PIRATE_FREE_SPIN_BOUTS_FIELD.name = "free_spin_bouts"
PIRATE_FREE_SPIN_BOUTS_FIELD.full_name = ".Pirate.free_spin_bouts"
PIRATE_FREE_SPIN_BOUTS_FIELD.number = 2
PIRATE_FREE_SPIN_BOUTS_FIELD.index = 1
PIRATE_FREE_SPIN_BOUTS_FIELD.label = 1
PIRATE_FREE_SPIN_BOUTS_FIELD.has_default_value = false
PIRATE_FREE_SPIN_BOUTS_FIELD.default_value = 0
PIRATE_FREE_SPIN_BOUTS_FIELD.type = 3
PIRATE_FREE_SPIN_BOUTS_FIELD.cpp_type = 2

PIRATE_FREE_SPIN_NUM_FIELD.name = "free_spin_num"
PIRATE_FREE_SPIN_NUM_FIELD.full_name = ".Pirate.free_spin_num"
PIRATE_FREE_SPIN_NUM_FIELD.number = 3
PIRATE_FREE_SPIN_NUM_FIELD.index = 2
PIRATE_FREE_SPIN_NUM_FIELD.label = 1
PIRATE_FREE_SPIN_NUM_FIELD.has_default_value = false
PIRATE_FREE_SPIN_NUM_FIELD.default_value = 0
PIRATE_FREE_SPIN_NUM_FIELD.type = 3
PIRATE_FREE_SPIN_NUM_FIELD.cpp_type = 2

PIRATE_BOUTS_ID_FIELD.name = "bouts_id"
PIRATE_BOUTS_ID_FIELD.full_name = ".Pirate.bouts_id"
PIRATE_BOUTS_ID_FIELD.number = 4
PIRATE_BOUTS_ID_FIELD.index = 3
PIRATE_BOUTS_ID_FIELD.label = 1
PIRATE_BOUTS_ID_FIELD.has_default_value = false
PIRATE_BOUTS_ID_FIELD.default_value = 0
PIRATE_BOUTS_ID_FIELD.type = 3
PIRATE_BOUTS_ID_FIELD.cpp_type = 2

PIRATE_CHANNEL_ID_FIELD.name = "channel_id"
PIRATE_CHANNEL_ID_FIELD.full_name = ".Pirate.channel_id"
PIRATE_CHANNEL_ID_FIELD.number = 5
PIRATE_CHANNEL_ID_FIELD.index = 4
PIRATE_CHANNEL_ID_FIELD.label = 1
PIRATE_CHANNEL_ID_FIELD.has_default_value = false
PIRATE_CHANNEL_ID_FIELD.default_value = ""
PIRATE_CHANNEL_ID_FIELD.type = 9
PIRATE_CHANNEL_ID_FIELD.cpp_type = 9

PIRATE_TOTAL_LOSS_FIELD.name = "total_loss"
PIRATE_TOTAL_LOSS_FIELD.full_name = ".Pirate.total_loss"
PIRATE_TOTAL_LOSS_FIELD.number = 6
PIRATE_TOTAL_LOSS_FIELD.index = 5
PIRATE_TOTAL_LOSS_FIELD.label = 1
PIRATE_TOTAL_LOSS_FIELD.has_default_value = false
PIRATE_TOTAL_LOSS_FIELD.default_value = 0
PIRATE_TOTAL_LOSS_FIELD.type = 3
PIRATE_TOTAL_LOSS_FIELD.cpp_type = 2

PIRATE_ENTER_CHIP_FIELD.name = "enter_chip"
PIRATE_ENTER_CHIP_FIELD.full_name = ".Pirate.enter_chip"
PIRATE_ENTER_CHIP_FIELD.number = 7
PIRATE_ENTER_CHIP_FIELD.index = 6
PIRATE_ENTER_CHIP_FIELD.label = 1
PIRATE_ENTER_CHIP_FIELD.has_default_value = false
PIRATE_ENTER_CHIP_FIELD.default_value = 0
PIRATE_ENTER_CHIP_FIELD.type = 3
PIRATE_ENTER_CHIP_FIELD.cpp_type = 2

PIRATE_SPINED_TIMES_FIELD.name = "spined_times"
PIRATE_SPINED_TIMES_FIELD.full_name = ".Pirate.spined_times"
PIRATE_SPINED_TIMES_FIELD.number = 8
PIRATE_SPINED_TIMES_FIELD.index = 7
PIRATE_SPINED_TIMES_FIELD.label = 1
PIRATE_SPINED_TIMES_FIELD.has_default_value = false
PIRATE_SPINED_TIMES_FIELD.default_value = 0
PIRATE_SPINED_TIMES_FIELD.type = 3
PIRATE_SPINED_TIMES_FIELD.cpp_type = 2

PIRATE_FREE_TOTAL_WIN_FIELD.name = "free_total_win"
PIRATE_FREE_TOTAL_WIN_FIELD.full_name = ".Pirate.free_total_win"
PIRATE_FREE_TOTAL_WIN_FIELD.number = 9
PIRATE_FREE_TOTAL_WIN_FIELD.index = 8
PIRATE_FREE_TOTAL_WIN_FIELD.label = 1
PIRATE_FREE_TOTAL_WIN_FIELD.has_default_value = false
PIRATE_FREE_TOTAL_WIN_FIELD.default_value = 0
PIRATE_FREE_TOTAL_WIN_FIELD.type = 3
PIRATE_FREE_TOTAL_WIN_FIELD.cpp_type = 2

PIRATE_IS_SLOTS_FIELD.name = "is_slots"
PIRATE_IS_SLOTS_FIELD.full_name = ".Pirate.is_slots"
PIRATE_IS_SLOTS_FIELD.number = 10
PIRATE_IS_SLOTS_FIELD.index = 9
PIRATE_IS_SLOTS_FIELD.label = 1
PIRATE_IS_SLOTS_FIELD.has_default_value = false
PIRATE_IS_SLOTS_FIELD.default_value = 0
PIRATE_IS_SLOTS_FIELD.type = 3
PIRATE_IS_SLOTS_FIELD.cpp_type = 2

PIRATE_STEP_NUM_FIELD.name = "step_num"
PIRATE_STEP_NUM_FIELD.full_name = ".Pirate.step_num"
PIRATE_STEP_NUM_FIELD.number = 11
PIRATE_STEP_NUM_FIELD.index = 10
PIRATE_STEP_NUM_FIELD.label = 1
PIRATE_STEP_NUM_FIELD.has_default_value = false
PIRATE_STEP_NUM_FIELD.default_value = 0
PIRATE_STEP_NUM_FIELD.type = 3
PIRATE_STEP_NUM_FIELD.cpp_type = 2

PIRATE_JSON_STR_FIELD.name = "json_str"
PIRATE_JSON_STR_FIELD.full_name = ".Pirate.json_str"
PIRATE_JSON_STR_FIELD.number = 12
PIRATE_JSON_STR_FIELD.index = 11
PIRATE_JSON_STR_FIELD.label = 1
PIRATE_JSON_STR_FIELD.has_default_value = false
PIRATE_JSON_STR_FIELD.default_value = ""
PIRATE_JSON_STR_FIELD.type = 9
PIRATE_JSON_STR_FIELD.cpp_type = 9

PIRATE.name = "Pirate"
PIRATE.full_name = ".Pirate"
PIRATE.nested_types = {}
PIRATE.enum_types = {}
PIRATE.fields = {PIRATE_BET_AMOUNT_FIELD, PIRATE_FREE_SPIN_BOUTS_FIELD, PIRATE_FREE_SPIN_NUM_FIELD, PIRATE_BOUTS_ID_FIELD, PIRATE_CHANNEL_ID_FIELD, PIRATE_TOTAL_LOSS_FIELD, PIRATE_ENTER_CHIP_FIELD, PIRATE_SPINED_TIMES_FIELD, PIRATE_FREE_TOTAL_WIN_FIELD, PIRATE_IS_SLOTS_FIELD, PIRATE_STEP_NUM_FIELD, PIRATE_JSON_STR_FIELD}
PIRATE.is_extendable = false
PIRATE.extensions = {}

Pirate = protobuf.Message(PIRATE)

