-- Generated By protoc-gen-lua Do not Edit
require "protobuf"
require "Protocol/SantaSuprise_pb"
require "Protocol/Character_pb"
require "Protocol/BacktoJurassic_pb"
require "Protocol/FruitSlice_pb"
require "Protocol/ChefsChoice_pb"
require "Protocol/WildCircus_pb"
require "Protocol/AgentBond_pb"
require "Protocol/LegendsofOlympus_pb"
require "Protocol/ChineseNewYear_pb"
require "Protocol/BruceLee_pb"
require "Protocol/Notice_pb"
require "Protocol/LuxuryLife_pb"
require "Protocol/CashSpin_pb"
require "Protocol/IceAndFire_pb"
require "Protocol/PurrfectPets_pb"
require "Protocol/NewHandAward_pb"
require "Protocol/SummerBeach_pb"
require "Protocol/WorldCup_pb"
require "Protocol/Statistics_pb"
require "Protocol/GameDataBase_pb"
require "Protocol/User_pb"
require "Protocol/Account_pb"
require "Protocol/Client_pb"
require "Protocol/DailyWheel_pb"
require "Protocol/Simple_pb"
require "Protocol/OpenSesame_pb"
require "Protocol/ElvesEpic_pb"
require "Protocol/Pirate_pb"
require "Protocol/AliceinWonderland_pb"
require "Protocol/Record_pb"
require "Protocol/DragonTale_pb"
require "Protocol/WestWorld_pb"
require "Protocol/ForbiddenCity_pb"
require "Protocol/Vampire_pb"
require "Protocol/ClubInfo_pb"
require "Protocol/HalloweenNight_pb"
require "Protocol/PharaohTreasure_pb"
module('Player_pb', package.seeall)


PLAYER = protobuf.Descriptor();
local PLAYER_ID_FIELD = protobuf.FieldDescriptor();
local PLAYER_EXPIRE_FIELD = protobuf.FieldDescriptor();
local PLAYER_VERSION_FIELD = protobuf.FieldDescriptor();
local PLAYER_USER_FIELD = protobuf.FieldDescriptor();
local PLAYER_ACCOUNT_FIELD = protobuf.FieldDescriptor();
local PLAYER_CLIENT_FIELD = protobuf.FieldDescriptor();
local PLAYER_CHARACTER_FIELD = protobuf.FieldDescriptor();
local PLAYER_PROP_FIELD = protobuf.FieldDescriptor();
local PLAYER_TASK_INFO_FIELD = protobuf.FieldDescriptor();
local PLAYER_RECORD_FIELD = protobuf.FieldDescriptor();
local PLAYER_OPEN_SESAME_FIELD = protobuf.FieldDescriptor();
local PLAYER_DAILY_WHEEL_FIELD = protobuf.FieldDescriptor();
local PLAYER_FIRST_CHARGE_FIELD = protobuf.FieldDescriptor();
local PLAYER_DRAGON_TALE_FIELD = protobuf.FieldDescriptor();
local PLAYER_FORBIDDEN_CITY_FIELD = protobuf.FieldDescriptor();
local PLAYER_VAMPIRE_FIELD = protobuf.FieldDescriptor();
local PLAYER_HALLOWEEN_NIGHT_FIELD = protobuf.FieldDescriptor();
local PLAYER_FRUIT_SLICE_FIELD = protobuf.FieldDescriptor();
local PLAYER_PHARAOH_TREASURE_FIELD = protobuf.FieldDescriptor();
local PLAYER_ELVES_EPIC_FIELD = protobuf.FieldDescriptor();
local PLAYER_ALICEIN_WONDERLAND_FIELD = protobuf.FieldDescriptor();
local PLAYER_PIRATE_FIELD = protobuf.FieldDescriptor();
local PLAYER_GAME_TYPE_FIELD = protobuf.FieldDescriptor();
local PLAYER_MEGA_WIN_CHIPS_FIELD = protobuf.FieldDescriptor();
local PLAYER_SANTA_SUPRISE_FIELD = protobuf.FieldDescriptor();
local PLAYER_UNLOCK_GAMES_FIELD = protobuf.FieldDescriptor();
local PLAYER_BACKTO_JURASSIC_FIELD = protobuf.FieldDescriptor();
local PLAYER_TOTAL_PURE_WIN_CHIP_FIELD = protobuf.FieldDescriptor();
local PLAYER_MEGA_WIN_TIME_FIELD = protobuf.FieldDescriptor();
local PLAYER_MEGA_WIN_NUMBER_FIELD = protobuf.FieldDescriptor();
local PLAYER_CHEFS_CHOICE_FIELD = protobuf.FieldDescriptor();
local PLAYER_WILD_CIRCUS_FIELD = protobuf.FieldDescriptor();
local PLAYER_AGENT_BOND_FIELD = protobuf.FieldDescriptor();
local PLAYER_LEGENDSOF_OLYMPUS_FIELD = protobuf.FieldDescriptor();
local PLAYER_UNLOCK_DIAMOND_GAMES_FIELD = protobuf.FieldDescriptor();
local PLAYER_UNLOCK_FREE_GAMES_FIELD = protobuf.FieldDescriptor();
local PLAYER_CHINESE_NEW_YEAR_FIELD = protobuf.FieldDescriptor();
local PLAYER_BRUCE_LEE_FIELD = protobuf.FieldDescriptor();
local PLAYER_NOTICE_FIELD = protobuf.FieldDescriptor();
local PLAYER_LUXURY_LIFE_FIELD = protobuf.FieldDescriptor();
local PLAYER_CASH_SPIN_FIELD = protobuf.FieldDescriptor();
local PLAYER_ICE_AND_FIRE_FIELD = protobuf.FieldDescriptor();
local PLAYER_PURRFECT_PETS_FIELD = protobuf.FieldDescriptor();
local PLAYER_SUMMER_BEACH_FIELD = protobuf.FieldDescriptor();
local PLAYER_WORLD_CUP_FIELD = protobuf.FieldDescriptor();
local PLAYER_STATISTICS_FIELD = protobuf.FieldDescriptor();
local PLAYER_LEPRECHAUN_TREASURE_FIELD = protobuf.FieldDescriptor();
local PLAYER_ICE_777_FIELD = protobuf.FieldDescriptor();
local PLAYER_MEGA5X_WINS_FIELD = protobuf.FieldDescriptor();
local PLAYER_PRESIDENT_TRUMP_FIELD = protobuf.FieldDescriptor();
local PLAYER_WEST_WORLD_FIELD = protobuf.FieldDescriptor();
local PLAYER_THE_SLOT_FATHER_FIELD = protobuf.FieldDescriptor();
local PLAYER_FROZEN_ERA_FIELD = protobuf.FieldDescriptor();
local PLAYER_LITTLE_RED_FIELD = protobuf.FieldDescriptor();
local PLAYER_PIGGY_JACKPOT_FIELD = protobuf.FieldDescriptor();

PLAYER_ID_FIELD.name = "id"
PLAYER_ID_FIELD.full_name = ".Player.id"
PLAYER_ID_FIELD.number = 1
PLAYER_ID_FIELD.index = 0
PLAYER_ID_FIELD.label = 1
PLAYER_ID_FIELD.has_default_value = false
PLAYER_ID_FIELD.default_value = 0
PLAYER_ID_FIELD.type = 3
PLAYER_ID_FIELD.cpp_type = 2

PLAYER_EXPIRE_FIELD.name = "expire"
PLAYER_EXPIRE_FIELD.full_name = ".Player.expire"
PLAYER_EXPIRE_FIELD.number = 2
PLAYER_EXPIRE_FIELD.index = 1
PLAYER_EXPIRE_FIELD.label = 1
PLAYER_EXPIRE_FIELD.has_default_value = false
PLAYER_EXPIRE_FIELD.default_value = 0
PLAYER_EXPIRE_FIELD.type = 3
PLAYER_EXPIRE_FIELD.cpp_type = 2

PLAYER_VERSION_FIELD.name = "version"
PLAYER_VERSION_FIELD.full_name = ".Player.version"
PLAYER_VERSION_FIELD.number = 3
PLAYER_VERSION_FIELD.index = 2
PLAYER_VERSION_FIELD.label = 1
PLAYER_VERSION_FIELD.has_default_value = false
PLAYER_VERSION_FIELD.default_value = 0
PLAYER_VERSION_FIELD.type = 3
PLAYER_VERSION_FIELD.cpp_type = 2

PLAYER_USER_FIELD.name = "user"
PLAYER_USER_FIELD.full_name = ".Player.user"
PLAYER_USER_FIELD.number = 4
PLAYER_USER_FIELD.index = 3
PLAYER_USER_FIELD.label = 1
PLAYER_USER_FIELD.has_default_value = false
PLAYER_USER_FIELD.default_value = nil
PLAYER_USER_FIELD.message_type = User_pb.USER
PLAYER_USER_FIELD.type = 11
PLAYER_USER_FIELD.cpp_type = 10

PLAYER_ACCOUNT_FIELD.name = "account"
PLAYER_ACCOUNT_FIELD.full_name = ".Player.account"
PLAYER_ACCOUNT_FIELD.number = 5
PLAYER_ACCOUNT_FIELD.index = 4
PLAYER_ACCOUNT_FIELD.label = 1
PLAYER_ACCOUNT_FIELD.has_default_value = false
PLAYER_ACCOUNT_FIELD.default_value = nil
PLAYER_ACCOUNT_FIELD.message_type = Account_pb.ACCOUNT
PLAYER_ACCOUNT_FIELD.type = 11
PLAYER_ACCOUNT_FIELD.cpp_type = 10

PLAYER_CLIENT_FIELD.name = "client"
PLAYER_CLIENT_FIELD.full_name = ".Player.client"
PLAYER_CLIENT_FIELD.number = 6
PLAYER_CLIENT_FIELD.index = 5
PLAYER_CLIENT_FIELD.label = 1
PLAYER_CLIENT_FIELD.has_default_value = false
PLAYER_CLIENT_FIELD.default_value = nil
PLAYER_CLIENT_FIELD.message_type = Client_pb.CLIENT
PLAYER_CLIENT_FIELD.type = 11
PLAYER_CLIENT_FIELD.cpp_type = 10

PLAYER_CHARACTER_FIELD.name = "character"
PLAYER_CHARACTER_FIELD.full_name = ".Player.character"
PLAYER_CHARACTER_FIELD.number = 7
PLAYER_CHARACTER_FIELD.index = 6
PLAYER_CHARACTER_FIELD.label = 1
PLAYER_CHARACTER_FIELD.has_default_value = false
PLAYER_CHARACTER_FIELD.default_value = nil
PLAYER_CHARACTER_FIELD.message_type = Character_pb.CHARACTER
PLAYER_CHARACTER_FIELD.type = 11
PLAYER_CHARACTER_FIELD.cpp_type = 10

PLAYER_PROP_FIELD.name = "prop"
PLAYER_PROP_FIELD.full_name = ".Player.prop"
PLAYER_PROP_FIELD.number = 8
PLAYER_PROP_FIELD.index = 7
PLAYER_PROP_FIELD.label = 1
PLAYER_PROP_FIELD.has_default_value = false
PLAYER_PROP_FIELD.default_value = nil
PLAYER_PROP_FIELD.message_type = Simple_pb.PROP
PLAYER_PROP_FIELD.type = 11
PLAYER_PROP_FIELD.cpp_type = 10

PLAYER_TASK_INFO_FIELD.name = "task_info"
PLAYER_TASK_INFO_FIELD.full_name = ".Player.task_info"
PLAYER_TASK_INFO_FIELD.number = 9
PLAYER_TASK_INFO_FIELD.index = 8
PLAYER_TASK_INFO_FIELD.label = 1
PLAYER_TASK_INFO_FIELD.has_default_value = false
PLAYER_TASK_INFO_FIELD.default_value = nil
PLAYER_TASK_INFO_FIELD.message_type = Simple_pb.TASKINFO
PLAYER_TASK_INFO_FIELD.type = 11
PLAYER_TASK_INFO_FIELD.cpp_type = 10

PLAYER_RECORD_FIELD.name = "record"
PLAYER_RECORD_FIELD.full_name = ".Player.record"
PLAYER_RECORD_FIELD.number = 10
PLAYER_RECORD_FIELD.index = 9
PLAYER_RECORD_FIELD.label = 1
PLAYER_RECORD_FIELD.has_default_value = false
PLAYER_RECORD_FIELD.default_value = nil
PLAYER_RECORD_FIELD.message_type = Record_pb.RECORD
PLAYER_RECORD_FIELD.type = 11
PLAYER_RECORD_FIELD.cpp_type = 10

PLAYER_OPEN_SESAME_FIELD.name = "open_sesame"
PLAYER_OPEN_SESAME_FIELD.full_name = ".Player.open_sesame"
PLAYER_OPEN_SESAME_FIELD.number = 11
PLAYER_OPEN_SESAME_FIELD.index = 10
PLAYER_OPEN_SESAME_FIELD.label = 1
PLAYER_OPEN_SESAME_FIELD.has_default_value = false
PLAYER_OPEN_SESAME_FIELD.default_value = nil
PLAYER_OPEN_SESAME_FIELD.message_type = OpenSesame_pb.OPENSESAME
PLAYER_OPEN_SESAME_FIELD.type = 11
PLAYER_OPEN_SESAME_FIELD.cpp_type = 10

PLAYER_DAILY_WHEEL_FIELD.name = "daily_wheel"
PLAYER_DAILY_WHEEL_FIELD.full_name = ".Player.daily_wheel"
PLAYER_DAILY_WHEEL_FIELD.number = 12
PLAYER_DAILY_WHEEL_FIELD.index = 11
PLAYER_DAILY_WHEEL_FIELD.label = 1
PLAYER_DAILY_WHEEL_FIELD.has_default_value = false
PLAYER_DAILY_WHEEL_FIELD.default_value = nil
PLAYER_DAILY_WHEEL_FIELD.message_type = DailyWheel_pb.DAILYWHEEL
PLAYER_DAILY_WHEEL_FIELD.type = 11
PLAYER_DAILY_WHEEL_FIELD.cpp_type = 10

PLAYER_FIRST_CHARGE_FIELD.name = "first_charge"
PLAYER_FIRST_CHARGE_FIELD.full_name = ".Player.first_charge"
PLAYER_FIRST_CHARGE_FIELD.number = 13
PLAYER_FIRST_CHARGE_FIELD.index = 12
PLAYER_FIRST_CHARGE_FIELD.label = 1
PLAYER_FIRST_CHARGE_FIELD.has_default_value = false
PLAYER_FIRST_CHARGE_FIELD.default_value = nil
PLAYER_FIRST_CHARGE_FIELD.message_type = Simple_pb.FIRSTCHARGEINFO
PLAYER_FIRST_CHARGE_FIELD.type = 11
PLAYER_FIRST_CHARGE_FIELD.cpp_type = 10

PLAYER_DRAGON_TALE_FIELD.name = "dragon_tale"
PLAYER_DRAGON_TALE_FIELD.full_name = ".Player.dragon_tale"
PLAYER_DRAGON_TALE_FIELD.number = 14
PLAYER_DRAGON_TALE_FIELD.index = 13
PLAYER_DRAGON_TALE_FIELD.label = 1
PLAYER_DRAGON_TALE_FIELD.has_default_value = false
PLAYER_DRAGON_TALE_FIELD.default_value = nil
PLAYER_DRAGON_TALE_FIELD.message_type = DragonTale_pb.DRAGONTALE
PLAYER_DRAGON_TALE_FIELD.type = 11
PLAYER_DRAGON_TALE_FIELD.cpp_type = 10

PLAYER_FORBIDDEN_CITY_FIELD.name = "forbidden_city"
PLAYER_FORBIDDEN_CITY_FIELD.full_name = ".Player.forbidden_city"
PLAYER_FORBIDDEN_CITY_FIELD.number = 15
PLAYER_FORBIDDEN_CITY_FIELD.index = 14
PLAYER_FORBIDDEN_CITY_FIELD.label = 1
PLAYER_FORBIDDEN_CITY_FIELD.has_default_value = false
PLAYER_FORBIDDEN_CITY_FIELD.default_value = nil
PLAYER_FORBIDDEN_CITY_FIELD.message_type = ForbiddenCity_pb.FORBIDDENCITY
PLAYER_FORBIDDEN_CITY_FIELD.type = 11
PLAYER_FORBIDDEN_CITY_FIELD.cpp_type = 10

PLAYER_VAMPIRE_FIELD.name = "vampire"
PLAYER_VAMPIRE_FIELD.full_name = ".Player.vampire"
PLAYER_VAMPIRE_FIELD.number = 16
PLAYER_VAMPIRE_FIELD.index = 15
PLAYER_VAMPIRE_FIELD.label = 1
PLAYER_VAMPIRE_FIELD.has_default_value = false
PLAYER_VAMPIRE_FIELD.default_value = nil
PLAYER_VAMPIRE_FIELD.message_type = Vampire_pb.VAMPIRE
PLAYER_VAMPIRE_FIELD.type = 11
PLAYER_VAMPIRE_FIELD.cpp_type = 10

PLAYER_HALLOWEEN_NIGHT_FIELD.name = "halloween_night"
PLAYER_HALLOWEEN_NIGHT_FIELD.full_name = ".Player.halloween_night"
PLAYER_HALLOWEEN_NIGHT_FIELD.number = 18
PLAYER_HALLOWEEN_NIGHT_FIELD.index = 16
PLAYER_HALLOWEEN_NIGHT_FIELD.label = 1
PLAYER_HALLOWEEN_NIGHT_FIELD.has_default_value = false
PLAYER_HALLOWEEN_NIGHT_FIELD.default_value = nil
PLAYER_HALLOWEEN_NIGHT_FIELD.message_type = HalloweenNight_pb.HALLOWEENNIGHT
PLAYER_HALLOWEEN_NIGHT_FIELD.type = 11
PLAYER_HALLOWEEN_NIGHT_FIELD.cpp_type = 10

PLAYER_FRUIT_SLICE_FIELD.name = "fruit_slice"
PLAYER_FRUIT_SLICE_FIELD.full_name = ".Player.fruit_slice"
PLAYER_FRUIT_SLICE_FIELD.number = 19
PLAYER_FRUIT_SLICE_FIELD.index = 17
PLAYER_FRUIT_SLICE_FIELD.label = 1
PLAYER_FRUIT_SLICE_FIELD.has_default_value = false
PLAYER_FRUIT_SLICE_FIELD.default_value = nil
PLAYER_FRUIT_SLICE_FIELD.message_type = FruitSlice_pb.FRUITSLICE
PLAYER_FRUIT_SLICE_FIELD.type = 11
PLAYER_FRUIT_SLICE_FIELD.cpp_type = 10

PLAYER_PHARAOH_TREASURE_FIELD.name = "pharaoh_treasure"
PLAYER_PHARAOH_TREASURE_FIELD.full_name = ".Player.pharaoh_treasure"
PLAYER_PHARAOH_TREASURE_FIELD.number = 20
PLAYER_PHARAOH_TREASURE_FIELD.index = 18
PLAYER_PHARAOH_TREASURE_FIELD.label = 1
PLAYER_PHARAOH_TREASURE_FIELD.has_default_value = false
PLAYER_PHARAOH_TREASURE_FIELD.default_value = nil
PLAYER_PHARAOH_TREASURE_FIELD.message_type = PharaohTreasure_pb.PHARAOHTREASURE
PLAYER_PHARAOH_TREASURE_FIELD.type = 11
PLAYER_PHARAOH_TREASURE_FIELD.cpp_type = 10

PLAYER_ELVES_EPIC_FIELD.name = "elves_epic"
PLAYER_ELVES_EPIC_FIELD.full_name = ".Player.elves_epic"
PLAYER_ELVES_EPIC_FIELD.number = 21
PLAYER_ELVES_EPIC_FIELD.index = 19
PLAYER_ELVES_EPIC_FIELD.label = 1
PLAYER_ELVES_EPIC_FIELD.has_default_value = false
PLAYER_ELVES_EPIC_FIELD.default_value = nil
PLAYER_ELVES_EPIC_FIELD.message_type = ElvesEpic_pb.ELVESEPIC
PLAYER_ELVES_EPIC_FIELD.type = 11
PLAYER_ELVES_EPIC_FIELD.cpp_type = 10

PLAYER_ALICEIN_WONDERLAND_FIELD.name = "alicein_wonderland"
PLAYER_ALICEIN_WONDERLAND_FIELD.full_name = ".Player.alicein_wonderland"
PLAYER_ALICEIN_WONDERLAND_FIELD.number = 22
PLAYER_ALICEIN_WONDERLAND_FIELD.index = 20
PLAYER_ALICEIN_WONDERLAND_FIELD.label = 1
PLAYER_ALICEIN_WONDERLAND_FIELD.has_default_value = false
PLAYER_ALICEIN_WONDERLAND_FIELD.default_value = nil
PLAYER_ALICEIN_WONDERLAND_FIELD.message_type = AliceinWonderland_pb.ALICEINWONDERLAND
PLAYER_ALICEIN_WONDERLAND_FIELD.type = 11
PLAYER_ALICEIN_WONDERLAND_FIELD.cpp_type = 10

PLAYER_PIRATE_FIELD.name = "pirate"
PLAYER_PIRATE_FIELD.full_name = ".Player.pirate"
PLAYER_PIRATE_FIELD.number = 23
PLAYER_PIRATE_FIELD.index = 21
PLAYER_PIRATE_FIELD.label = 1
PLAYER_PIRATE_FIELD.has_default_value = false
PLAYER_PIRATE_FIELD.default_value = nil
PLAYER_PIRATE_FIELD.message_type = Pirate_pb.PIRATE
PLAYER_PIRATE_FIELD.type = 11
PLAYER_PIRATE_FIELD.cpp_type = 10

PLAYER_GAME_TYPE_FIELD.name = "game_type"
PLAYER_GAME_TYPE_FIELD.full_name = ".Player.game_type"
PLAYER_GAME_TYPE_FIELD.number = 24
PLAYER_GAME_TYPE_FIELD.index = 22
PLAYER_GAME_TYPE_FIELD.label = 1
PLAYER_GAME_TYPE_FIELD.has_default_value = false
PLAYER_GAME_TYPE_FIELD.default_value = 0
PLAYER_GAME_TYPE_FIELD.type = 3
PLAYER_GAME_TYPE_FIELD.cpp_type = 2

PLAYER_MEGA_WIN_CHIPS_FIELD.name = "mega_win_chips"
PLAYER_MEGA_WIN_CHIPS_FIELD.full_name = ".Player.mega_win_chips"
PLAYER_MEGA_WIN_CHIPS_FIELD.number = 25
PLAYER_MEGA_WIN_CHIPS_FIELD.index = 23
PLAYER_MEGA_WIN_CHIPS_FIELD.label = 1
PLAYER_MEGA_WIN_CHIPS_FIELD.has_default_value = false
PLAYER_MEGA_WIN_CHIPS_FIELD.default_value = ""
PLAYER_MEGA_WIN_CHIPS_FIELD.type = 9
PLAYER_MEGA_WIN_CHIPS_FIELD.cpp_type = 9

PLAYER_SANTA_SUPRISE_FIELD.name = "santa_suprise"
PLAYER_SANTA_SUPRISE_FIELD.full_name = ".Player.santa_suprise"
PLAYER_SANTA_SUPRISE_FIELD.number = 26
PLAYER_SANTA_SUPRISE_FIELD.index = 24
PLAYER_SANTA_SUPRISE_FIELD.label = 1
PLAYER_SANTA_SUPRISE_FIELD.has_default_value = false
PLAYER_SANTA_SUPRISE_FIELD.default_value = nil
PLAYER_SANTA_SUPRISE_FIELD.message_type = SantaSuprise_pb.SANTASUPRISE
PLAYER_SANTA_SUPRISE_FIELD.type = 11
PLAYER_SANTA_SUPRISE_FIELD.cpp_type = 10

PLAYER_UNLOCK_GAMES_FIELD.name = "unlock_games"
PLAYER_UNLOCK_GAMES_FIELD.full_name = ".Player.unlock_games"
PLAYER_UNLOCK_GAMES_FIELD.number = 27
PLAYER_UNLOCK_GAMES_FIELD.index = 25
PLAYER_UNLOCK_GAMES_FIELD.label = 1
PLAYER_UNLOCK_GAMES_FIELD.has_default_value = false
PLAYER_UNLOCK_GAMES_FIELD.default_value = ""
PLAYER_UNLOCK_GAMES_FIELD.type = 9
PLAYER_UNLOCK_GAMES_FIELD.cpp_type = 9

PLAYER_BACKTO_JURASSIC_FIELD.name = "backto_jurassic"
PLAYER_BACKTO_JURASSIC_FIELD.full_name = ".Player.backto_jurassic"
PLAYER_BACKTO_JURASSIC_FIELD.number = 31
PLAYER_BACKTO_JURASSIC_FIELD.index = 26
PLAYER_BACKTO_JURASSIC_FIELD.label = 1
PLAYER_BACKTO_JURASSIC_FIELD.has_default_value = false
PLAYER_BACKTO_JURASSIC_FIELD.default_value = nil
PLAYER_BACKTO_JURASSIC_FIELD.message_type = BacktoJurassic_pb.BACKTOJURASSIC
PLAYER_BACKTO_JURASSIC_FIELD.type = 11
PLAYER_BACKTO_JURASSIC_FIELD.cpp_type = 10

PLAYER_TOTAL_PURE_WIN_CHIP_FIELD.name = "total_pure_win_chip"
PLAYER_TOTAL_PURE_WIN_CHIP_FIELD.full_name = ".Player.total_pure_win_chip"
PLAYER_TOTAL_PURE_WIN_CHIP_FIELD.number = 32
PLAYER_TOTAL_PURE_WIN_CHIP_FIELD.index = 27
PLAYER_TOTAL_PURE_WIN_CHIP_FIELD.label = 1
PLAYER_TOTAL_PURE_WIN_CHIP_FIELD.has_default_value = false
PLAYER_TOTAL_PURE_WIN_CHIP_FIELD.default_value = 0
PLAYER_TOTAL_PURE_WIN_CHIP_FIELD.type = 3
PLAYER_TOTAL_PURE_WIN_CHIP_FIELD.cpp_type = 2

PLAYER_MEGA_WIN_TIME_FIELD.name = "mega_win_time"
PLAYER_MEGA_WIN_TIME_FIELD.full_name = ".Player.mega_win_time"
PLAYER_MEGA_WIN_TIME_FIELD.number = 33
PLAYER_MEGA_WIN_TIME_FIELD.index = 28
PLAYER_MEGA_WIN_TIME_FIELD.label = 1
PLAYER_MEGA_WIN_TIME_FIELD.has_default_value = false
PLAYER_MEGA_WIN_TIME_FIELD.default_value = 0
PLAYER_MEGA_WIN_TIME_FIELD.type = 3
PLAYER_MEGA_WIN_TIME_FIELD.cpp_type = 2

PLAYER_MEGA_WIN_NUMBER_FIELD.name = "mega_win_number"
PLAYER_MEGA_WIN_NUMBER_FIELD.full_name = ".Player.mega_win_number"
PLAYER_MEGA_WIN_NUMBER_FIELD.number = 34
PLAYER_MEGA_WIN_NUMBER_FIELD.index = 29
PLAYER_MEGA_WIN_NUMBER_FIELD.label = 1
PLAYER_MEGA_WIN_NUMBER_FIELD.has_default_value = false
PLAYER_MEGA_WIN_NUMBER_FIELD.default_value = 0
PLAYER_MEGA_WIN_NUMBER_FIELD.type = 3
PLAYER_MEGA_WIN_NUMBER_FIELD.cpp_type = 2

PLAYER_CHEFS_CHOICE_FIELD.name = "chefs_choice"
PLAYER_CHEFS_CHOICE_FIELD.full_name = ".Player.chefs_choice"
PLAYER_CHEFS_CHOICE_FIELD.number = 35
PLAYER_CHEFS_CHOICE_FIELD.index = 30
PLAYER_CHEFS_CHOICE_FIELD.label = 1
PLAYER_CHEFS_CHOICE_FIELD.has_default_value = false
PLAYER_CHEFS_CHOICE_FIELD.default_value = nil
PLAYER_CHEFS_CHOICE_FIELD.message_type = ChefsChoice_pb.CHEFSCHOICE
PLAYER_CHEFS_CHOICE_FIELD.type = 11
PLAYER_CHEFS_CHOICE_FIELD.cpp_type = 10

PLAYER_WILD_CIRCUS_FIELD.name = "wild_circus"
PLAYER_WILD_CIRCUS_FIELD.full_name = ".Player.wild_circus"
PLAYER_WILD_CIRCUS_FIELD.number = 36
PLAYER_WILD_CIRCUS_FIELD.index = 31
PLAYER_WILD_CIRCUS_FIELD.label = 1
PLAYER_WILD_CIRCUS_FIELD.has_default_value = false
PLAYER_WILD_CIRCUS_FIELD.default_value = nil
PLAYER_WILD_CIRCUS_FIELD.message_type = WildCircus_pb.WILDCIRCUS
PLAYER_WILD_CIRCUS_FIELD.type = 11
PLAYER_WILD_CIRCUS_FIELD.cpp_type = 10

PLAYER_AGENT_BOND_FIELD.name = "agent_bond"
PLAYER_AGENT_BOND_FIELD.full_name = ".Player.agent_bond"
PLAYER_AGENT_BOND_FIELD.number = 37
PLAYER_AGENT_BOND_FIELD.index = 32
PLAYER_AGENT_BOND_FIELD.label = 1
PLAYER_AGENT_BOND_FIELD.has_default_value = false
PLAYER_AGENT_BOND_FIELD.default_value = nil
PLAYER_AGENT_BOND_FIELD.message_type = AgentBond_pb.AGENTBOND
PLAYER_AGENT_BOND_FIELD.type = 11
PLAYER_AGENT_BOND_FIELD.cpp_type = 10

PLAYER_LEGENDSOF_OLYMPUS_FIELD.name = "legendsof_olympus"
PLAYER_LEGENDSOF_OLYMPUS_FIELD.full_name = ".Player.legendsof_olympus"
PLAYER_LEGENDSOF_OLYMPUS_FIELD.number = 38
PLAYER_LEGENDSOF_OLYMPUS_FIELD.index = 33
PLAYER_LEGENDSOF_OLYMPUS_FIELD.label = 1
PLAYER_LEGENDSOF_OLYMPUS_FIELD.has_default_value = false
PLAYER_LEGENDSOF_OLYMPUS_FIELD.default_value = nil
PLAYER_LEGENDSOF_OLYMPUS_FIELD.message_type = LegendsofOlympus_pb.LEGENDSOFOLYMPUS
PLAYER_LEGENDSOF_OLYMPUS_FIELD.type = 11
PLAYER_LEGENDSOF_OLYMPUS_FIELD.cpp_type = 10

PLAYER_UNLOCK_DIAMOND_GAMES_FIELD.name = "unlock_diamond_games"
PLAYER_UNLOCK_DIAMOND_GAMES_FIELD.full_name = ".Player.unlock_diamond_games"
PLAYER_UNLOCK_DIAMOND_GAMES_FIELD.number = 39
PLAYER_UNLOCK_DIAMOND_GAMES_FIELD.index = 34
PLAYER_UNLOCK_DIAMOND_GAMES_FIELD.label = 1
PLAYER_UNLOCK_DIAMOND_GAMES_FIELD.has_default_value = false
PLAYER_UNLOCK_DIAMOND_GAMES_FIELD.default_value = ""
PLAYER_UNLOCK_DIAMOND_GAMES_FIELD.type = 9
PLAYER_UNLOCK_DIAMOND_GAMES_FIELD.cpp_type = 9

PLAYER_UNLOCK_FREE_GAMES_FIELD.name = "unlock_free_games"
PLAYER_UNLOCK_FREE_GAMES_FIELD.full_name = ".Player.unlock_free_games"
PLAYER_UNLOCK_FREE_GAMES_FIELD.number = 40
PLAYER_UNLOCK_FREE_GAMES_FIELD.index = 35
PLAYER_UNLOCK_FREE_GAMES_FIELD.label = 1
PLAYER_UNLOCK_FREE_GAMES_FIELD.has_default_value = false
PLAYER_UNLOCK_FREE_GAMES_FIELD.default_value = ""
PLAYER_UNLOCK_FREE_GAMES_FIELD.type = 9
PLAYER_UNLOCK_FREE_GAMES_FIELD.cpp_type = 9

PLAYER_CHINESE_NEW_YEAR_FIELD.name = "chinese_new_year"
PLAYER_CHINESE_NEW_YEAR_FIELD.full_name = ".Player.chinese_new_year"
PLAYER_CHINESE_NEW_YEAR_FIELD.number = 41
PLAYER_CHINESE_NEW_YEAR_FIELD.index = 36
PLAYER_CHINESE_NEW_YEAR_FIELD.label = 1
PLAYER_CHINESE_NEW_YEAR_FIELD.has_default_value = false
PLAYER_CHINESE_NEW_YEAR_FIELD.default_value = nil
PLAYER_CHINESE_NEW_YEAR_FIELD.message_type = ChineseNewYear_pb.CHINESENEWYEAR
PLAYER_CHINESE_NEW_YEAR_FIELD.type = 11
PLAYER_CHINESE_NEW_YEAR_FIELD.cpp_type = 10

PLAYER_BRUCE_LEE_FIELD.name = "bruce_lee"
PLAYER_BRUCE_LEE_FIELD.full_name = ".Player.bruce_lee"
PLAYER_BRUCE_LEE_FIELD.number = 42
PLAYER_BRUCE_LEE_FIELD.index = 37
PLAYER_BRUCE_LEE_FIELD.label = 1
PLAYER_BRUCE_LEE_FIELD.has_default_value = false
PLAYER_BRUCE_LEE_FIELD.default_value = nil
PLAYER_BRUCE_LEE_FIELD.message_type = BruceLee_pb.BRUCELEE
PLAYER_BRUCE_LEE_FIELD.type = 11
PLAYER_BRUCE_LEE_FIELD.cpp_type = 10

PLAYER_NOTICE_FIELD.name = "notice"
PLAYER_NOTICE_FIELD.full_name = ".Player.notice"
PLAYER_NOTICE_FIELD.number = 43
PLAYER_NOTICE_FIELD.index = 38
PLAYER_NOTICE_FIELD.label = 1
PLAYER_NOTICE_FIELD.has_default_value = false
PLAYER_NOTICE_FIELD.default_value = nil
PLAYER_NOTICE_FIELD.message_type = Notice_pb.NOTICE
PLAYER_NOTICE_FIELD.type = 11
PLAYER_NOTICE_FIELD.cpp_type = 10

PLAYER_LUXURY_LIFE_FIELD.name = "luxury_life"
PLAYER_LUXURY_LIFE_FIELD.full_name = ".Player.luxury_life"
PLAYER_LUXURY_LIFE_FIELD.number = 44
PLAYER_LUXURY_LIFE_FIELD.index = 39
PLAYER_LUXURY_LIFE_FIELD.label = 1
PLAYER_LUXURY_LIFE_FIELD.has_default_value = false
PLAYER_LUXURY_LIFE_FIELD.default_value = nil
PLAYER_LUXURY_LIFE_FIELD.message_type = LuxuryLife_pb.LUXURYLIFE
PLAYER_LUXURY_LIFE_FIELD.type = 11
PLAYER_LUXURY_LIFE_FIELD.cpp_type = 10

PLAYER_CASH_SPIN_FIELD.name = "cash_spin"
PLAYER_CASH_SPIN_FIELD.full_name = ".Player.cash_spin"
PLAYER_CASH_SPIN_FIELD.number = 45
PLAYER_CASH_SPIN_FIELD.index = 40
PLAYER_CASH_SPIN_FIELD.label = 1
PLAYER_CASH_SPIN_FIELD.has_default_value = false
PLAYER_CASH_SPIN_FIELD.default_value = nil
PLAYER_CASH_SPIN_FIELD.message_type = CashSpin_pb.CASHSPIN
PLAYER_CASH_SPIN_FIELD.type = 11
PLAYER_CASH_SPIN_FIELD.cpp_type = 10

PLAYER_ICE_AND_FIRE_FIELD.name = "ice_and_fire"
PLAYER_ICE_AND_FIRE_FIELD.full_name = ".Player.ice_and_fire"
PLAYER_ICE_AND_FIRE_FIELD.number = 46
PLAYER_ICE_AND_FIRE_FIELD.index = 41
PLAYER_ICE_AND_FIRE_FIELD.label = 1
PLAYER_ICE_AND_FIRE_FIELD.has_default_value = false
PLAYER_ICE_AND_FIRE_FIELD.default_value = nil
PLAYER_ICE_AND_FIRE_FIELD.message_type = IceAndFire_pb.ICEANDFIRE
PLAYER_ICE_AND_FIRE_FIELD.type = 11
PLAYER_ICE_AND_FIRE_FIELD.cpp_type = 10

PLAYER_PURRFECT_PETS_FIELD.name = "purrfect_pets"
PLAYER_PURRFECT_PETS_FIELD.full_name = ".Player.purrfect_pets"
PLAYER_PURRFECT_PETS_FIELD.number = 47
PLAYER_PURRFECT_PETS_FIELD.index = 42
PLAYER_PURRFECT_PETS_FIELD.label = 1
PLAYER_PURRFECT_PETS_FIELD.has_default_value = false
PLAYER_PURRFECT_PETS_FIELD.default_value = nil
PLAYER_PURRFECT_PETS_FIELD.message_type = PurrfectPets_pb.PURRFECTPETS
PLAYER_PURRFECT_PETS_FIELD.type = 11
PLAYER_PURRFECT_PETS_FIELD.cpp_type = 10

PLAYER_SUMMER_BEACH_FIELD.name = "summer_beach"
PLAYER_SUMMER_BEACH_FIELD.full_name = ".Player.summer_beach"
PLAYER_SUMMER_BEACH_FIELD.number = 49
PLAYER_SUMMER_BEACH_FIELD.index = 43
PLAYER_SUMMER_BEACH_FIELD.label = 1
PLAYER_SUMMER_BEACH_FIELD.has_default_value = false
PLAYER_SUMMER_BEACH_FIELD.default_value = nil
PLAYER_SUMMER_BEACH_FIELD.message_type = SummerBeach_pb.SUMMERBEACH
PLAYER_SUMMER_BEACH_FIELD.type = 11
PLAYER_SUMMER_BEACH_FIELD.cpp_type = 10

PLAYER_WORLD_CUP_FIELD.name = "world_cup"
PLAYER_WORLD_CUP_FIELD.full_name = ".Player.world_cup"
PLAYER_WORLD_CUP_FIELD.number = 50
PLAYER_WORLD_CUP_FIELD.index = 44
PLAYER_WORLD_CUP_FIELD.label = 1
PLAYER_WORLD_CUP_FIELD.has_default_value = false
PLAYER_WORLD_CUP_FIELD.default_value = nil
PLAYER_WORLD_CUP_FIELD.message_type = WorldCup_pb.WORLDCUP
PLAYER_WORLD_CUP_FIELD.type = 11
PLAYER_WORLD_CUP_FIELD.cpp_type = 10

PLAYER_STATISTICS_FIELD.name = "statistics"
PLAYER_STATISTICS_FIELD.full_name = ".Player.statistics"
PLAYER_STATISTICS_FIELD.number = 51
PLAYER_STATISTICS_FIELD.index = 45
PLAYER_STATISTICS_FIELD.label = 1
PLAYER_STATISTICS_FIELD.has_default_value = false
PLAYER_STATISTICS_FIELD.default_value = nil
PLAYER_STATISTICS_FIELD.message_type = Statistics_pb.STATISTICS
PLAYER_STATISTICS_FIELD.type = 11
PLAYER_STATISTICS_FIELD.cpp_type = 10

PLAYER_LEPRECHAUN_TREASURE_FIELD.name = "leprechaun_treasure"
PLAYER_LEPRECHAUN_TREASURE_FIELD.full_name = ".Player.leprechaun_treasure"
PLAYER_LEPRECHAUN_TREASURE_FIELD.number = 52
PLAYER_LEPRECHAUN_TREASURE_FIELD.index = 46
PLAYER_LEPRECHAUN_TREASURE_FIELD.label = 1
PLAYER_LEPRECHAUN_TREASURE_FIELD.has_default_value = false
PLAYER_LEPRECHAUN_TREASURE_FIELD.default_value = nil
PLAYER_LEPRECHAUN_TREASURE_FIELD.message_type = GameDataBase_pb.GAMEDATABASE
PLAYER_LEPRECHAUN_TREASURE_FIELD.type = 11
PLAYER_LEPRECHAUN_TREASURE_FIELD.cpp_type = 10

PLAYER_ICE_777_FIELD.name = "ice_777"
PLAYER_ICE_777_FIELD.full_name = ".Player.ice_777"
PLAYER_ICE_777_FIELD.number = 53
PLAYER_ICE_777_FIELD.index = 47
PLAYER_ICE_777_FIELD.label = 1
PLAYER_ICE_777_FIELD.has_default_value = false
PLAYER_ICE_777_FIELD.default_value = nil
PLAYER_ICE_777_FIELD.message_type = GameDataBase_pb.GAMEDATABASE
PLAYER_ICE_777_FIELD.type = 11
PLAYER_ICE_777_FIELD.cpp_type = 10

PLAYER_MEGA5X_WINS_FIELD.name = "mega5x_wins"
PLAYER_MEGA5X_WINS_FIELD.full_name = ".Player.mega5x_wins"
PLAYER_MEGA5X_WINS_FIELD.number = 54
PLAYER_MEGA5X_WINS_FIELD.index = 48
PLAYER_MEGA5X_WINS_FIELD.label = 1
PLAYER_MEGA5X_WINS_FIELD.has_default_value = false
PLAYER_MEGA5X_WINS_FIELD.default_value = nil
PLAYER_MEGA5X_WINS_FIELD.message_type = GameDataBase_pb.GAMEDATABASE
PLAYER_MEGA5X_WINS_FIELD.type = 11
PLAYER_MEGA5X_WINS_FIELD.cpp_type = 10

PLAYER_PRESIDENT_TRUMP_FIELD.name = "president_trump"
PLAYER_PRESIDENT_TRUMP_FIELD.full_name = ".Player.president_trump"
PLAYER_PRESIDENT_TRUMP_FIELD.number = 55
PLAYER_PRESIDENT_TRUMP_FIELD.index = 49
PLAYER_PRESIDENT_TRUMP_FIELD.label = 1
PLAYER_PRESIDENT_TRUMP_FIELD.has_default_value = false
PLAYER_PRESIDENT_TRUMP_FIELD.default_value = nil
PLAYER_PRESIDENT_TRUMP_FIELD.message_type = GameDataBase_pb.GAMEDATABASE
PLAYER_PRESIDENT_TRUMP_FIELD.type = 11
PLAYER_PRESIDENT_TRUMP_FIELD.cpp_type = 10

PLAYER_WEST_WORLD_FIELD.name = "west_world"
PLAYER_WEST_WORLD_FIELD.full_name = ".Player.west_world"
PLAYER_WEST_WORLD_FIELD.number = 56
PLAYER_WEST_WORLD_FIELD.index = 50
PLAYER_WEST_WORLD_FIELD.label = 1
PLAYER_WEST_WORLD_FIELD.has_default_value = false
PLAYER_WEST_WORLD_FIELD.default_value = nil
PLAYER_WEST_WORLD_FIELD.message_type = WestWorld_pb.WESTWORLD
PLAYER_WEST_WORLD_FIELD.type = 11
PLAYER_WEST_WORLD_FIELD.cpp_type = 10

PLAYER_THE_SLOT_FATHER_FIELD.name = "the_slot_father"
PLAYER_THE_SLOT_FATHER_FIELD.full_name = ".Player.the_slot_father"
PLAYER_THE_SLOT_FATHER_FIELD.number = 57
PLAYER_THE_SLOT_FATHER_FIELD.index = 51
PLAYER_THE_SLOT_FATHER_FIELD.label = 1
PLAYER_THE_SLOT_FATHER_FIELD.has_default_value = false
PLAYER_THE_SLOT_FATHER_FIELD.default_value = nil
PLAYER_THE_SLOT_FATHER_FIELD.message_type = GameDataBase_pb.GAMEDATABASE
PLAYER_THE_SLOT_FATHER_FIELD.type = 11
PLAYER_THE_SLOT_FATHER_FIELD.cpp_type = 10

PLAYER_FROZEN_ERA_FIELD.name = "frozen_era"
PLAYER_FROZEN_ERA_FIELD.full_name = ".Player.frozen_era"
PLAYER_FROZEN_ERA_FIELD.number = 58
PLAYER_FROZEN_ERA_FIELD.index = 52
PLAYER_FROZEN_ERA_FIELD.label = 1
PLAYER_FROZEN_ERA_FIELD.has_default_value = false
PLAYER_FROZEN_ERA_FIELD.default_value = nil
PLAYER_FROZEN_ERA_FIELD.message_type = GameDataBase_pb.GAMEDATABASE
PLAYER_FROZEN_ERA_FIELD.type = 11
PLAYER_FROZEN_ERA_FIELD.cpp_type = 10

PLAYER_LITTLE_RED_FIELD.name = "little_red"
PLAYER_LITTLE_RED_FIELD.full_name = ".Player.little_red"
PLAYER_LITTLE_RED_FIELD.number = 59
PLAYER_LITTLE_RED_FIELD.index = 53
PLAYER_LITTLE_RED_FIELD.label = 1
PLAYER_LITTLE_RED_FIELD.has_default_value = false
PLAYER_LITTLE_RED_FIELD.default_value = nil
PLAYER_LITTLE_RED_FIELD.message_type = GameDataBase_pb.GAMEDATABASE
PLAYER_LITTLE_RED_FIELD.type = 11
PLAYER_LITTLE_RED_FIELD.cpp_type = 10

PLAYER_PIGGY_JACKPOT_FIELD.name = "piggy_jackpot"
PLAYER_PIGGY_JACKPOT_FIELD.full_name = ".Player.piggy_jackpot"
PLAYER_PIGGY_JACKPOT_FIELD.number = 60
PLAYER_PIGGY_JACKPOT_FIELD.index = 54
PLAYER_PIGGY_JACKPOT_FIELD.label = 1
PLAYER_PIGGY_JACKPOT_FIELD.has_default_value = false
PLAYER_PIGGY_JACKPOT_FIELD.default_value = nil
PLAYER_PIGGY_JACKPOT_FIELD.message_type = GameDataBase_pb.GAMEDATABASE
PLAYER_PIGGY_JACKPOT_FIELD.type = 11
PLAYER_PIGGY_JACKPOT_FIELD.cpp_type = 10

PLAYER.name = "Player"
PLAYER.full_name = ".Player"
PLAYER.nested_types = {}
PLAYER.enum_types = {}
PLAYER.fields = {PLAYER_ID_FIELD, PLAYER_EXPIRE_FIELD, PLAYER_VERSION_FIELD, PLAYER_USER_FIELD, PLAYER_ACCOUNT_FIELD, PLAYER_CLIENT_FIELD, PLAYER_CHARACTER_FIELD, PLAYER_PROP_FIELD, PLAYER_TASK_INFO_FIELD, PLAYER_RECORD_FIELD, PLAYER_OPEN_SESAME_FIELD, PLAYER_DAILY_WHEEL_FIELD, PLAYER_FIRST_CHARGE_FIELD, PLAYER_DRAGON_TALE_FIELD, PLAYER_FORBIDDEN_CITY_FIELD, PLAYER_VAMPIRE_FIELD, PLAYER_HALLOWEEN_NIGHT_FIELD, PLAYER_FRUIT_SLICE_FIELD, PLAYER_PHARAOH_TREASURE_FIELD, PLAYER_ELVES_EPIC_FIELD, PLAYER_ALICEIN_WONDERLAND_FIELD, PLAYER_PIRATE_FIELD, PLAYER_GAME_TYPE_FIELD, PLAYER_MEGA_WIN_CHIPS_FIELD, PLAYER_SANTA_SUPRISE_FIELD, PLAYER_UNLOCK_GAMES_FIELD, PLAYER_BACKTO_JURASSIC_FIELD, PLAYER_TOTAL_PURE_WIN_CHIP_FIELD, PLAYER_MEGA_WIN_TIME_FIELD, PLAYER_MEGA_WIN_NUMBER_FIELD, PLAYER_CHEFS_CHOICE_FIELD, PLAYER_WILD_CIRCUS_FIELD, PLAYER_AGENT_BOND_FIELD, PLAYER_LEGENDSOF_OLYMPUS_FIELD, PLAYER_UNLOCK_DIAMOND_GAMES_FIELD, PLAYER_UNLOCK_FREE_GAMES_FIELD, PLAYER_CHINESE_NEW_YEAR_FIELD, PLAYER_BRUCE_LEE_FIELD, PLAYER_NOTICE_FIELD, PLAYER_LUXURY_LIFE_FIELD, PLAYER_CASH_SPIN_FIELD, PLAYER_ICE_AND_FIRE_FIELD, PLAYER_PURRFECT_PETS_FIELD, PLAYER_SUMMER_BEACH_FIELD, PLAYER_WORLD_CUP_FIELD, PLAYER_STATISTICS_FIELD, PLAYER_LEPRECHAUN_TREASURE_FIELD, PLAYER_ICE_777_FIELD, PLAYER_MEGA5X_WINS_FIELD, PLAYER_PRESIDENT_TRUMP_FIELD, PLAYER_WEST_WORLD_FIELD, PLAYER_THE_SLOT_FATHER_FIELD, PLAYER_FROZEN_ERA_FIELD, PLAYER_LITTLE_RED_FIELD, PLAYER_PIGGY_JACKPOT_FIELD}
PLAYER.is_extendable = false
PLAYER.extensions = {}

Player = protobuf.Message(PLAYER)

