-- Generated By protoc-gen-lua Do not Edit
require "protobuf"
module('PopUp_pb', package.seeall)


BUTTON = protobuf.Descriptor();
local BUTTON_TEXT_FIELD = protobuf.FieldDescriptor();
local BUTTON_COLOR_FIELD = protobuf.FieldDescriptor();
local BUTTON_CALLBACK_FIELD = protobuf.FieldDescriptor();

BUTTON_TEXT_FIELD.name = "text"
BUTTON_TEXT_FIELD.full_name = ".Button.text"
BUTTON_TEXT_FIELD.number = 1
BUTTON_TEXT_FIELD.index = 0
BUTTON_TEXT_FIELD.label = 2
BUTTON_TEXT_FIELD.has_default_value = false
BUTTON_TEXT_FIELD.default_value = ""
BUTTON_TEXT_FIELD.type = 9
BUTTON_TEXT_FIELD.cpp_type = 9

BUTTON_COLOR_FIELD.name = "color"
BUTTON_COLOR_FIELD.full_name = ".Button.color"
BUTTON_COLOR_FIELD.number = 2
BUTTON_COLOR_FIELD.index = 1
BUTTON_COLOR_FIELD.label = 1
BUTTON_COLOR_FIELD.has_default_value = false
BUTTON_COLOR_FIELD.default_value = 0
BUTTON_COLOR_FIELD.type = 3
BUTTON_COLOR_FIELD.cpp_type = 2

BUTTON_CALLBACK_FIELD.name = "callback"
BUTTON_CALLBACK_FIELD.full_name = ".Button.callback"
BUTTON_CALLBACK_FIELD.number = 3
BUTTON_CALLBACK_FIELD.index = 2
BUTTON_CALLBACK_FIELD.label = 2
BUTTON_CALLBACK_FIELD.has_default_value = false
BUTTON_CALLBACK_FIELD.default_value = ""
BUTTON_CALLBACK_FIELD.type = 9
BUTTON_CALLBACK_FIELD.cpp_type = 9

BUTTON.name = "Button"
BUTTON.full_name = ".Button"
BUTTON.nested_types = {}
BUTTON.enum_types = {}
BUTTON.fields = {BUTTON_TEXT_FIELD, BUTTON_COLOR_FIELD, BUTTON_CALLBACK_FIELD}
BUTTON.is_extendable = false
BUTTON.extensions = {}

Button = protobuf.Message(BUTTON)

