-- Generated By protoc-gen-lua Do not Edit
require "protobuf"
module('PresidentTrump_pb', package.seeall)


PRESIDENTTRUMP = protobuf.Descriptor();
local PRESIDENTTRUMP_BET_AMOUNT_FIELD = protobuf.FieldDescriptor();

PRESIDENTTRUMP_BET_AMOUNT_FIELD.name = "bet_amount"
PRESIDENTTRUMP_BET_AMOUNT_FIELD.full_name = ".PresidentTrump.bet_amount"
PRESIDENTTRUMP_BET_AMOUNT_FIELD.number = 1
PRESIDENTTRUMP_BET_AMOUNT_FIELD.index = 0
PRESIDENTTRUMP_BET_AMOUNT_FIELD.label = 1
PRESIDENTTRUMP_BET_AMOUNT_FIELD.has_default_value = false
PRESIDENTTRUMP_BET_AMOUNT_FIELD.default_value = 0
PRESIDENTTRUMP_BET_AMOUNT_FIELD.type = 3
PRESIDENTTRUMP_BET_AMOUNT_FIELD.cpp_type = 2

PRESIDENTTRUMP.name = "PresidentTrump"
PRESIDENTTRUMP.full_name = ".PresidentTrump"
PRESIDENTTRUMP.nested_types = {}
PRESIDENTTRUMP.enum_types = {}
PRESIDENTTRUMP.fields = {PRESIDENTTRUMP_BET_AMOUNT_FIELD}
PRESIDENTTRUMP.is_extendable = false
PRESIDENTTRUMP.extensions = {}

PresidentTrump = protobuf.Message(PRESIDENTTRUMP)

