-- Generated By protoc-gen-lua Do not Edit
require "protobuf"
module('Prop_pb', package.seeall)


ITEM = protobuf.Descriptor();
local ITEM_ID_FIELD = protobuf.FieldDescriptor();
local ITEM_AMOUNT_FIELD = protobuf.FieldDescriptor();

ITEM_ID_FIELD.name = "id"
ITEM_ID_FIELD.full_name = ".Item.id"
ITEM_ID_FIELD.number = 1
ITEM_ID_FIELD.index = 0
ITEM_ID_FIELD.label = 1
ITEM_ID_FIELD.has_default_value = false
ITEM_ID_FIELD.default_value = 0
ITEM_ID_FIELD.type = 3
ITEM_ID_FIELD.cpp_type = 2

ITEM_AMOUNT_FIELD.name = "amount"
ITEM_AMOUNT_FIELD.full_name = ".Item.amount"
ITEM_AMOUNT_FIELD.number = 2
ITEM_AMOUNT_FIELD.index = 1
ITEM_AMOUNT_FIELD.label = 1
ITEM_AMOUNT_FIELD.has_default_value = false
ITEM_AMOUNT_FIELD.default_value = 0
ITEM_AMOUNT_FIELD.type = 3
ITEM_AMOUNT_FIELD.cpp_type = 2

ITEM.name = "Item"
ITEM.full_name = ".Item"
ITEM.nested_types = {}
ITEM.enum_types = {}
ITEM.fields = {ITEM_ID_FIELD, ITEM_AMOUNT_FIELD}
ITEM.is_extendable = false
ITEM.extensions = {}

Item = protobuf.Message(ITEM)

