-- Generated By protoc-gen-lua Do not Edit
require "protobuf"
module('Record_pb', package.seeall)


RECORD = protobuf.Descriptor();
local RECORD_TOTAL_SPIN_FIELD = protobuf.FieldDescriptor();
local RECORD_SPIN_WON_FIELD = protobuf.FieldDescriptor();
local RECORD_TOTAL_WIN_FIELD = protobuf.FieldDescriptor();
local RECORD_BIGGEST_WIN_FIELD = protobuf.FieldDescriptor();
local RECORD_BONUS_GAME_FIELD = protobuf.FieldDescriptor();
local RECORD_FREE_SPIN_FIELD = protobuf.FieldDescriptor();

RECORD_TOTAL_SPIN_FIELD.name = "total_spin"
RECORD_TOTAL_SPIN_FIELD.full_name = ".Record.total_spin"
RECORD_TOTAL_SPIN_FIELD.number = 1
RECORD_TOTAL_SPIN_FIELD.index = 0
RECORD_TOTAL_SPIN_FIELD.label = 1
RECORD_TOTAL_SPIN_FIELD.has_default_value = false
RECORD_TOTAL_SPIN_FIELD.default_value = 0
RECORD_TOTAL_SPIN_FIELD.type = 3
RECORD_TOTAL_SPIN_FIELD.cpp_type = 2

RECORD_SPIN_WON_FIELD.name = "spin_won"
RECORD_SPIN_WON_FIELD.full_name = ".Record.spin_won"
RECORD_SPIN_WON_FIELD.number = 2
RECORD_SPIN_WON_FIELD.index = 1
RECORD_SPIN_WON_FIELD.label = 1
RECORD_SPIN_WON_FIELD.has_default_value = false
RECORD_SPIN_WON_FIELD.default_value = 0
RECORD_SPIN_WON_FIELD.type = 3
RECORD_SPIN_WON_FIELD.cpp_type = 2

RECORD_TOTAL_WIN_FIELD.name = "total_win"
RECORD_TOTAL_WIN_FIELD.full_name = ".Record.total_win"
RECORD_TOTAL_WIN_FIELD.number = 3
RECORD_TOTAL_WIN_FIELD.index = 2
RECORD_TOTAL_WIN_FIELD.label = 1
RECORD_TOTAL_WIN_FIELD.has_default_value = false
RECORD_TOTAL_WIN_FIELD.default_value = 0
RECORD_TOTAL_WIN_FIELD.type = 3
RECORD_TOTAL_WIN_FIELD.cpp_type = 2

RECORD_BIGGEST_WIN_FIELD.name = "biggest_win"
RECORD_BIGGEST_WIN_FIELD.full_name = ".Record.biggest_win"
RECORD_BIGGEST_WIN_FIELD.number = 4
RECORD_BIGGEST_WIN_FIELD.index = 3
RECORD_BIGGEST_WIN_FIELD.label = 1
RECORD_BIGGEST_WIN_FIELD.has_default_value = false
RECORD_BIGGEST_WIN_FIELD.default_value = 0
RECORD_BIGGEST_WIN_FIELD.type = 3
RECORD_BIGGEST_WIN_FIELD.cpp_type = 2

RECORD_BONUS_GAME_FIELD.name = "bonus_game"
RECORD_BONUS_GAME_FIELD.full_name = ".Record.bonus_game"
RECORD_BONUS_GAME_FIELD.number = 5
RECORD_BONUS_GAME_FIELD.index = 4
RECORD_BONUS_GAME_FIELD.label = 1
RECORD_BONUS_GAME_FIELD.has_default_value = false
RECORD_BONUS_GAME_FIELD.default_value = 0
RECORD_BONUS_GAME_FIELD.type = 3
RECORD_BONUS_GAME_FIELD.cpp_type = 2

RECORD_FREE_SPIN_FIELD.name = "free_spin"
RECORD_FREE_SPIN_FIELD.full_name = ".Record.free_spin"
RECORD_FREE_SPIN_FIELD.number = 6
RECORD_FREE_SPIN_FIELD.index = 5
RECORD_FREE_SPIN_FIELD.label = 1
RECORD_FREE_SPIN_FIELD.has_default_value = false
RECORD_FREE_SPIN_FIELD.default_value = 0
RECORD_FREE_SPIN_FIELD.type = 3
RECORD_FREE_SPIN_FIELD.cpp_type = 2

RECORD.name = "Record"
RECORD.full_name = ".Record"
RECORD.nested_types = {}
RECORD.enum_types = {}
RECORD.fields = {RECORD_TOTAL_SPIN_FIELD, RECORD_SPIN_WON_FIELD, RECORD_TOTAL_WIN_FIELD, RECORD_BIGGEST_WIN_FIELD, RECORD_BONUS_GAME_FIELD, RECORD_FREE_SPIN_FIELD}
RECORD.is_extendable = false
RECORD.extensions = {}

Record = protobuf.Message(RECORD)

