-- Generated By protoc-gen-lua Do not Edit
require "protobuf"
module('TheSlotFather_pb', package.seeall)


THESLOTFATHER = protobuf.Descriptor();
local THESLOTFATHER_BET_AMOUNT_FIELD = protobuf.FieldDescriptor();

THESLOTFATHER_BET_AMOUNT_FIELD.name = "bet_amount"
THESLOTFATHER_BET_AMOUNT_FIELD.full_name = ".TheSlotFather.bet_amount"
THESLOTFATHER_BET_AMOUNT_FIELD.number = 1
THESLOTFATHER_BET_AMOUNT_FIELD.index = 0
THESLOTFATHER_BET_AMOUNT_FIELD.label = 1
THESLOTFATHER_BET_AMOUNT_FIELD.has_default_value = false
THESLOTFATHER_BET_AMOUNT_FIELD.default_value = 0
THESLOTFATHER_BET_AMOUNT_FIELD.type = 3
THESLOTFATHER_BET_AMOUNT_FIELD.cpp_type = 2

THESLOTFATHER.name = "TheSlotFather"
THESLOTFATHER.full_name = ".TheSlotFather"
THESLOTFATHER.nested_types = {}
THESLOTFATHER.enum_types = {}
THESLOTFATHER.fields = {THESLOTFATHER_BET_AMOUNT_FIELD}
THESLOTFATHER.is_extendable = false
THESLOTFATHER.extensions = {}

TheSlotFather = protobuf.Message(THESLOTFATHER)

