-- Generated By protoc-gen-lua Do not Edit
require "protobuf"
module('User_pb', package.seeall)


USER = protobuf.Descriptor();
local USER_NICKNAME_FIELD = protobuf.FieldDescriptor();
local USER_SEX_FIELD = protobuf.FieldDescriptor();
local USER_LOCATION_FIELD = protobuf.FieldDescriptor();
local USER_AGE_FIELD = protobuf.FieldDescriptor();
local USER_SIGNATURE_FIELD = protobuf.FieldDescriptor();
local USER_COUNTRY_FIELD = protobuf.FieldDescriptor();
local USER_AVATAR_FIELD = protobuf.FieldDescriptor();

USER_NICKNAME_FIELD.name = "nickname"
USER_NICKNAME_FIELD.full_name = ".User.nickname"
USER_NICKNAME_FIELD.number = 1
USER_NICKNAME_FIELD.index = 0
USER_NICKNAME_FIELD.label = 1
USER_NICKNAME_FIELD.has_default_value = false
USER_NICKNAME_FIELD.default_value = ""
USER_NICKNAME_FIELD.type = 9
USER_NICKNAME_FIELD.cpp_type = 9

USER_SEX_FIELD.name = "sex"
USER_SEX_FIELD.full_name = ".User.sex"
USER_SEX_FIELD.number = 2
USER_SEX_FIELD.index = 1
USER_SEX_FIELD.label = 1
USER_SEX_FIELD.has_default_value = false
USER_SEX_FIELD.default_value = 0
USER_SEX_FIELD.type = 3
USER_SEX_FIELD.cpp_type = 2

USER_LOCATION_FIELD.name = "location"
USER_LOCATION_FIELD.full_name = ".User.location"
USER_LOCATION_FIELD.number = 3
USER_LOCATION_FIELD.index = 2
USER_LOCATION_FIELD.label = 1
USER_LOCATION_FIELD.has_default_value = false
USER_LOCATION_FIELD.default_value = ""
USER_LOCATION_FIELD.type = 9
USER_LOCATION_FIELD.cpp_type = 9

USER_AGE_FIELD.name = "age"
USER_AGE_FIELD.full_name = ".User.age"
USER_AGE_FIELD.number = 4
USER_AGE_FIELD.index = 3
USER_AGE_FIELD.label = 1
USER_AGE_FIELD.has_default_value = false
USER_AGE_FIELD.default_value = 0
USER_AGE_FIELD.type = 3
USER_AGE_FIELD.cpp_type = 2

USER_SIGNATURE_FIELD.name = "signature"
USER_SIGNATURE_FIELD.full_name = ".User.signature"
USER_SIGNATURE_FIELD.number = 5
USER_SIGNATURE_FIELD.index = 4
USER_SIGNATURE_FIELD.label = 1
USER_SIGNATURE_FIELD.has_default_value = false
USER_SIGNATURE_FIELD.default_value = ""
USER_SIGNATURE_FIELD.type = 9
USER_SIGNATURE_FIELD.cpp_type = 9

USER_COUNTRY_FIELD.name = "country"
USER_COUNTRY_FIELD.full_name = ".User.country"
USER_COUNTRY_FIELD.number = 6
USER_COUNTRY_FIELD.index = 5
USER_COUNTRY_FIELD.label = 1
USER_COUNTRY_FIELD.has_default_value = false
USER_COUNTRY_FIELD.default_value = ""
USER_COUNTRY_FIELD.type = 9
USER_COUNTRY_FIELD.cpp_type = 9

USER_AVATAR_FIELD.name = "avatar"
USER_AVATAR_FIELD.full_name = ".User.avatar"
USER_AVATAR_FIELD.number = 7
USER_AVATAR_FIELD.index = 6
USER_AVATAR_FIELD.label = 1
USER_AVATAR_FIELD.has_default_value = false
USER_AVATAR_FIELD.default_value = 0
USER_AVATAR_FIELD.type = 3
USER_AVATAR_FIELD.cpp_type = 2

USER.name = "User"
USER.full_name = ".User"
USER.nested_types = {}
USER.enum_types = {}
USER.fields = {USER_NICKNAME_FIELD, USER_SEX_FIELD, USER_LOCATION_FIELD, USER_AGE_FIELD, USER_SIGNATURE_FIELD, USER_COUNTRY_FIELD, USER_AVATAR_FIELD}
USER.is_extendable = false
USER.extensions = {}

User = protobuf.Message(USER)

