-- Generated By protoc-gen-lua Do not Edit
require "protobuf"
module('Vampire_pb', package.seeall)


VAMPIRE = protobuf.Descriptor();
local VAMPIRE_BET_AMOUNT_FIELD = protobuf.FieldDescriptor();
local VAMPIRE_FREE_SPIN_BOUTS_FIELD = protobuf.FieldDescriptor();
local VAMPIRE_BOUTS_ID_FIELD = protobuf.FieldDescriptor();
local VAMPIRE_CHANNEL_ID_FIELD = protobuf.FieldDescriptor();
local VAMPIRE_TOTAL_LOSS_FIELD = protobuf.FieldDescriptor();
local VAMPIRE_ENTER_CHIP_FIELD = protobuf.FieldDescriptor();
local VAMPIRE_SPINED_TIMES_FIELD = protobuf.FieldDescriptor();
local VAMPIRE_FREE_TOTAL_WIN_FIELD = protobuf.FieldDescriptor();
local VAMPIRE_JSON_STR_FIELD = protobuf.FieldDescriptor();

VAMPIRE_BET_AMOUNT_FIELD.name = "bet_amount"
VAMPIRE_BET_AMOUNT_FIELD.full_name = ".Vampire.bet_amount"
VAMPIRE_BET_AMOUNT_FIELD.number = 1
VAMPIRE_BET_AMOUNT_FIELD.index = 0
VAMPIRE_BET_AMOUNT_FIELD.label = 1
VAMPIRE_BET_AMOUNT_FIELD.has_default_value = false
VAMPIRE_BET_AMOUNT_FIELD.default_value = 0
VAMPIRE_BET_AMOUNT_FIELD.type = 3
VAMPIRE_BET_AMOUNT_FIELD.cpp_type = 2

VAMPIRE_FREE_SPIN_BOUTS_FIELD.name = "free_spin_bouts"
VAMPIRE_FREE_SPIN_BOUTS_FIELD.full_name = ".Vampire.free_spin_bouts"
VAMPIRE_FREE_SPIN_BOUTS_FIELD.number = 2
VAMPIRE_FREE_SPIN_BOUTS_FIELD.index = 1
VAMPIRE_FREE_SPIN_BOUTS_FIELD.label = 1
VAMPIRE_FREE_SPIN_BOUTS_FIELD.has_default_value = false
VAMPIRE_FREE_SPIN_BOUTS_FIELD.default_value = 0
VAMPIRE_FREE_SPIN_BOUTS_FIELD.type = 3
VAMPIRE_FREE_SPIN_BOUTS_FIELD.cpp_type = 2

VAMPIRE_BOUTS_ID_FIELD.name = "bouts_id"
VAMPIRE_BOUTS_ID_FIELD.full_name = ".Vampire.bouts_id"
VAMPIRE_BOUTS_ID_FIELD.number = 3
VAMPIRE_BOUTS_ID_FIELD.index = 2
VAMPIRE_BOUTS_ID_FIELD.label = 1
VAMPIRE_BOUTS_ID_FIELD.has_default_value = false
VAMPIRE_BOUTS_ID_FIELD.default_value = 0
VAMPIRE_BOUTS_ID_FIELD.type = 3
VAMPIRE_BOUTS_ID_FIELD.cpp_type = 2

VAMPIRE_CHANNEL_ID_FIELD.name = "channel_id"
VAMPIRE_CHANNEL_ID_FIELD.full_name = ".Vampire.channel_id"
VAMPIRE_CHANNEL_ID_FIELD.number = 4
VAMPIRE_CHANNEL_ID_FIELD.index = 3
VAMPIRE_CHANNEL_ID_FIELD.label = 1
VAMPIRE_CHANNEL_ID_FIELD.has_default_value = false
VAMPIRE_CHANNEL_ID_FIELD.default_value = ""
VAMPIRE_CHANNEL_ID_FIELD.type = 9
VAMPIRE_CHANNEL_ID_FIELD.cpp_type = 9

VAMPIRE_TOTAL_LOSS_FIELD.name = "total_loss"
VAMPIRE_TOTAL_LOSS_FIELD.full_name = ".Vampire.total_loss"
VAMPIRE_TOTAL_LOSS_FIELD.number = 5
VAMPIRE_TOTAL_LOSS_FIELD.index = 4
VAMPIRE_TOTAL_LOSS_FIELD.label = 1
VAMPIRE_TOTAL_LOSS_FIELD.has_default_value = false
VAMPIRE_TOTAL_LOSS_FIELD.default_value = 0
VAMPIRE_TOTAL_LOSS_FIELD.type = 3
VAMPIRE_TOTAL_LOSS_FIELD.cpp_type = 2

VAMPIRE_ENTER_CHIP_FIELD.name = "enter_chip"
VAMPIRE_ENTER_CHIP_FIELD.full_name = ".Vampire.enter_chip"
VAMPIRE_ENTER_CHIP_FIELD.number = 6
VAMPIRE_ENTER_CHIP_FIELD.index = 5
VAMPIRE_ENTER_CHIP_FIELD.label = 1
VAMPIRE_ENTER_CHIP_FIELD.has_default_value = false
VAMPIRE_ENTER_CHIP_FIELD.default_value = 0
VAMPIRE_ENTER_CHIP_FIELD.type = 3
VAMPIRE_ENTER_CHIP_FIELD.cpp_type = 2

VAMPIRE_SPINED_TIMES_FIELD.name = "spined_times"
VAMPIRE_SPINED_TIMES_FIELD.full_name = ".Vampire.spined_times"
VAMPIRE_SPINED_TIMES_FIELD.number = 7
VAMPIRE_SPINED_TIMES_FIELD.index = 6
VAMPIRE_SPINED_TIMES_FIELD.label = 1
VAMPIRE_SPINED_TIMES_FIELD.has_default_value = false
VAMPIRE_SPINED_TIMES_FIELD.default_value = 0
VAMPIRE_SPINED_TIMES_FIELD.type = 3
VAMPIRE_SPINED_TIMES_FIELD.cpp_type = 2

VAMPIRE_FREE_TOTAL_WIN_FIELD.name = "free_total_win"
VAMPIRE_FREE_TOTAL_WIN_FIELD.full_name = ".Vampire.free_total_win"
VAMPIRE_FREE_TOTAL_WIN_FIELD.number = 8
VAMPIRE_FREE_TOTAL_WIN_FIELD.index = 7
VAMPIRE_FREE_TOTAL_WIN_FIELD.label = 1
VAMPIRE_FREE_TOTAL_WIN_FIELD.has_default_value = false
VAMPIRE_FREE_TOTAL_WIN_FIELD.default_value = 0
VAMPIRE_FREE_TOTAL_WIN_FIELD.type = 3
VAMPIRE_FREE_TOTAL_WIN_FIELD.cpp_type = 2

VAMPIRE_JSON_STR_FIELD.name = "json_str"
VAMPIRE_JSON_STR_FIELD.full_name = ".Vampire.json_str"
VAMPIRE_JSON_STR_FIELD.number = 9
VAMPIRE_JSON_STR_FIELD.index = 8
VAMPIRE_JSON_STR_FIELD.label = 1
VAMPIRE_JSON_STR_FIELD.has_default_value = false
VAMPIRE_JSON_STR_FIELD.default_value = ""
VAMPIRE_JSON_STR_FIELD.type = 9
VAMPIRE_JSON_STR_FIELD.cpp_type = 9

VAMPIRE.name = "Vampire"
VAMPIRE.full_name = ".Vampire"
VAMPIRE.nested_types = {}
VAMPIRE.enum_types = {}
VAMPIRE.fields = {VAMPIRE_BET_AMOUNT_FIELD, VAMPIRE_FREE_SPIN_BOUTS_FIELD, VAMPIRE_BOUTS_ID_FIELD, VAMPIRE_CHANNEL_ID_FIELD, VAMPIRE_TOTAL_LOSS_FIELD, VAMPIRE_ENTER_CHIP_FIELD, VAMPIRE_SPINED_TIMES_FIELD, VAMPIRE_FREE_TOTAL_WIN_FIELD, VAMPIRE_JSON_STR_FIELD}
VAMPIRE.is_extendable = false
VAMPIRE.extensions = {}

Vampire = protobuf.Message(VAMPIRE)

