formal_android_mirror_testaLuckyChristmasMapInfoConfig = {
[1] = { id=1, base_reel_weight_config="LuckyChristmasBaseReelWeight1Config", feature_reel_weight_config="LuckyChristmasFeatureReelWeightConfig", others_config="LuckyChristmasOthers2Config", respin_type="LuckyChristmasRespinType2Config", box_config="LuckyChristmasBox2Config"},
[2] = { id=2, base_reel_weight_config="LuckyChristmasBaseReelWeight2Config", feature_reel_weight_config="LuckyChristmasFeatureReelWeightConfig", others_config="LuckyChristmasOthers3Config", respin_type="LuckyChristmasRespinType1Config", box_config="LuckyChristmasBox1Config"},
[3] = { id=3, base_reel_weight_config="LuckyChristmasBaseReelWeight3Config", feature_reel_weight_config="LuckyChristmasFeatureReelWeightConfig", others_config="LuckyChristmasOthers1Config", respin_type="LuckyChristmasRespinType1Config", box_config="LuckyChristmasBox1Config"},
[4] = { id=4, base_reel_weight_config="LuckyChristmasBaseReelWeightConfig", feature_reel_weight_config="LuckyChristmasFeatureReelWeightConfig", others_config="LuckyChristmasOthers1Config", respin_type="LuckyChristmasRespinType1Config", box_config="LuckyChristmasBox1Config"},
[5] = { id=5, base_reel_weight_config="LuckyChristmasBaseReelWeight4Config", feature_reel_weight_config="LuckyChristmasFeatureReelWeightConfig", others_config="LuckyChristmasOthers4Config", respin_type="LuckyChristmasRespinType2Config", box_config="LuckyChristmasBox2Config"},
[6] = { id=6, base_reel_weight_config="LuckyChristmasBaseReelWeight5Config", feature_reel_weight_config="LuckyChristmasFeatureReelWeightConfig", others_config="LuckyChristmasOthers5Config", respin_type="LuckyChristmasRespinType2Config", box_config="LuckyChristmasBox2Config"},
[7] = { id=7, base_reel_weight_config="LuckyChristmasBaseReelWeight6Config", feature_reel_weight_config="LuckyChristmasFeatureReelWeightConfig", others_config="LuckyChristmasOthers6Config", respin_type="LuckyChristmasRespinType1Config", box_config="LuckyChristmasBox1Config"},
[8] = { id=8, base_reel_weight_config="LuckyChristmasBaseReelWeight7Config", feature_reel_weight_config="LuckyChristmasFeatureReelWeightConfig", others_config="LuckyChristmasOthers6Config", respin_type="LuckyChristmasRespinType1Config", box_config="LuckyChristmasBox1Config"},
}