#ifndef MACRO_H
#define MACRO_H

#ifndef ENUM_POOL_COUNT
#define ENUM_POOL_COUNT 0
#endif

#ifndef ENUM_POOL_TIME
#define ENUM_POOL_TIME 1
#endif

#ifndef STRING_OS_ENV
#define STRING_OS_ENV "PRO_SPEC_T"
#endif

#ifndef STRING_WORK_DIRECTORY
#define STRING_WORK_DIRECTORY "WORK_DIRECTORY"
#endif

#ifndef STRING_ENVIROMENT_VARIABLE
#define STRING_ENVIROMENT_VARIABLE "EVIROMENT_VARIABLE"
#endif

#ifndef STRING_INSTANCE_NAME
#define STRING_INSTANCE_NAME "INSTANCE_NAME"
#endif

#define NUM_MEMORY_STATISTICS_INTERVAL 60
#define LOOP_SERVICE_QUEUE_MAX 65536
#define LOOP_SERVICE_MAX_TIME 30

#define SERVICE_LOGGER_SYSTEM "logger.system"

#endif // !MACRO_H