formal_android_mirror_testaNewWildCircusMapInfoConfig = {
[1] = { id=1, major_trigger_pro=0.001, feature_major_trigger_pro=0.001, base_reel_config="NewWildCircusBaseReelConfig", base_reel_weight_config="NewWildCircusBaseReelWeightConfig", feature_reel_config="NewWildCircusFeatureReelConfig", feature_reel_weight_config="NewWildCircusFeatureReelWeightConfig", major_reel_weight_config="NewWildCircusBaseReelWeightMajorConfig", box_replace_config="NewWildCircusBoxReplaceConfig"},
[2] = { id=2, major_trigger_pro=0, feature_major_trigger_pro=0, base_reel_config="NewWildCircusBaseReelConfig", base_reel_weight_config="NewWildCircusBaseReelWeight2Config", feature_reel_config="NewWildCircusFeatureReelConfig", feature_reel_weight_config="NewWildCircusFeatureReelWeightConfig", major_reel_weight_config="NewWildCircusBaseReelWeightMajorConfig", box_replace_config="NewWildCircusBoxReplaceConfig"},
[3] = { id=3, major_trigger_pro=0.001, feature_major_trigger_pro=0.001, base_reel_config="NewWildCircusBaseReelConfig", base_reel_weight_config="NewWildCircusBaseReelWeight3Config", feature_reel_config="NewWildCircusFeatureReelConfig", feature_reel_weight_config="NewWildCircusFeatureReelWeightConfig", major_reel_weight_config="NewWildCircusBaseReelWeightMajorConfig", box_replace_config="NewWildCircusBoxReplaceConfig"},
[4] = { id=4, major_trigger_pro=0.004, feature_major_trigger_pro=0.004, base_reel_config="NewWildCircusBaseReelConfig", base_reel_weight_config="NewWildCircusBaseReelWeight4Config", feature_reel_config="NewWildCircusFeatureReelConfig", feature_reel_weight_config="NewWildCircusFeatureReelWeightConfig", major_reel_weight_config="NewWildCircusBaseReelWeightMajorConfig", box_replace_config="NewWildCircusBoxReplaceConfig"},
[5] = { id=5, major_trigger_pro=0.0004, feature_major_trigger_pro=0.0004, base_reel_config="NewWildCircusBaseReelConfig", base_reel_weight_config="NewWildCircusBaseReelWeightConfig", feature_reel_config="NewWildCircusFeatureReelConfig", feature_reel_weight_config="NewWildCircusFeatureReelWeightConfig", major_reel_weight_config="NewWildCircusBaseReelWeightMajorConfig", box_replace_config="NewWildCircusBoxReplaceConfig"},
[6] = { id=6, major_trigger_pro=1, feature_major_trigger_pro=0, base_reel_config="NewWildCircusBaseReelConfig", base_reel_weight_config="NewWildCircusBaseReelWeightConfig", feature_reel_config="NewWildCircusFeatureReelConfig", feature_reel_weight_config="NewWildCircusFeatureReelWeightConfig", major_reel_weight_config="NewWildCircusBaseReelWeightMajorConfig", box_replace_config="NewWildCircusBoxReplaceConfig"},
[7] = { id=7, major_trigger_pro=0, feature_major_trigger_pro=0, base_reel_config="NewWildCircusBaseReelConfig", base_reel_weight_config="NewWildCircusBaseReelWeight5Config", feature_reel_config="NewWildCircusFeatureReelConfig", feature_reel_weight_config="NewWildCircusFeatureReelWeightConfig", major_reel_weight_config="NewWildCircusBaseReelWeightMajorConfig", box_replace_config="NewWildCircusBoxReplaceConfig"},
[8] = { id=8, major_trigger_pro=0, feature_major_trigger_pro=0, base_reel_config="NewWildCircusBaseReelConfig", base_reel_weight_config="NewWildCircusBaseReelWeight6Config", feature_reel_config="NewWildCircusFeatureReelConfig", feature_reel_weight_config="NewWildCircusFeatureReelWeightConfig", major_reel_weight_config="NewWildCircusBaseReelWeightMajorConfig", box_replace_config="NewWildCircusBoxReplaceConfig"},
}