OperativeExternConfig = {
[251001] = { global_id=251001, category_id=251, category_alias="创建订单", category_name="CreatePayment", field_id=1, field_alias="玩家ID", field_name="PlayerId", field_value_index=1},
[251002] = { global_id=251002, category_id=251, category_alias="创建订单", category_name="CreatePayment", field_id=2, field_alias="订单金额", field_name="PaymentAmount", field_value_index=2},
[251003] = { global_id=251003, category_id=251, category_alias="创建订单", category_name="CreatePayment", field_id=3, field_alias="外部订单号", field_name="OutOrderId", field_value_index=3},
[251004] = { global_id=251004, category_id=251, category_alias="创建订单", category_name="CreatePayment", field_id=4, field_alias="内部订单号", field_name="PaymentId", field_value_index=4},
[251005] = { global_id=251005, category_id=251, category_alias="创建订单", category_name="CreatePayment", field_id=5, field_alias="商品名称", field_name="GoodsId", field_value_index=5},
[251006] = { global_id=251006, category_id=251, category_alias="创建订单", category_name="CreatePayment", field_id=6, field_alias="支付渠道", field_name="Channel", field_value_index=6},
[252001] = { global_id=252001, category_id=252, category_alias="支付成功", category_name="FinishPayment", field_id=1, field_alias="玩家ID", field_name="PlayerId", field_value_index=1},
[252002] = { global_id=252002, category_id=252, category_alias="支付成功", category_name="FinishPayment", field_id=2, field_alias="订单金额", field_name="PaymentAmount", field_value_index=2},
[252003] = { global_id=252003, category_id=252, category_alias="支付成功", category_name="FinishPayment", field_id=3, field_alias="外部订单号", field_name="OutOrderId", field_value_index=3},
[252004] = { global_id=252004, category_id=252, category_alias="支付成功", category_name="FinishPayment", field_id=4, field_alias="内部订单号", field_name="PaymentId", field_value_index=4},
[252005] = { global_id=252005, category_id=252, category_alias="支付成功", category_name="FinishPayment", field_id=5, field_alias="商品名称", field_name="GoodsId", field_value_index=5},
[252006] = { global_id=252006, category_id=252, category_alias="支付成功", category_name="FinishPayment", field_id=6, field_alias="支付渠道", field_name="Channel", field_value_index=6},
[252007] = { global_id=252007, category_id=252, category_alias="支付成功", category_name="FinishPayment", field_id=7, field_alias="商品中文名称", field_name="GoodsName", field_value_index=7},
[252008] = { global_id=252008, category_id=252, category_alias="支付成功", category_name="FinishPayment", field_id=8, field_alias="是否是沙盒测试", field_name="IsFree", field_value_index=8},
[253001] = { global_id=253001, category_id=253, category_alias="发送邮件", category_name="SendMail", field_id=1, field_alias="玩家ID", field_name="PlayerId", field_value_index=1},
[253002] = { global_id=253002, category_id=253, category_alias="发送邮件", category_name="SendMail", field_id=2, field_alias="邮件ID", field_name="MailId", field_value_index=2},
[253003] = { global_id=253003, category_id=253, category_alias="发送邮件", category_name="SendMail", field_id=3, field_alias="邮件标题", field_name="Title", field_value_index=3},
[253004] = { global_id=253004, category_id=253, category_alias="发送邮件", category_name="SendMail", field_id=4, field_alias="邮件内容", field_name="Content", field_value_index=4},
[253005] = { global_id=253005, category_id=253, category_alias="发送邮件", category_name="SendMail", field_id=5, field_alias="邮件来自", field_name="Sender", field_value_index=5},
[253006] = { global_id=253006, category_id=253, category_alias="发送邮件", category_name="SendMail", field_id=6, field_alias="邮件附件", field_name="Attachment", field_value_index=6},
[254001] = { global_id=254001, category_id=254, category_alias="领取邮件奖励", category_name="GetAttachment", field_id=1, field_alias="玩家ID", field_name="PlayerId", field_value_index=1},
[254002] = { global_id=254002, category_id=254, category_alias="领取邮件奖励", category_name="GetAttachment", field_id=3, field_alias="邮件ID", field_name="MailId", field_value_index=2},
[254003] = { global_id=254003, category_id=254, category_alias="领取邮件奖励", category_name="GetAttachment", field_id=4, field_alias="邮件标题", field_name="Title", field_value_index=3},
[254004] = { global_id=254004, category_id=254, category_alias="领取邮件奖励", category_name="GetAttachment", field_id=5, field_alias="邮件内容", field_name="Content", field_value_index=4},
[254005] = { global_id=254005, category_id=254, category_alias="领取邮件奖励", category_name="GetAttachment", field_id=6, field_alias="邮件来自", field_name="Sender", field_value_index=5},
[254006] = { global_id=254006, category_id=254, category_alias="领取邮件奖励", category_name="GetAttachment", field_id=7, field_alias="邮件附件", field_name="Attachments", field_value_index=6},
[255001] = { global_id=255001, category_id=255, category_alias="绑定facebook", category_name="BindFacebook", field_id=1, field_alias="FacebookID", field_name="FacebookID", field_value_index=1},
[255002] = { global_id=255002, category_id=255, category_alias="绑定facebook", category_name="BindFacebook", field_id=2, field_alias="玩家ID", field_name="PlayerId", field_value_index=2},
[256001] = { global_id=256001, category_id=256, category_alias="解绑facebook", category_name="UnbindFacebook", field_id=1, field_alias="FacebookID", field_name="FacebookID", field_value_index=1},
[256002] = { global_id=256002, category_id=256, category_alias="解绑facebook", category_name="UnbindFacebook", field_id=2, field_alias="玩家ID", field_name="PlayerId", field_value_index=2},
[257001] = { global_id=257001, category_id=257, category_alias="替换facebook", category_name="ReplaceFacebook", field_id=1, field_alias="替换玩家ID", field_name="ReplacePlayId", field_value_index=1},
[257002] = { global_id=257002, category_id=257, category_alias="替换facebook", category_name="ReplaceFacebook", field_id=2, field_alias="被替换玩家ID", field_name="ReplacedPlayId", field_value_index=2},
[257003] = { global_id=257003, category_id=257, category_alias="替换facebook", category_name="ReplaceFacebook", field_id=3, field_alias="替换玩家替换前FacebookID", field_name="ReplacePlayerFacebookIDBefore", field_value_index=3},
[257004] = { global_id=257004, category_id=257, category_alias="替换facebook", category_name="ReplaceFacebook", field_id=4, field_alias="替换玩家替换后FacebookID", field_name="ReplacePlayerFacebookIDAfter", field_value_index=4},
[257005] = { global_id=257005, category_id=257, category_alias="替换facebook", category_name="ReplaceFacebook", field_id=5, field_alias="被替换玩家替换前FacebookID", field_name="ReplacedPlayerFacebookIDBefore", field_value_index=5},
[257006] = { global_id=257006, category_id=257, category_alias="替换facebook", category_name="ReplaceFacebook", field_id=6, field_alias="被替换玩家替换后FacebookID", field_name="ReplacedPlayerFacebookIDAfter", field_value_index=6},
[258001] = { global_id=258001, category_id=258, category_alias="load facebook", category_name="LoadFacebook", field_id=1, field_alias="load玩家ID", field_name="LoadPlayId", field_value_index=1},
[258002] = { global_id=258002, category_id=258, category_alias="load facebook", category_name="LoadFacebook", field_id=2, field_alias="被load玩家ID", field_name="LoadedPlayId", field_value_index=2},
[258003] = { global_id=258003, category_id=258, category_alias="load facebook", category_name="LoadFacebook", field_id=3, field_alias="load玩家load前FacebookID", field_name="LoadPlayerFacebookIDBefore", field_value_index=3},
[258004] = { global_id=258004, category_id=258, category_alias="load facebook", category_name="LoadFacebook", field_id=4, field_alias="load玩家load后FacebookID", field_name="LoadPlayerFacebookIDAfter", field_value_index=4},
[258005] = { global_id=258005, category_id=258, category_alias="load facebook", category_name="LoadFacebook", field_id=5, field_alias="被load玩家load前FacebookID", field_name="LoadedPlayerFacebookIDBefore", field_value_index=5},
[258006] = { global_id=258006, category_id=258, category_alias="load facebook", category_name="LoadFacebook", field_id=6, field_alias="被load玩家load后FacebookID", field_name="LoadedPlayerFacebookIDAfter", field_value_index=6},
[259001] = { global_id=259001, category_id=259, category_alias="绑定googleplay", category_name="BindGooglePlay", field_id=1, field_alias="GooglePlayID", field_name="GooglePlayID", field_value_index=1},
[259002] = { global_id=259002, category_id=259, category_alias="绑定googleplay", category_name="BindGooglePlay", field_id=2, field_alias="玩家ID", field_name="PlayerId", field_value_index=2},
[260001] = { global_id=260001, category_id=260, category_alias="解绑googleplay", category_name="UnbindGooglePlay", field_id=1, field_alias="GooglePlayID", field_name="GooglePlayID", field_value_index=1},
[260002] = { global_id=260002, category_id=260, category_alias="解绑googleplay", category_name="UnbindGooglePlay", field_id=2, field_alias="玩家ID", field_name="PlayerId", field_value_index=2},
[261001] = { global_id=261001, category_id=261, category_alias="替换googleplay", category_name="ReplaceGooglePlay", field_id=1, field_alias="替换玩家ID", field_name="ReplacePlayId", field_value_index=1},
[261002] = { global_id=261002, category_id=261, category_alias="替换googleplay", category_name="ReplaceGooglePlay", field_id=2, field_alias="被替换玩家ID", field_name="ReplacedPlayId", field_value_index=2},
[261003] = { global_id=261003, category_id=261, category_alias="替换googleplay", category_name="ReplaceGooglePlay", field_id=3, field_alias="替换玩家替换前GooglePlayID", field_name="ReplacePlayerGooglePlayIDBefore", field_value_index=3},
[261004] = { global_id=261004, category_id=261, category_alias="替换googleplay", category_name="ReplaceGooglePlay", field_id=4, field_alias="替换玩家替换后GooglePlayID", field_name="ReplacePlayerGooglePlayIDAfter", field_value_index=4},
[261005] = { global_id=261005, category_id=261, category_alias="替换googleplay", category_name="ReplaceGooglePlay", field_id=5, field_alias="被替换玩家替换前GooglePlayID", field_name="ReplacedPlayerGooglePlayIDBefore", field_value_index=5},
[261006] = { global_id=261006, category_id=261, category_alias="替换googleplay", category_name="ReplaceGooglePlay", field_id=6, field_alias="被替换玩家替换后GooglePlayID", field_name="ReplacedPlayerGooglePlayIDAfter", field_value_index=6},
[262001] = { global_id=262001, category_id=262, category_alias="load googleplay", category_name="LoadGooglePlay", field_id=1, field_alias="load玩家ID", field_name="LoadPlayId", field_value_index=1},
[262002] = { global_id=262002, category_id=262, category_alias="load googleplay", category_name="LoadGooglePlay", field_id=2, field_alias="被load玩家ID", field_name="LoadedPlayId", field_value_index=2},
[262003] = { global_id=262003, category_id=262, category_alias="load googleplay", category_name="LoadGooglePlay", field_id=3, field_alias="load玩家load前GooglePlayID", field_name="LoadPlayerGooglePlayIDBefore", field_value_index=3},
[262004] = { global_id=262004, category_id=262, category_alias="load googleplay", category_name="LoadGooglePlay", field_id=4, field_alias="load玩家load后GooglePlayID", field_name="LoadPlayerGooglePlayIDAfter", field_value_index=4},
[262005] = { global_id=262005, category_id=262, category_alias="load googleplay", category_name="LoadGooglePlay", field_id=5, field_alias="被load玩家load前GooglePlayID", field_name="LoadedPlayerGooglePlayIDBefore", field_value_index=5},
[262006] = { global_id=262006, category_id=262, category_alias="load googleplay", category_name="LoadGooglePlay", field_id=6, field_alias="被load玩家load后GooglePlayID", field_name="LoadedPlayerGooglePlayIDAfter", field_value_index=6},
[263001] = { global_id=263001, category_id=263, category_alias="点赞", category_name="Like", field_id=1, field_alias="点赞玩家ID", field_name="LikePlayerId", field_value_index=1},
[263002] = { global_id=263002, category_id=263, category_alias="点赞", category_name="Like", field_id=2, field_alias="被点赞玩家ID", field_name="LikedPlayerId", field_value_index=2},
[264001] = { global_id=264001, category_id=264, category_alias="准备创建订单", category_name="BeginCreatePayment", field_id=1, field_alias="玩家ID", field_name="PlayerId", field_value_index=1},
[264002] = { global_id=264002, category_id=264, category_alias="准备创建订单", category_name="BeginCreatePayment", field_id=2, field_alias="产品ID", field_name="ProductId", field_value_index=2},
[264003] = { global_id=264003, category_id=264, category_alias="准备创建订单", category_name="BeginCreatePayment", field_id=3, field_alias="订单ID", field_name="OrderId", field_value_index=3},
[264004] = { global_id=264004, category_id=264, category_alias="准备创建订单", category_name="BeginCreatePayment", field_id=4, field_alias="支付渠道", field_name="Channel", field_value_index=4},
[265001] = { global_id=265001, category_id=265, category_alias="错误订单", category_name="ErrorPayment", field_id=1, field_alias="玩家ID", field_name="PlayerId", field_value_index=1},
[265002] = { global_id=265002, category_id=265, category_alias="错误订单", category_name="ErrorPayment", field_id=2, field_alias="订单金额", field_name="PaymentAmount", field_value_index=2},
[265003] = { global_id=265003, category_id=265, category_alias="错误订单", category_name="ErrorPayment", field_id=3, field_alias="外部订单号", field_name="OutOrderId", field_value_index=3},
[265004] = { global_id=265004, category_id=265, category_alias="错误订单", category_name="ErrorPayment", field_id=4, field_alias="失效时间", field_name="ExpiresDate", field_value_index=4},
[265005] = { global_id=265005, category_id=265, category_alias="错误订单", category_name="ErrorPayment", field_id=5, field_alias="商品名称", field_name="GoodsId", field_value_index=5},
[265006] = { global_id=265006, category_id=265, category_alias="错误订单", category_name="ErrorPayment", field_id=6, field_alias="支付渠道", field_name="Channel", field_value_index=6},
}