QuestFeverMissionTypeConfig = {
[1] = { id=1, mission_type="在Base Game中下注%d次", mission_text="Bet %s Times in Base Game", parameter_count=1, icon_id=1},
[2] = { id=2, mission_type="在Base Game中赢%d次", mission_text="Win %s Times in Base Game", parameter_count=1, icon_id=1},
[3] = { id=3, mission_type="赢%d金币", mission_text="Win %s Coins in Total", parameter_count=1, icon_id=2},
[4] = { id=4, mission_type="进入%d次Free Spin", mission_text="Hit Free Spin %s Time", parameter_count=1, icon_id=3},
[5] = { id=5, mission_type="在Free Spin中赢%d金币", mission_text="Win %s Coins in Free Spins", parameter_count=1, icon_id=2},
[6] = { id=6, mission_type="进入%d次Hold and Spin（TIKI ISLAND）", mission_text="Hit Hold and Spin %s Time", parameter_count=1, icon_id=3},
[7] = { id=7, mission_type="在Hold and Spin中赢%d金币（TIKI ISLAND）", mission_text="Win %s Coins in Hold and Spin", parameter_count=1, icon_id=2},
[8] = { id=8, mission_type="进入%d次Lightning Respin（Thunder Zeus）", mission_text="Hit Lightning Respin %s Time", parameter_count=1, icon_id=3},
[9] = { id=9, mission_type="在Lightning Respin中赢%d金币（Thunder Zeus）", mission_text="Win %s Coins in Lightning Respin", parameter_count=1, icon_id=2},
[10] = { id=10, mission_type="进入%d次Dynamite Respin（Gold Mine）", mission_text="Hit Dynamite Respin %s Time", parameter_count=1, icon_id=3},
[11] = { id=11, mission_type="在Dynamite Respin中赢%d金币（Gold Mine）", mission_text="Win %s Coins in Dynamite Respin", parameter_count=1, icon_id=2},
[12] = { id=12, mission_type="进入%d次Coins Respin（New Purrfect Pets）", mission_text="Hit Coins Respin %s Time", parameter_count=1, icon_id=3},
[13] = { id=13, mission_type="在Coins Respin中赢%d金币（New Purrfect Pets）", mission_text="Win %s Coins in Coins Respin", parameter_count=1, icon_id=2},
[14] = { id=14, mission_type="进入%d次小游戏（New Leprechaun Treasure，New Legends of Olympus，Dancing Drums，Alice in Wonderland，Lucky Christmas，Honey Fortune）", mission_text="Hit Bonus Game %s Time", parameter_count=1, icon_id=3},
[15] = { id=15, mission_type="在小游戏中赢%d金币（New Leprechaun Treasure，New Legends of Olympus，Dancing Drums，Alice in Wonderland，New Purrfect Pets,Lucky Christmas）", mission_text="Win %s Coins in Bonus Game", parameter_count=1, icon_id=2},
[16] = { id=16, mission_type="中Rapid Hit特性%d次（Rapid Hit Jackpot）", mission_text="Hit Rapid Hit %s Time", parameter_count=1, icon_id=3},
[17] = { id=17, mission_type="中Mini Classic特性%d次（Rapid Hit Jackpot）", mission_text="Hit Mini Classic Feature %s Time", parameter_count=1, icon_id=3},
[18] = { id=18, mission_type="在地图上前进%d次（Piggy Jackpot）", mission_text="Get %s step forward in the Map", parameter_count=1, icon_id=3},
[19] = { id=19, mission_type="进入%d次Frozen Respin（Frozen Era）", mission_text="Hit Frozen Respin %s Time", parameter_count=1, icon_id=3},
[20] = { id=20, mission_type="在Frozen Respin中赢%d金币（Frozen Era）", mission_text="Win %s Coins in Coins Respin", parameter_count=1, icon_id=2},
[21] = { id=21, mission_type="中%d次Minor Jackpot（New Wild Circus）", mission_text="Hit Minor Jackpot %s Time", parameter_count=1, icon_id=3},
[22] = { id=22, mission_type="进入%d次Cash Rain Feature（Cash Rain）", mission_text="Hit Cash Rain Feature %s Time", parameter_count=1, icon_id=3},
[23] = { id=23, mission_type="在Cash Rain Feature中赢%d金币（Cash Rain）", mission_text="Win %s Coins in Cash Rain Feature", parameter_count=1, icon_id=2},
[24] = { id=24, mission_type="进入%s次Star Link Respin（Lucky Christmas）", mission_text="Hit Star Link Respin %s Time", parameter_count=1, icon_id=3},
[25] = { id=25, mission_type="在Star Link Respin中%d金币(Lucky Christmas)", mission_text="Win %s Coins in Star Link Respin", parameter_count=1, icon_id=2},
}