formal_android_mirror_testaDancingDrumsMapInfoConfig = {
[1] = { id=1, base_reel_config="DancingDrumsBaseReelConfig", base_reel_weight_config="DancingDrumsBaseReelWeightConfig", feature_reel_config="DancingDrumsFeatureReelConfig", feature_reel_weight_config="DancingDrumsFeatureReelWeightConfig", Jackpot_config="DancingDrumsJackpotConfig"},
[2] = { id=2, base_reel_config="DancingDrumsBaseReelConfig", base_reel_weight_config="DancingDrumsBaseReelWeightLucky1Config", feature_reel_config="DancingDrumsFeatureReelConfig", feature_reel_weight_config="DancingDrumsFeatureReelWeightLucky1Config", Jackpot_config="DancingDrumsJackpotLucky1Config"},
[3] = { id=3, base_reel_config="DancingDrumsBaseReelConfig", base_reel_weight_config="DancingDrumsBaseReelWeightLucky2Config", feature_reel_config="DancingDrumsFeatureReelConfig", feature_reel_weight_config="DancingDrumsFeatureReelWeightLucky2Config", Jackpot_config="DancingDrumsJackpotLucky2Config"},
[4] = { id=4, base_reel_config="DancingDrumsBaseReelConfig", base_reel_weight_config="DancingDrumsBaseReelWeightLucky3Config", feature_reel_config="DancingDrumsFeatureReelConfig", feature_reel_weight_config="DancingDrumsFeatureReelWeightLucky3Config", Jackpot_config="DancingDrumsJackpotLucky3Config"},
[5] = { id=5, base_reel_config="DancingDrumsBaseReelConfig", base_reel_weight_config="DancingDrumsBaseReelWeightUnlucky1Config", feature_reel_config="DancingDrumsFeatureReelConfig", feature_reel_weight_config="DancingDrumsFeatureReelWeightUnlucky1Config", Jackpot_config="DancingDrumsJackpotUnlucky1Config"},
[6] = { id=6, base_reel_config="DancingDrumsBaseReelConfig", base_reel_weight_config="DancingDrumsBaseReelWeightUnlucky2Config", feature_reel_config="DancingDrumsFeatureReelConfig", feature_reel_weight_config="DancingDrumsFeatureReelWeightUnlucky2Config", Jackpot_config="DancingDrumsJackpotUnlucky2Config"},
[7] = { id=7, base_reel_config="DancingDrumsBaseReelConfig", base_reel_weight_config="DancingDrumsBaseReelWeightUnlucky3Config", feature_reel_config="DancingDrumsFeatureReelConfig", feature_reel_weight_config="DancingDrumsFeatureReelWeightUnlucky3Config", Jackpot_config="DancingDrumsJackpotUnlucky3Config"},
[8] = { id=8, base_reel_config="DancingDrumsBaseReelConfig", base_reel_weight_config="DancingDrumsBaseReelWeight4Config", feature_reel_config="DancingDrumsFeatureReelConfig", feature_reel_weight_config="DancingDrumsFeatureReelWeightConfig", Jackpot_config="DancingDrumsJackpot3Config"},
[9] = { id=9, base_reel_config="DancingDrumsBaseReelConfig", base_reel_weight_config="DancingDrumsBaseReelWeight5Config", feature_reel_config="DancingDrumsFeatureReelConfig", feature_reel_weight_config="DancingDrumsFeatureReelWeightConfig", Jackpot_config="DancingDrumsJackpot4Config"},
[10] = { id=10, base_reel_config="DancingDrumsBaseReelConfig", base_reel_weight_config="DancingDrumsBaseReelWeight6Config", feature_reel_config="DancingDrumsFeatureReelConfig", feature_reel_weight_config="DancingDrumsFeatureReelWeightConfig", Jackpot_config="DancingDrumsJackpot3Config"},
}