macro (use_function_call_convention FUNCTION_CALL_CONVENTION)
    if (${FUNCTION_CALL_CONVENTION} STREQUAL "__cdecl")
        set(FUNCTION_CALL_CONVENTION_ARG "/Gd")
    elseif (${FUNCTION_CALL_CONVENTION} STREQUAL "__fastcall")
        set(FUNCTION_CALL_CONVENTION_ARG "/Gr")
    elseif (${FUNCTION_CALL_CONVENTION} STREQUAL "__stdcall")
        set(FUNCTION_CALL_CONVENTION_ARG "/Gz")
    elseif (${FUNCTION_CALL_CONVENTION} STREQUAL "__thiscall")
        message("Warning: FUNCTION_CALL_CONVENTION is not set, as __thiscall is deprecated.")  
    elseif (${FUNCTION_CALL_CONVENTION} STREQUAL "__pascal")
        message("Warning: FUNCTION_CALL_CONVENTION is not set, as __pascal is deprecated.")   
    endif()
endmacro()

macro (use_c_standard C_STANDARD)
    set(CMAKE_C_STANDARD "${C_STANDARD}")
endmacro()

macro (use_cxx_standard CXX_STANDARD)
    set(CMAKE_CXX_STANDARD "${CXX_STANDARD}")
endmacro()

macro (set_c_flags)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${FUNCTION_CALL_CONVENTION_ARG}")
    set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} ${FUNCTION_CALL_CONVENTION_ARG} /D__DEBUG")
    set(CMAKE_C_FLAGS_MINSIZEREL "${CMAKE_C_FLAGS_MINSIZEREL} ${FUNCTION_CALL_CONVENTION_ARG} /D__MINSIZEREL")
    set(CMAKE_C_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS_RELWITHDEBINFO} ${FUNCTION_CALL_CONVENTION_ARG} /D__RELWITHDEBINFO")
    set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} ${FUNCTION_CALL_CONVENTION_ARG} /D__RELEASE")
endmacro()

macro (set_cxx_flags)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${FUNCTION_CALL_CONVENTION_ARG}")
    set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} ${FUNCTION_CALL_CONVENTION_ARG} /D__DEBUG")
    set(CMAKE_CXX_FLAGS_MINSIZEREL "${CMAKE_CXX_FLAGS_MINSIZEREL} ${FUNCTION_CALL_CONVENTION_ARG} /D__MINSIZEREL")
    set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO} ${FUNCTION_CALL_CONVENTION_ARG} /D__RELWITHDEBINFO")
    set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${FUNCTION_CALL_CONVENTION_ARG} /D__RELEASE")
endmacro()

macro (msvc_link LINK_TYPE)
    set(COMPILER_FLAGS
        CMAKE_C_FLAGS
        CMAKE_C_FLAGS_DEBUG
        CMAKE_C_FLAGS_MINSIZEREL
        CMAKE_C_FLAGS_RELWITHDEBINFO
        CMAKE_C_FLAGS_RELEASE
        CMAKE_CXX_FLAGS
        CMAKE_CXX_FLAGS_DEBUG
        CMAKE_CXX_FLAGS_MINSIZEREL
        CMAKE_CXX_FLAGS_RELWITHDEBINFO
        CMAKE_CXX_FLAGS_RELEASE
    )

    foreach(COMPILER_FLAG ${COMPILER_FLAGS})
        if (${LINK_TYPE} STREQUAL "MT" )
            string(REPLACE "/MD" "/MT" ${COMPILER_FLAG} "${${COMPILER_FLAG}}")
        elseif(${LINK_TYPE} STREQUAL "MD")
            string(REPLACE "/MT" "/MD" ${COMPILER_FLAG} "${${COMPILER_FLAG}}")
        endif()
    endforeach()
endmacro()

macro (msvc_export_all_symbols)
    set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS YES CACHE BOOL "Export all symbols")
endmacro()