RobotLocationConfig = {
[1] = { id=1, location="Adelaide"},
[2] = { id=2, location="Alaska"},
[3] = { id=3, location="Amsterdam"},
[4] = { id=4, location="Athens"},
[5] = { id=5, location="Atlanta"},
[6] = { id=6, location="Austin"},
[7] = { id=7, location="Barcelona"},
[8] = { id=8, location="Berlin"},
[9] = { id=9, location="Birmingham"},
[10] = { id=10, location="Boston"},
[11] = { id=11, location="Bradfold"},
[12] = { id=12, location="Brussels"},
[13] = { id=13, location="Budapest"},
[14] = { id=14, location="Cambridge"},
[15] = { id=15, location="Carson"},
[16] = { id=16, location="Charleston"},
[17] = { id=17, location="Chicago"},
[18] = { id=18, location="Cleveland"},
[19] = { id=19, location="Columbia"},
[20] = { id=20, location="Copenhagen"},
[21] = { id=21, location="Dallas"},
[22] = { id=22, location="Darwin"},
[23] = { id=23, location="Denver"},
[24] = { id=24, location="Detroit"},
[25] = { id=25, location="Dublin"},
[26] = { id=26, location="Edinburgh"},
[27] = { id=27, location="Edmonton"},
[28] = { id=28, location="Frankfurt"},
[29] = { id=29, location="Geneva"},
[30] = { id=30, location="Hawaii"},
[31] = { id=31, location="Houston"},
[32] = { id=32, location="Istanbul"},
[33] = { id=33, location="Lisbon"},
[34] = { id=34, location="Liverpool"},
[35] = { id=35, location="London"},
[36] = { id=36, location="Los Angeles"},
[37] = { id=37, location="Lyon"},
[38] = { id=38, location="Madrid"},
[39] = { id=39, location="Manchester"},
[40] = { id=40, location="Manila"},
[41] = { id=41, location="Melbourne"},
[42] = { id=42, location="Montgomery"},
[43] = { id=43, location="Nagoya"},
[44] = { id=44, location="New York"},
[45] = { id=45, location="Nottingham"},
[46] = { id=46, location="Osaka"},
[47] = { id=47, location="Oslo"},
[48] = { id=48, location="Oxford"},
[49] = { id=49, location="Paris"},
[50] = { id=50, location="Perth"},
[51] = { id=51, location="Philadelphia"},
[52] = { id=52, location="Phoenix"},
[53] = { id=53, location="Pittsburgh"},
[54] = { id=54, location="Plymouth"},
[55] = { id=55, location="Prague"},
[56] = { id=56, location="Provence"},
[57] = { id=57, location="Reykjavik"},
[58] = { id=58, location="Rome"},
[59] = { id=59, location="San Antonio"},
[60] = { id=60, location="San Francisco"},
[61] = { id=61, location="San Jose"},
[62] = { id=62, location="SanDiego"},
[63] = { id=63, location="Seattle"},
[64] = { id=64, location="Stockholm"},
[65] = { id=65, location="Sydney"},
[66] = { id=66, location="Tokyo"},
[67] = { id=67, location="Toronto"},
[68] = { id=68, location="Vienna"},
[69] = { id=69, location="Warsaw"},
[70] = { id=70, location="Zagreb"},
[71] = { id=71, location="Zurich"},
}