formal_android_mirror_testaGoldMineHoldSpinPrizeConfig = {
[1] = { id=1, prize_pool={
    {prize_type = 6, prize_val = 1, weight = 1}
}},
[2] = { id=2, prize_pool={
    {prize_type = 6, prize_val = 3, weight = 1}
}},
[3] = { id=3, prize_pool={
    {prize_type = 6, prize_val = 5, weight = 1}
}},
[4] = { id=4, prize_pool={
{prize_type = 6, prize_val = 10, weight = 3}, 
{prize_type = 6, prize_val = 6, weight = 6}, 
{prize_type = 4, prize_val = 1, weight = 0},
{prize_type = 6, prize_val = 8, weight = 12},
{prize_type = 6, prize_val = 15, weight = 2},
{prize_type = 6, prize_val = 10, weight = 3},
{prize_type = 5, prize_val = 1, weight = 5},
{prize_type = 6, prize_val = 12, weight = 2},
{prize_type = 6, prize_val = 8, weight = 12},
{prize_type = 6, prize_val = 6, weight = 6},
{prize_type = 6, prize_val = 15, weight = 2},
{prize_type = 6, prize_val = 10, weight = 3},
{prize_type = 6, prize_val = 6, weight = 6},
{prize_type = 4, prize_val = 1, weight = 0},
{prize_type = 6, prize_val = 8, weight = 12},
{prize_type = 6, prize_val = 10, weight = 3},
{prize_type = 6, prize_val = 6, weight = 6},
{prize_type = 6, prize_val = 12, weight = 2},
{prize_type = 6, prize_val = 10, weight = 3},
{prize_type = 6, prize_val = 8, weight = 12}
}},
[6] = { id=6, prize_pool={
{prize_type = 5, prize_val = 1, weight = 8},
{prize_type = 6, prize_val = 15, weight = 2},
{prize_type = 6, prize_val = 18, weight = 3},
{prize_type = 6, prize_val = 25, weight = 2},
{prize_type = 6, prize_val = 10, weight = 10},
{prize_type = 4, prize_val = 1, weight = 0.5},
{prize_type = 6, prize_val = 12, weight = 15},
{prize_type = 6, prize_val = 20, weight = 2},
{prize_type = 6, prize_val = 15, weight = 2},
{prize_type = 5, prize_val = 1, weight = 8},
{prize_type = 6, prize_val = 15, weight = 2},
{prize_type = 6, prize_val = 10, weight = 10},
{prize_type = 6, prize_val = 25, weight = 2},
{prize_type = 4, prize_val = 1, weight = 0.5},
{prize_type = 6, prize_val = 20, weight = 2},
{prize_type = 6, prize_val = 18, weight = 3},
{prize_type = 5, prize_val = 1, weight = 8},
{prize_type = 6, prize_val = 12, weight = 15},
{prize_type = 6, prize_val = 20, weight = 2},
{prize_type = 6, prize_val = 18, weight = 3}
}
},
[8] = { id=8, prize_pool={
{prize_type = 6, prize_val = 25, weight = 5},
{prize_type = 4, prize_val = 1, weight = 5},
{prize_type = 6, prize_val = 30, weight = 2},
{prize_type = 6, prize_val = 35, weight = 2},
{prize_type = 6, prize_val = 20, weight = 6},
{prize_type = 5, prize_val = 1, weight = 10},
{prize_type = 6, prize_val = 15, weight = 6},
{prize_type = 6, prize_val = 30, weight = 2},
{prize_type = 4, prize_val = 1, weight = 5},
{prize_type = 6, prize_val = 15, weight = 6},
{prize_type = 6, prize_val = 20, weight = 6},
{prize_type = 6, prize_val = 18, weight = 6},
{prize_type = 5, prize_val = 1, weight = 10},
{prize_type = 6, prize_val = 35, weight = 2},
{prize_type = 6, prize_val = 30, weight = 2},
{prize_type = 6, prize_val = 25, weight = 5},
{prize_type = 6, prize_val = 18, weight = 6},
{prize_type = 5, prize_val = 1, weight = 10},
{prize_type = 6, prize_val = 35, weight = 2},
{prize_type = 6, prize_val = 30, weight = 2}
}},
[9] = { id=9, prize_pool={
{prize_type = 4, prize_val = 1, weight = 1},
{prize_type = 6, prize_val = 30, weight = 1},
{prize_type = 6, prize_val = 40, weight = 1},
{prize_type = 6, prize_val = 25, weight = 1},
{prize_type = 6, prize_val = 35, weight = 1},
{prize_type = 6, prize_val = 30, weight = 1},
{prize_type = 6, prize_val = 35, weight = 1},
{prize_type = 4, prize_val = 1, weight = 1},
{prize_type = 6, prize_val = 30, weight = 1},
{prize_type = 6, prize_val = 35, weight = 1},
{prize_type = 6, prize_val = 25, weight = 1},
{prize_type = 4, prize_val = 1, weight = 1},
{prize_type = 6, prize_val = 20, weight = 1},
{prize_type = 6, prize_val = 40, weight = 1},
{prize_type = 6, prize_val = 45, weight = 1},
{prize_type = 6, prize_val = 35, weight = 1},
{prize_type = 3, prize_val = 1, weight = 1},
{prize_type = 6, prize_val = 30, weight = 1},
{prize_type = 6, prize_val = 25, weight = 1},
{prize_type = 6, prize_val = 20, weight = 1}
}},
[10] = { id=10, prize_pool={
{prize_type = 4, prize_val = 1, weight = 1},
{prize_type = 6, prize_val = 30, weight = 1},
{prize_type = 6, prize_val = 40, weight = 1},
{prize_type = 6, prize_val = 25, weight = 1},
{prize_type = 6, prize_val = 35, weight = 1},
{prize_type = 6, prize_val = 30, weight = 1},
{prize_type = 6, prize_val = 35, weight = 1},
{prize_type = 4, prize_val = 1, weight = 1},
{prize_type = 6, prize_val = 30, weight = 1},
{prize_type = 6, prize_val = 35, weight = 1},
{prize_type = 6, prize_val = 25, weight = 1},
{prize_type = 4, prize_val = 1, weight = 1},
{prize_type = 6, prize_val = 50, weight = 1},
{prize_type = 6, prize_val = 40, weight = 1},
{prize_type = 6, prize_val = 45, weight = 1},
{prize_type = 6, prize_val = 35, weight = 1},
{prize_type = 3, prize_val = 1, weight = 1},
{prize_type = 6, prize_val = 30, weight = 1},
{prize_type = 6, prize_val = 25, weight = 1},
{prize_type = 6, prize_val = 40, weight = 1}
}},
[12] = { id=12, prize_pool={
{prize_type = 6, prize_val = 60, weight = 1},
{prize_type = 6, prize_val = 70, weight = 1},
{prize_type = 6, prize_val = 45, weight = 1},
{prize_type = 3, prize_val = 1, weight = 1},
{prize_type = 6, prize_val = 40, weight = 1},
{prize_type = 6, prize_val = 60, weight = 1},
{prize_type = 4, prize_val = 1, weight = 1},
{prize_type = 6, prize_val = 70, weight = 1},
{prize_type = 6, prize_val = 45, weight = 1},
{prize_type = 6, prize_val = 60, weight = 1},
{prize_type = 6, prize_val = 50, weight = 1},
{prize_type = 6, prize_val = 40, weight = 1},
{prize_type = 3, prize_val = 1, weight = 1},
{prize_type = 6, prize_val = 40, weight = 1},
{prize_type = 6, prize_val = 45, weight = 1},
{prize_type = 6, prize_val = 60, weight = 1},
{prize_type = 6, prize_val = 40, weight = 1},
{prize_type = 4, prize_val = 1, weight = 1},
{prize_type = 6, prize_val = 70, weight = 1},
{prize_type = 4, prize_val = 1, weight = 1},
}},
[15] = { id=15, prize_pool={
 {prize_type = 2, prize_val = 1, weight = 1},
 {prize_type = 3, prize_val = 1, weight = 1},
 {prize_type = 2, prize_val = 1, weight = 0},
 {prize_type = 3, prize_val = 1, weight = 0},
 {prize_type = 2, prize_val = 1, weight = 0},
 {prize_type = 3, prize_val = 1, weight = 0}
}},
}