_G.TableDefine = 
{
	feature_condition=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(11)",
			spin_num="int(11)",
			enter_num="int(11)",
			free_spin_count="int(11)",
			event_json="varchar(8196)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_info=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(255)",
			bet_amount="int(11)",
			free_spin_bouts="int(11)",
			free_spin_num="int(11)",
			bouts_id="int(11)",
			channel_id="varchar(128)",
			total_loss="int(11)",
			enter_chip="int(11)",
			spined_times="int(11)",
			free_total_win="int(11)",
			free_item_id="int(11)",
			json_str="varchar(8192)",
			bonus_game_type="int(11)",
			last_formation_list="varchar(8192)",
			mother_dragons_type="int(11)",
			mother_dragons_str="varchar(512)",
			raven_prophet_str="varchar(512)",
			sticky_wild_pos_list="varchar(128)",
			total_spined_times="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_info_0=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(255)",
			bet_amount="int(11)",
			free_spin_bouts="int(11)",
			free_spin_num="int(11)",
			bouts_id="int(11)",
			channel_id="varchar(128)",
			total_loss="int(11)",
			enter_chip="int(11)",
			spined_times="int(11)",
			free_total_win="int(11)",
			free_item_id="int(11)",
			json_str="varchar(8192)",
			bonus_game_type="int(11)",
			last_formation_list="varchar(8192)",
			mother_dragons_type="int(11)",
			mother_dragons_str="varchar(512)",
			raven_prophet_str="varchar(512)",
			sticky_wild_pos_list="varchar(128)",
			total_spined_times="int(11)",
			extral_spin_bouts="int(11)",
			total_spin_bouts="int(11)",
			free_spined_count="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_info_1=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(255)",
			bet_amount="int(11)",
			free_spin_bouts="int(11)",
			free_spin_num="int(11)",
			bouts_id="int(11)",
			channel_id="varchar(128)",
			total_loss="int(11)",
			enter_chip="int(11)",
			spined_times="int(11)",
			free_total_win="int(11)",
			free_item_id="int(11)",
			json_str="varchar(8192)",
			bonus_game_type="int(11)",
			last_formation_list="varchar(8192)",
			mother_dragons_type="int(11)",
			mother_dragons_str="varchar(512)",
			raven_prophet_str="varchar(512)",
			sticky_wild_pos_list="varchar(128)",
			total_spined_times="int(11)",
			extral_spin_bouts="int(11)",
			total_spin_bouts="int(11)",
			free_spined_count="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_info_10=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(255)",
			bet_amount="int(11)",
			free_spin_bouts="int(11)",
			free_spin_num="int(11)",
			bouts_id="int(11)",
			channel_id="varchar(128)",
			total_loss="int(11)",
			enter_chip="int(11)",
			spined_times="int(11)",
			free_total_win="int(11)",
			free_item_id="int(11)",
			json_str="varchar(8192)",
			bonus_game_type="int(11)",
			last_formation_list="varchar(8192)",
			mother_dragons_type="int(11)",
			mother_dragons_str="varchar(512)",
			raven_prophet_str="varchar(512)",
			sticky_wild_pos_list="varchar(128)",
			total_spined_times="int(11)",
			extral_spin_bouts="int(11)",
			total_spin_bouts="int(11)",
			free_spined_count="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_info_11=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(255)",
			bet_amount="int(11)",
			free_spin_bouts="int(11)",
			free_spin_num="int(11)",
			bouts_id="int(11)",
			channel_id="varchar(128)",
			total_loss="int(11)",
			enter_chip="int(11)",
			spined_times="int(11)",
			free_total_win="int(11)",
			free_item_id="int(11)",
			json_str="varchar(8192)",
			bonus_game_type="int(11)",
			last_formation_list="varchar(8192)",
			mother_dragons_type="int(11)",
			mother_dragons_str="varchar(512)",
			raven_prophet_str="varchar(512)",
			sticky_wild_pos_list="varchar(128)",
			total_spined_times="int(11)",
			extral_spin_bouts="int(11)",
			total_spin_bouts="int(11)",
			free_spined_count="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_info_12=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(255)",
			bet_amount="int(11)",
			free_spin_bouts="int(11)",
			free_spin_num="int(11)",
			bouts_id="int(11)",
			channel_id="varchar(128)",
			total_loss="int(11)",
			enter_chip="int(11)",
			spined_times="int(11)",
			free_total_win="int(11)",
			free_item_id="int(11)",
			json_str="varchar(8192)",
			bonus_game_type="int(11)",
			last_formation_list="varchar(8192)",
			mother_dragons_type="int(11)",
			mother_dragons_str="varchar(512)",
			raven_prophet_str="varchar(512)",
			sticky_wild_pos_list="varchar(128)",
			total_spined_times="int(11)",
			extral_spin_bouts="int(11)",
			total_spin_bouts="int(11)",
			free_spined_count="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_info_13=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(255)",
			bet_amount="int(11)",
			free_spin_bouts="int(11)",
			free_spin_num="int(11)",
			bouts_id="int(11)",
			channel_id="varchar(128)",
			total_loss="int(11)",
			enter_chip="int(11)",
			spined_times="int(11)",
			free_total_win="int(11)",
			free_item_id="int(11)",
			json_str="varchar(8192)",
			bonus_game_type="int(11)",
			last_formation_list="varchar(8192)",
			mother_dragons_type="int(11)",
			mother_dragons_str="varchar(512)",
			raven_prophet_str="varchar(512)",
			sticky_wild_pos_list="varchar(128)",
			total_spined_times="int(11)",
			extral_spin_bouts="int(11)",
			total_spin_bouts="int(11)",
			free_spined_count="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_info_14=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(255)",
			bet_amount="int(11)",
			free_spin_bouts="int(11)",
			free_spin_num="int(11)",
			bouts_id="int(11)",
			channel_id="varchar(128)",
			total_loss="int(11)",
			enter_chip="int(11)",
			spined_times="int(11)",
			free_total_win="int(11)",
			free_item_id="int(11)",
			json_str="varchar(8192)",
			bonus_game_type="int(11)",
			last_formation_list="varchar(8192)",
			mother_dragons_type="int(11)",
			mother_dragons_str="varchar(512)",
			raven_prophet_str="varchar(512)",
			sticky_wild_pos_list="varchar(128)",
			total_spined_times="int(11)",
			extral_spin_bouts="int(11)",
			total_spin_bouts="int(11)",
			free_spined_count="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_info_15=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(255)",
			bet_amount="int(11)",
			free_spin_bouts="int(11)",
			free_spin_num="int(11)",
			bouts_id="int(11)",
			channel_id="varchar(128)",
			total_loss="int(11)",
			enter_chip="int(11)",
			spined_times="int(11)",
			free_total_win="int(11)",
			free_item_id="int(11)",
			json_str="varchar(8192)",
			bonus_game_type="int(11)",
			last_formation_list="varchar(8192)",
			mother_dragons_type="int(11)",
			mother_dragons_str="varchar(512)",
			raven_prophet_str="varchar(512)",
			sticky_wild_pos_list="varchar(128)",
			total_spined_times="int(11)",
			extral_spin_bouts="int(11)",
			total_spin_bouts="int(11)",
			free_spined_count="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_info_2=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(255)",
			bet_amount="int(11)",
			free_spin_bouts="int(11)",
			free_spin_num="int(11)",
			bouts_id="int(11)",
			channel_id="varchar(128)",
			total_loss="int(11)",
			enter_chip="int(11)",
			spined_times="int(11)",
			free_total_win="int(11)",
			free_item_id="int(11)",
			json_str="varchar(8192)",
			bonus_game_type="int(11)",
			last_formation_list="varchar(8192)",
			mother_dragons_type="int(11)",
			mother_dragons_str="varchar(512)",
			raven_prophet_str="varchar(512)",
			sticky_wild_pos_list="varchar(128)",
			total_spined_times="int(11)",
			extral_spin_bouts="int(11)",
			total_spin_bouts="int(11)",
			free_spined_count="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_info_3=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(255)",
			bet_amount="int(11)",
			free_spin_bouts="int(11)",
			free_spin_num="int(11)",
			bouts_id="int(11)",
			channel_id="varchar(128)",
			total_loss="int(11)",
			enter_chip="int(11)",
			spined_times="int(11)",
			free_total_win="int(11)",
			free_item_id="int(11)",
			json_str="varchar(8192)",
			bonus_game_type="int(11)",
			last_formation_list="varchar(8192)",
			mother_dragons_type="int(11)",
			mother_dragons_str="varchar(512)",
			raven_prophet_str="varchar(512)",
			sticky_wild_pos_list="varchar(128)",
			total_spined_times="int(11)",
			extral_spin_bouts="int(11)",
			total_spin_bouts="int(11)",
			free_spined_count="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_info_4=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(255)",
			bet_amount="int(11)",
			free_spin_bouts="int(11)",
			free_spin_num="int(11)",
			bouts_id="int(11)",
			channel_id="varchar(128)",
			total_loss="int(11)",
			enter_chip="int(11)",
			spined_times="int(11)",
			free_total_win="int(11)",
			free_item_id="int(11)",
			json_str="varchar(8192)",
			bonus_game_type="int(11)",
			last_formation_list="varchar(8192)",
			mother_dragons_type="int(11)",
			mother_dragons_str="varchar(512)",
			raven_prophet_str="varchar(512)",
			sticky_wild_pos_list="varchar(128)",
			total_spined_times="int(11)",
			extral_spin_bouts="int(11)",
			total_spin_bouts="int(11)",
			free_spined_count="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_info_5=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(255)",
			bet_amount="int(11)",
			free_spin_bouts="int(11)",
			free_spin_num="int(11)",
			bouts_id="int(11)",
			channel_id="varchar(128)",
			total_loss="int(11)",
			enter_chip="int(11)",
			spined_times="int(11)",
			free_total_win="int(11)",
			free_item_id="int(11)",
			json_str="varchar(8192)",
			bonus_game_type="int(11)",
			last_formation_list="varchar(8192)",
			mother_dragons_type="int(11)",
			mother_dragons_str="varchar(512)",
			raven_prophet_str="varchar(512)",
			sticky_wild_pos_list="varchar(128)",
			total_spined_times="int(11)",
			extral_spin_bouts="int(11)",
			total_spin_bouts="int(11)",
			free_spined_count="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_info_6=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(255)",
			bet_amount="int(11)",
			free_spin_bouts="int(11)",
			free_spin_num="int(11)",
			bouts_id="int(11)",
			channel_id="varchar(128)",
			total_loss="int(11)",
			enter_chip="int(11)",
			spined_times="int(11)",
			free_total_win="int(11)",
			free_item_id="int(11)",
			json_str="varchar(8192)",
			bonus_game_type="int(11)",
			last_formation_list="varchar(8192)",
			mother_dragons_type="int(11)",
			mother_dragons_str="varchar(512)",
			raven_prophet_str="varchar(512)",
			sticky_wild_pos_list="varchar(128)",
			total_spined_times="int(11)",
			extral_spin_bouts="int(11)",
			total_spin_bouts="int(11)",
			free_spined_count="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_info_7=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(255)",
			bet_amount="int(11)",
			free_spin_bouts="int(11)",
			free_spin_num="int(11)",
			bouts_id="int(11)",
			channel_id="varchar(128)",
			total_loss="int(11)",
			enter_chip="int(11)",
			spined_times="int(11)",
			free_total_win="int(11)",
			free_item_id="int(11)",
			json_str="varchar(8192)",
			bonus_game_type="int(11)",
			last_formation_list="varchar(8192)",
			mother_dragons_type="int(11)",
			mother_dragons_str="varchar(512)",
			raven_prophet_str="varchar(512)",
			sticky_wild_pos_list="varchar(128)",
			total_spined_times="int(11)",
			extral_spin_bouts="int(11)",
			total_spin_bouts="int(11)",
			free_spined_count="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_info_8=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(255)",
			bet_amount="int(11)",
			free_spin_bouts="int(11)",
			free_spin_num="int(11)",
			bouts_id="int(11)",
			channel_id="varchar(128)",
			total_loss="int(11)",
			enter_chip="int(11)",
			spined_times="int(11)",
			free_total_win="int(11)",
			free_item_id="int(11)",
			json_str="varchar(8192)",
			bonus_game_type="int(11)",
			last_formation_list="varchar(8192)",
			mother_dragons_type="int(11)",
			mother_dragons_str="varchar(512)",
			raven_prophet_str="varchar(512)",
			sticky_wild_pos_list="varchar(128)",
			total_spined_times="int(11)",
			extral_spin_bouts="int(11)",
			total_spin_bouts="int(11)",
			free_spined_count="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_info_9=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(255)",
			bet_amount="int(11)",
			free_spin_bouts="int(11)",
			free_spin_num="int(11)",
			bouts_id="int(11)",
			channel_id="varchar(128)",
			total_loss="int(11)",
			enter_chip="int(11)",
			spined_times="int(11)",
			free_total_win="int(11)",
			free_item_id="int(11)",
			json_str="varchar(8192)",
			bonus_game_type="int(11)",
			last_formation_list="varchar(8192)",
			mother_dragons_type="int(11)",
			mother_dragons_str="varchar(512)",
			raven_prophet_str="varchar(512)",
			sticky_wild_pos_list="varchar(128)",
			total_spined_times="int(11)",
			extral_spin_bouts="int(11)",
			total_spin_bouts="int(11)",
			free_spined_count="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_status_0=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_status_1=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_status_10=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_status_11=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_status_12=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_status_13=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_status_14=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_status_15=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_status_2=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_status_3=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_status_4=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_status_5=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_status_6=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_status_7=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_status_8=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	game_status_9=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	heart_beat=
	{
		db_name = "slots_game",
		content=
		{
			id="int(11)",
			value="int(11)",
		},
		primary_keys=
		{
			"id",
		},
	},
	player_ad=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			ad_type="int(11)",
			left_times="int(11)",
			left_cd_time="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"ad_type",
		},
	},
	player_extern=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			json_str="varchar(8192)",
		},
		primary_keys=
		{
			"player_id",
		},
	},
	slots_info_0=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(11)",
			content="varchar(8192)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_info_1=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(11)",
			content="varchar(8192)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_info_10=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(11)",
			content="varchar(8192)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_info_11=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(11)",
			content="varchar(8192)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_info_12=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(11)",
			content="varchar(8192)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_info_13=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(11)",
			content="varchar(8192)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_info_14=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(11)",
			content="varchar(8192)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_info_15=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(11)",
			content="varchar(8192)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_info_2=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(11)",
			content="varchar(8192)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_info_3=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(11)",
			content="varchar(8192)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_info_4=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(11)",
			content="varchar(8192)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_info_5=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(11)",
			content="varchar(8192)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_info_6=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(11)",
			content="varchar(8192)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_info_7=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(11)",
			content="varchar(8192)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_info_8=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(11)",
			content="varchar(8192)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_info_9=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			game_type="int(11)",
			content="varchar(8192)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_status_0=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_status_1=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_status_10=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_status_11=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_status_12=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_status_13=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_status_14=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_status_15=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_status_2=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_status_3=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_status_4=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_status_5=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_status_6=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_status_7=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_status_8=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
	slots_status_9=
	{
		db_name = "slots_game",
		content=
		{
			player_id="int(11)",
			history_data="varchar(8196)",
			history_swap="varchar(1024)",
			game_type="int(11)",
		},
		primary_keys=
		{
			"player_id",
			"game_type",
		},
	},
}