ClimbSlideLevelOneMapConfig = {
[3] = { id=3, move_to_grid_id=0, grid_type=1, grid_first_arrive_weight=2, grid_normal_weight=1},
[5] = { id=5, move_to_grid_id=25, grid_type=4, grid_first_arrive_weight=2, grid_normal_weight=1},
[8] = { id=8, move_to_grid_id=31, grid_type=4, grid_first_arrive_weight=2, grid_normal_weight=1},
[10] = { id=10, move_to_grid_id=0, grid_type=1, grid_first_arrive_weight=2, grid_normal_weight=1},
[14] = { id=14, move_to_grid_id=0, grid_type=1, grid_first_arrive_weight=2, grid_normal_weight=1},
[20] = { id=20, move_to_grid_id=0, grid_type=1, grid_first_arrive_weight=2, grid_normal_weight=1},
[21] = { id=21, move_to_grid_id=37, grid_type=4, grid_first_arrive_weight=2, grid_normal_weight=1},
[25] = { id=25, move_to_grid_id=0, grid_type=1, grid_first_arrive_weight=2, grid_normal_weight=1},
[27] = { id=27, move_to_grid_id=47, grid_type=4, grid_first_arrive_weight=2, grid_normal_weight=1},
[28] = { id=28, move_to_grid_id=6, grid_type=5, grid_first_arrive_weight=1.5, grid_normal_weight=0.5},
[32] = { id=32, move_to_grid_id=0, grid_type=1, grid_first_arrive_weight=2, grid_normal_weight=1},
[39] = { id=39, move_to_grid_id=57, grid_type=4, grid_first_arrive_weight=2, grid_normal_weight=1},
[42] = { id=42, move_to_grid_id=0, grid_type=1, grid_first_arrive_weight=2, grid_normal_weight=1},
[43] = { id=43, move_to_grid_id=17, grid_type=5, grid_first_arrive_weight=1.5, grid_normal_weight=0.5},
[47] = { id=47, move_to_grid_id=0, grid_type=1, grid_first_arrive_weight=2, grid_normal_weight=1},
[48] = { id=48, move_to_grid_id=52, grid_type=4, grid_first_arrive_weight=2, grid_normal_weight=1},
[52] = { id=52, move_to_grid_id=0, grid_type=1, grid_first_arrive_weight=2, grid_normal_weight=1},
[55] = { id=55, move_to_grid_id=36, grid_type=5, grid_first_arrive_weight=1.5, grid_normal_weight=0.5},
[57] = { id=57, move_to_grid_id=0, grid_type=1, grid_first_arrive_weight=2, grid_normal_weight=1},
[60] = { id=60, move_to_grid_id=0, grid_type=6, grid_first_arrive_weight=1, grid_normal_weight=1},
}